// Code generated by ent, DO NOT EDIT.

package rechargeorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the rechargeorder type in the database.
	Label = "recharge_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldOrderNo holds the string denoting the order_no field in the database.
	FieldOrderNo = "order_no"
	// FieldExternalOrderID holds the string denoting the external_order_id field in the database.
	FieldExternalOrderID = "external_order_id"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCreditedAmount holds the string denoting the credited_amount field in the database.
	FieldCreditedAmount = "credited_amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPaidAt holds the string denoting the paid_at field in the database.
	FieldPaidAt = "paid_at"
	// FieldRefundedAt holds the string denoting the refunded_at field in the database.
	FieldRefundedAt = "refunded_at"
	// FieldCallbackIdempotencyKey holds the string denoting the callback_idempotency_key field in the database.
	FieldCallbackIdempotencyKey = "callback_idempotency_key"
	// FieldCallbackRaw holds the string denoting the callback_raw field in the database.
	FieldCallbackRaw = "callback_raw"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeReferralCommissions holds the string denoting the referral_commissions edge name in mutations.
	EdgeReferralCommissions = "referral_commissions"
	// Table holds the table name of the rechargeorder in the database.
	Table = "recharge_orders"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "recharge_orders"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// ReferralCommissionsTable is the table that holds the referral_commissions relation/edge.
	ReferralCommissionsTable = "referral_commissions"
	// ReferralCommissionsInverseTable is the table name for the ReferralCommission entity.
	// It exists in this package in order to avoid circular dependency with the "referralcommission" package.
	ReferralCommissionsInverseTable = "referral_commissions"
	// ReferralCommissionsColumn is the table column denoting the referral_commissions relation/edge.
	ReferralCommissionsColumn = "recharge_order_id"
)

// Columns holds all SQL columns for rechargeorder fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldOrderNo,
	FieldExternalOrderID,
	FieldChannel,
	FieldSource,
	FieldCurrency,
	FieldAmount,
	FieldCreditedAmount,
	FieldStatus,
	FieldPaidAt,
	FieldRefundedAt,
	FieldCallbackIdempotencyKey,
	FieldCallbackRaw,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// OrderNoValidator is a validator for the "order_no" field. It is called by the builders before save.
	OrderNoValidator func(string) error
	// ExternalOrderIDValidator is a validator for the "external_order_id" field. It is called by the builders before save.
	ExternalOrderIDValidator func(string) error
	// DefaultChannel holds the default value on creation for the "channel" field.
	DefaultChannel string
	// ChannelValidator is a validator for the "channel" field. It is called by the builders before save.
	ChannelValidator func(string) error
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount float64
	// DefaultCreditedAmount holds the default value on creation for the "credited_amount" field.
	DefaultCreditedAmount float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCallbackIdempotencyKey holds the default value on creation for the "callback_idempotency_key" field.
	DefaultCallbackIdempotencyKey string
	// CallbackIdempotencyKeyValidator is a validator for the "callback_idempotency_key" field. It is called by the builders before save.
	CallbackIdempotencyKeyValidator func(string) error
)

// OrderOption defines the ordering options for the RechargeOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByOrderNo orders the results by the order_no field.
func ByOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderNo, opts...).ToFunc()
}

// ByExternalOrderID orders the results by the external_order_id field.
func ByExternalOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalOrderID, opts...).ToFunc()
}

// ByChannel orders the results by the channel field.
func ByChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannel, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByCreditedAmount orders the results by the credited_amount field.
func ByCreditedAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditedAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPaidAt orders the results by the paid_at field.
func ByPaidAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidAt, opts...).ToFunc()
}

// ByRefundedAt orders the results by the refunded_at field.
func ByRefundedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundedAt, opts...).ToFunc()
}

// ByCallbackIdempotencyKey orders the results by the callback_idempotency_key field.
func ByCallbackIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCallbackIdempotencyKey, opts...).ToFunc()
}

// ByCallbackRaw orders the results by the callback_raw field.
func ByCallbackRaw(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCallbackRaw, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByReferralCommissionsCount orders the results by referral_commissions count.
func ByReferralCommissionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReferralCommissionsStep(), opts...)
	}
}

// ByReferralCommissions orders the results by referral_commissions terms.
func ByReferralCommissions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReferralCommissionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newReferralCommissionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReferralCommissionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReferralCommissionsTable, ReferralCommissionsColumn),
	)
}
