// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldConcurrency holds the string denoting the concurrency field in the database.
	FieldConcurrency = "concurrency"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSubscriptionLimitFallbackToBalance holds the string denoting the subscription_limit_fallback_to_balance field in the database.
	FieldSubscriptionLimitFallbackToBalance = "subscription_limit_fallback_to_balance"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldInviterID holds the string denoting the inviter_id field in the database.
	FieldInviterID = "inviter_id"
	// FieldReferralCode holds the string denoting the referral_code field in the database.
	FieldReferralCode = "referral_code"
	// FieldCustomFirstCommissionRate holds the string denoting the custom_first_commission_rate field in the database.
	FieldCustomFirstCommissionRate = "custom_first_commission_rate"
	// FieldCustomRecurringCommissionRate holds the string denoting the custom_recurring_commission_rate field in the database.
	FieldCustomRecurringCommissionRate = "custom_recurring_commission_rate"
	// FieldRecurringCommissionEnabled holds the string denoting the recurring_commission_enabled field in the database.
	FieldRecurringCommissionEnabled = "recurring_commission_enabled"
	// FieldHasSuccessfulRecharge holds the string denoting the has_successful_recharge field in the database.
	FieldHasSuccessfulRecharge = "has_successful_recharge"
	// FieldReferralWithdrawalDebt holds the string denoting the referral_withdrawal_debt field in the database.
	FieldReferralWithdrawalDebt = "referral_withdrawal_debt"
	// FieldTotpSecretEncrypted holds the string denoting the totp_secret_encrypted field in the database.
	FieldTotpSecretEncrypted = "totp_secret_encrypted"
	// FieldTotpEnabled holds the string denoting the totp_enabled field in the database.
	FieldTotpEnabled = "totp_enabled"
	// FieldTotpEnabledAt holds the string denoting the totp_enabled_at field in the database.
	FieldTotpEnabledAt = "totp_enabled_at"
	// FieldSoraStorageQuotaBytes holds the string denoting the sora_storage_quota_bytes field in the database.
	FieldSoraStorageQuotaBytes = "sora_storage_quota_bytes"
	// FieldSoraStorageUsedBytes holds the string denoting the sora_storage_used_bytes field in the database.
	FieldSoraStorageUsedBytes = "sora_storage_used_bytes"
	// EdgeAPIKeys holds the string denoting the api_keys edge name in mutations.
	EdgeAPIKeys = "api_keys"
	// EdgeRedeemCodes holds the string denoting the redeem_codes edge name in mutations.
	EdgeRedeemCodes = "redeem_codes"
	// EdgeSubscriptions holds the string denoting the subscriptions edge name in mutations.
	EdgeSubscriptions = "subscriptions"
	// EdgeAssignedSubscriptions holds the string denoting the assigned_subscriptions edge name in mutations.
	EdgeAssignedSubscriptions = "assigned_subscriptions"
	// EdgeAnnouncementReads holds the string denoting the announcement_reads edge name in mutations.
	EdgeAnnouncementReads = "announcement_reads"
	// EdgeAllowedGroups holds the string denoting the allowed_groups edge name in mutations.
	EdgeAllowedGroups = "allowed_groups"
	// EdgeUsageLogs holds the string denoting the usage_logs edge name in mutations.
	EdgeUsageLogs = "usage_logs"
	// EdgeAttributeValues holds the string denoting the attribute_values edge name in mutations.
	EdgeAttributeValues = "attribute_values"
	// EdgePromoCodeUsages holds the string denoting the promo_code_usages edge name in mutations.
	EdgePromoCodeUsages = "promo_code_usages"
	// EdgeInvitees holds the string denoting the invitees edge name in mutations.
	EdgeInvitees = "invitees"
	// EdgeInviter holds the string denoting the inviter edge name in mutations.
	EdgeInviter = "inviter"
	// EdgeRechargeOrders holds the string denoting the recharge_orders edge name in mutations.
	EdgeRechargeOrders = "recharge_orders"
	// EdgePromoterCommissions holds the string denoting the promoter_commissions edge name in mutations.
	EdgePromoterCommissions = "promoter_commissions"
	// EdgeReferredCommissions holds the string denoting the referred_commissions edge name in mutations.
	EdgeReferredCommissions = "referred_commissions"
	// EdgeReferralWithdrawalRequests holds the string denoting the referral_withdrawal_requests edge name in mutations.
	EdgeReferralWithdrawalRequests = "referral_withdrawal_requests"
	// EdgeReferralWithdrawalAllocations holds the string denoting the referral_withdrawal_allocations edge name in mutations.
	EdgeReferralWithdrawalAllocations = "referral_withdrawal_allocations"
	// EdgeReviewedReferralWithdrawals holds the string denoting the reviewed_referral_withdrawals edge name in mutations.
	EdgeReviewedReferralWithdrawals = "reviewed_referral_withdrawals"
	// EdgeUserAllowedGroups holds the string denoting the user_allowed_groups edge name in mutations.
	EdgeUserAllowedGroups = "user_allowed_groups"
	// Table holds the table name of the user in the database.
	Table = "users"
	// APIKeysTable is the table that holds the api_keys relation/edge.
	APIKeysTable = "api_keys"
	// APIKeysInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	APIKeysInverseTable = "api_keys"
	// APIKeysColumn is the table column denoting the api_keys relation/edge.
	APIKeysColumn = "user_id"
	// RedeemCodesTable is the table that holds the redeem_codes relation/edge.
	RedeemCodesTable = "redeem_codes"
	// RedeemCodesInverseTable is the table name for the RedeemCode entity.
	// It exists in this package in order to avoid circular dependency with the "redeemcode" package.
	RedeemCodesInverseTable = "redeem_codes"
	// RedeemCodesColumn is the table column denoting the redeem_codes relation/edge.
	RedeemCodesColumn = "used_by"
	// SubscriptionsTable is the table that holds the subscriptions relation/edge.
	SubscriptionsTable = "user_subscriptions"
	// SubscriptionsInverseTable is the table name for the UserSubscription entity.
	// It exists in this package in order to avoid circular dependency with the "usersubscription" package.
	SubscriptionsInverseTable = "user_subscriptions"
	// SubscriptionsColumn is the table column denoting the subscriptions relation/edge.
	SubscriptionsColumn = "user_id"
	// AssignedSubscriptionsTable is the table that holds the assigned_subscriptions relation/edge.
	AssignedSubscriptionsTable = "user_subscriptions"
	// AssignedSubscriptionsInverseTable is the table name for the UserSubscription entity.
	// It exists in this package in order to avoid circular dependency with the "usersubscription" package.
	AssignedSubscriptionsInverseTable = "user_subscriptions"
	// AssignedSubscriptionsColumn is the table column denoting the assigned_subscriptions relation/edge.
	AssignedSubscriptionsColumn = "assigned_by"
	// AnnouncementReadsTable is the table that holds the announcement_reads relation/edge.
	AnnouncementReadsTable = "announcement_reads"
	// AnnouncementReadsInverseTable is the table name for the AnnouncementRead entity.
	// It exists in this package in order to avoid circular dependency with the "announcementread" package.
	AnnouncementReadsInverseTable = "announcement_reads"
	// AnnouncementReadsColumn is the table column denoting the announcement_reads relation/edge.
	AnnouncementReadsColumn = "user_id"
	// AllowedGroupsTable is the table that holds the allowed_groups relation/edge. The primary key declared below.
	AllowedGroupsTable = "user_allowed_groups"
	// AllowedGroupsInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	AllowedGroupsInverseTable = "groups"
	// UsageLogsTable is the table that holds the usage_logs relation/edge.
	UsageLogsTable = "usage_logs"
	// UsageLogsInverseTable is the table name for the UsageLog entity.
	// It exists in this package in order to avoid circular dependency with the "usagelog" package.
	UsageLogsInverseTable = "usage_logs"
	// UsageLogsColumn is the table column denoting the usage_logs relation/edge.
	UsageLogsColumn = "user_id"
	// AttributeValuesTable is the table that holds the attribute_values relation/edge.
	AttributeValuesTable = "user_attribute_values"
	// AttributeValuesInverseTable is the table name for the UserAttributeValue entity.
	// It exists in this package in order to avoid circular dependency with the "userattributevalue" package.
	AttributeValuesInverseTable = "user_attribute_values"
	// AttributeValuesColumn is the table column denoting the attribute_values relation/edge.
	AttributeValuesColumn = "user_id"
	// PromoCodeUsagesTable is the table that holds the promo_code_usages relation/edge.
	PromoCodeUsagesTable = "promo_code_usages"
	// PromoCodeUsagesInverseTable is the table name for the PromoCodeUsage entity.
	// It exists in this package in order to avoid circular dependency with the "promocodeusage" package.
	PromoCodeUsagesInverseTable = "promo_code_usages"
	// PromoCodeUsagesColumn is the table column denoting the promo_code_usages relation/edge.
	PromoCodeUsagesColumn = "user_id"
	// InviteesTable is the table that holds the invitees relation/edge.
	InviteesTable = "users"
	// InviteesColumn is the table column denoting the invitees relation/edge.
	InviteesColumn = "inviter_id"
	// InviterTable is the table that holds the inviter relation/edge.
	InviterTable = "users"
	// InviterColumn is the table column denoting the inviter relation/edge.
	InviterColumn = "inviter_id"
	// RechargeOrdersTable is the table that holds the recharge_orders relation/edge.
	RechargeOrdersTable = "recharge_orders"
	// RechargeOrdersInverseTable is the table name for the RechargeOrder entity.
	// It exists in this package in order to avoid circular dependency with the "rechargeorder" package.
	RechargeOrdersInverseTable = "recharge_orders"
	// RechargeOrdersColumn is the table column denoting the recharge_orders relation/edge.
	RechargeOrdersColumn = "user_id"
	// PromoterCommissionsTable is the table that holds the promoter_commissions relation/edge.
	PromoterCommissionsTable = "referral_commissions"
	// PromoterCommissionsInverseTable is the table name for the ReferralCommission entity.
	// It exists in this package in order to avoid circular dependency with the "referralcommission" package.
	PromoterCommissionsInverseTable = "referral_commissions"
	// PromoterCommissionsColumn is the table column denoting the promoter_commissions relation/edge.
	PromoterCommissionsColumn = "promoter_user_id"
	// ReferredCommissionsTable is the table that holds the referred_commissions relation/edge.
	ReferredCommissionsTable = "referral_commissions"
	// ReferredCommissionsInverseTable is the table name for the ReferralCommission entity.
	// It exists in this package in order to avoid circular dependency with the "referralcommission" package.
	ReferredCommissionsInverseTable = "referral_commissions"
	// ReferredCommissionsColumn is the table column denoting the referred_commissions relation/edge.
	ReferredCommissionsColumn = "referred_user_id"
	// ReferralWithdrawalRequestsTable is the table that holds the referral_withdrawal_requests relation/edge.
	ReferralWithdrawalRequestsTable = "referral_withdrawal_requests"
	// ReferralWithdrawalRequestsInverseTable is the table name for the ReferralWithdrawalRequest entity.
	// It exists in this package in order to avoid circular dependency with the "referralwithdrawalrequest" package.
	ReferralWithdrawalRequestsInverseTable = "referral_withdrawal_requests"
	// ReferralWithdrawalRequestsColumn is the table column denoting the referral_withdrawal_requests relation/edge.
	ReferralWithdrawalRequestsColumn = "promoter_user_id"
	// ReferralWithdrawalAllocationsTable is the table that holds the referral_withdrawal_allocations relation/edge.
	ReferralWithdrawalAllocationsTable = "referral_withdrawal_allocations"
	// ReferralWithdrawalAllocationsInverseTable is the table name for the ReferralWithdrawalAllocation entity.
	// It exists in this package in order to avoid circular dependency with the "referralwithdrawalallocation" package.
	ReferralWithdrawalAllocationsInverseTable = "referral_withdrawal_allocations"
	// ReferralWithdrawalAllocationsColumn is the table column denoting the referral_withdrawal_allocations relation/edge.
	ReferralWithdrawalAllocationsColumn = "promoter_user_id"
	// ReviewedReferralWithdrawalsTable is the table that holds the reviewed_referral_withdrawals relation/edge.
	ReviewedReferralWithdrawalsTable = "referral_withdrawal_requests"
	// ReviewedReferralWithdrawalsInverseTable is the table name for the ReferralWithdrawalRequest entity.
	// It exists in this package in order to avoid circular dependency with the "referralwithdrawalrequest" package.
	ReviewedReferralWithdrawalsInverseTable = "referral_withdrawal_requests"
	// ReviewedReferralWithdrawalsColumn is the table column denoting the reviewed_referral_withdrawals relation/edge.
	ReviewedReferralWithdrawalsColumn = "reviewer_user_id"
	// UserAllowedGroupsTable is the table that holds the user_allowed_groups relation/edge.
	UserAllowedGroupsTable = "user_allowed_groups"
	// UserAllowedGroupsInverseTable is the table name for the UserAllowedGroup entity.
	// It exists in this package in order to avoid circular dependency with the "userallowedgroup" package.
	UserAllowedGroupsInverseTable = "user_allowed_groups"
	// UserAllowedGroupsColumn is the table column denoting the user_allowed_groups relation/edge.
	UserAllowedGroupsColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldEmail,
	FieldPasswordHash,
	FieldRole,
	FieldBalance,
	FieldConcurrency,
	FieldStatus,
	FieldSubscriptionLimitFallbackToBalance,
	FieldUsername,
	FieldNotes,
	FieldInviterID,
	FieldReferralCode,
	FieldCustomFirstCommissionRate,
	FieldCustomRecurringCommissionRate,
	FieldRecurringCommissionEnabled,
	FieldHasSuccessfulRecharge,
	FieldReferralWithdrawalDebt,
	FieldTotpSecretEncrypted,
	FieldTotpEnabled,
	FieldTotpEnabledAt,
	FieldSoraStorageQuotaBytes,
	FieldSoraStorageUsedBytes,
}

var (
	// AllowedGroupsPrimaryKey and AllowedGroupsColumn2 are the table columns denoting the
	// primary key for the allowed_groups relation (M2M).
	AllowedGroupsPrimaryKey = []string{"user_id", "group_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	PasswordHashValidator func(string) error
	// DefaultRole holds the default value on creation for the "role" field.
	DefaultRole string
	// RoleValidator is a validator for the "role" field. It is called by the builders before save.
	RoleValidator func(string) error
	// DefaultBalance holds the default value on creation for the "balance" field.
	DefaultBalance float64
	// DefaultConcurrency holds the default value on creation for the "concurrency" field.
	DefaultConcurrency int
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultSubscriptionLimitFallbackToBalance holds the default value on creation for the "subscription_limit_fallback_to_balance" field.
	DefaultSubscriptionLimitFallbackToBalance bool
	// DefaultUsername holds the default value on creation for the "username" field.
	DefaultUsername string
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// DefaultNotes holds the default value on creation for the "notes" field.
	DefaultNotes string
	// DefaultReferralCode holds the default value on creation for the "referral_code" field.
	DefaultReferralCode string
	// ReferralCodeValidator is a validator for the "referral_code" field. It is called by the builders before save.
	ReferralCodeValidator func(string) error
	// DefaultRecurringCommissionEnabled holds the default value on creation for the "recurring_commission_enabled" field.
	DefaultRecurringCommissionEnabled bool
	// DefaultHasSuccessfulRecharge holds the default value on creation for the "has_successful_recharge" field.
	DefaultHasSuccessfulRecharge bool
	// DefaultReferralWithdrawalDebt holds the default value on creation for the "referral_withdrawal_debt" field.
	DefaultReferralWithdrawalDebt float64
	// DefaultTotpEnabled holds the default value on creation for the "totp_enabled" field.
	DefaultTotpEnabled bool
	// DefaultSoraStorageQuotaBytes holds the default value on creation for the "sora_storage_quota_bytes" field.
	DefaultSoraStorageQuotaBytes int64
	// DefaultSoraStorageUsedBytes holds the default value on creation for the "sora_storage_used_bytes" field.
	DefaultSoraStorageUsedBytes int64
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByBalance orders the results by the balance field.
func ByBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalance, opts...).ToFunc()
}

// ByConcurrency orders the results by the concurrency field.
func ByConcurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConcurrency, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySubscriptionLimitFallbackToBalance orders the results by the subscription_limit_fallback_to_balance field.
func BySubscriptionLimitFallbackToBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionLimitFallbackToBalance, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByInviterID orders the results by the inviter_id field.
func ByInviterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviterID, opts...).ToFunc()
}

// ByReferralCode orders the results by the referral_code field.
func ByReferralCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferralCode, opts...).ToFunc()
}

// ByCustomFirstCommissionRate orders the results by the custom_first_commission_rate field.
func ByCustomFirstCommissionRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomFirstCommissionRate, opts...).ToFunc()
}

// ByCustomRecurringCommissionRate orders the results by the custom_recurring_commission_rate field.
func ByCustomRecurringCommissionRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomRecurringCommissionRate, opts...).ToFunc()
}

// ByRecurringCommissionEnabled orders the results by the recurring_commission_enabled field.
func ByRecurringCommissionEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecurringCommissionEnabled, opts...).ToFunc()
}

// ByHasSuccessfulRecharge orders the results by the has_successful_recharge field.
func ByHasSuccessfulRecharge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHasSuccessfulRecharge, opts...).ToFunc()
}

// ByReferralWithdrawalDebt orders the results by the referral_withdrawal_debt field.
func ByReferralWithdrawalDebt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferralWithdrawalDebt, opts...).ToFunc()
}

// ByTotpSecretEncrypted orders the results by the totp_secret_encrypted field.
func ByTotpSecretEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotpSecretEncrypted, opts...).ToFunc()
}

// ByTotpEnabled orders the results by the totp_enabled field.
func ByTotpEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotpEnabled, opts...).ToFunc()
}

// ByTotpEnabledAt orders the results by the totp_enabled_at field.
func ByTotpEnabledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotpEnabledAt, opts...).ToFunc()
}

// BySoraStorageQuotaBytes orders the results by the sora_storage_quota_bytes field.
func BySoraStorageQuotaBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSoraStorageQuotaBytes, opts...).ToFunc()
}

// BySoraStorageUsedBytes orders the results by the sora_storage_used_bytes field.
func BySoraStorageUsedBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSoraStorageUsedBytes, opts...).ToFunc()
}

// ByAPIKeysCount orders the results by api_keys count.
func ByAPIKeysCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAPIKeysStep(), opts...)
	}
}

// ByAPIKeys orders the results by api_keys terms.
func ByAPIKeys(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeysStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRedeemCodesCount orders the results by redeem_codes count.
func ByRedeemCodesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRedeemCodesStep(), opts...)
	}
}

// ByRedeemCodes orders the results by redeem_codes terms.
func ByRedeemCodes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRedeemCodesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySubscriptionsCount orders the results by subscriptions count.
func BySubscriptionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSubscriptionsStep(), opts...)
	}
}

// BySubscriptions orders the results by subscriptions terms.
func BySubscriptions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubscriptionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAssignedSubscriptionsCount orders the results by assigned_subscriptions count.
func ByAssignedSubscriptionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAssignedSubscriptionsStep(), opts...)
	}
}

// ByAssignedSubscriptions orders the results by assigned_subscriptions terms.
func ByAssignedSubscriptions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssignedSubscriptionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAnnouncementReadsCount orders the results by announcement_reads count.
func ByAnnouncementReadsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAnnouncementReadsStep(), opts...)
	}
}

// ByAnnouncementReads orders the results by announcement_reads terms.
func ByAnnouncementReads(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAnnouncementReadsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAllowedGroupsCount orders the results by allowed_groups count.
func ByAllowedGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAllowedGroupsStep(), opts...)
	}
}

// ByAllowedGroups orders the results by allowed_groups terms.
func ByAllowedGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAllowedGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUsageLogsCount orders the results by usage_logs count.
func ByUsageLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsageLogsStep(), opts...)
	}
}

// ByUsageLogs orders the results by usage_logs terms.
func ByUsageLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsageLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAttributeValuesCount orders the results by attribute_values count.
func ByAttributeValuesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAttributeValuesStep(), opts...)
	}
}

// ByAttributeValues orders the results by attribute_values terms.
func ByAttributeValues(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAttributeValuesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPromoCodeUsagesCount orders the results by promo_code_usages count.
func ByPromoCodeUsagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPromoCodeUsagesStep(), opts...)
	}
}

// ByPromoCodeUsages orders the results by promo_code_usages terms.
func ByPromoCodeUsages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPromoCodeUsagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByInviteesCount orders the results by invitees count.
func ByInviteesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInviteesStep(), opts...)
	}
}

// ByInvitees orders the results by invitees terms.
func ByInvitees(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInviteesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByInviterField orders the results by inviter field.
func ByInviterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInviterStep(), sql.OrderByField(field, opts...))
	}
}

// ByRechargeOrdersCount orders the results by recharge_orders count.
func ByRechargeOrdersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRechargeOrdersStep(), opts...)
	}
}

// ByRechargeOrders orders the results by recharge_orders terms.
func ByRechargeOrders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRechargeOrdersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPromoterCommissionsCount orders the results by promoter_commissions count.
func ByPromoterCommissionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPromoterCommissionsStep(), opts...)
	}
}

// ByPromoterCommissions orders the results by promoter_commissions terms.
func ByPromoterCommissions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPromoterCommissionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReferredCommissionsCount orders the results by referred_commissions count.
func ByReferredCommissionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReferredCommissionsStep(), opts...)
	}
}

// ByReferredCommissions orders the results by referred_commissions terms.
func ByReferredCommissions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReferredCommissionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReferralWithdrawalRequestsCount orders the results by referral_withdrawal_requests count.
func ByReferralWithdrawalRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReferralWithdrawalRequestsStep(), opts...)
	}
}

// ByReferralWithdrawalRequests orders the results by referral_withdrawal_requests terms.
func ByReferralWithdrawalRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReferralWithdrawalRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReferralWithdrawalAllocationsCount orders the results by referral_withdrawal_allocations count.
func ByReferralWithdrawalAllocationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReferralWithdrawalAllocationsStep(), opts...)
	}
}

// ByReferralWithdrawalAllocations orders the results by referral_withdrawal_allocations terms.
func ByReferralWithdrawalAllocations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReferralWithdrawalAllocationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReviewedReferralWithdrawalsCount orders the results by reviewed_referral_withdrawals count.
func ByReviewedReferralWithdrawalsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReviewedReferralWithdrawalsStep(), opts...)
	}
}

// ByReviewedReferralWithdrawals orders the results by reviewed_referral_withdrawals terms.
func ByReviewedReferralWithdrawals(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReviewedReferralWithdrawalsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserAllowedGroupsCount orders the results by user_allowed_groups count.
func ByUserAllowedGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserAllowedGroupsStep(), opts...)
	}
}

// ByUserAllowedGroups orders the results by user_allowed_groups terms.
func ByUserAllowedGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserAllowedGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAPIKeysStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeysInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, APIKeysTable, APIKeysColumn),
	)
}
func newRedeemCodesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RedeemCodesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RedeemCodesTable, RedeemCodesColumn),
	)
}
func newSubscriptionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubscriptionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SubscriptionsTable, SubscriptionsColumn),
	)
}
func newAssignedSubscriptionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssignedSubscriptionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AssignedSubscriptionsTable, AssignedSubscriptionsColumn),
	)
}
func newAnnouncementReadsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AnnouncementReadsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AnnouncementReadsTable, AnnouncementReadsColumn),
	)
}
func newAllowedGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AllowedGroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, AllowedGroupsTable, AllowedGroupsPrimaryKey...),
	)
}
func newUsageLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsageLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
	)
}
func newAttributeValuesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AttributeValuesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AttributeValuesTable, AttributeValuesColumn),
	)
}
func newPromoCodeUsagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PromoCodeUsagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PromoCodeUsagesTable, PromoCodeUsagesColumn),
	)
}
func newInviteesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, InviteesTable, InviteesColumn),
	)
}
func newInviterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InviterTable, InviterColumn),
	)
}
func newRechargeOrdersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RechargeOrdersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RechargeOrdersTable, RechargeOrdersColumn),
	)
}
func newPromoterCommissionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PromoterCommissionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PromoterCommissionsTable, PromoterCommissionsColumn),
	)
}
func newReferredCommissionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReferredCommissionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReferredCommissionsTable, ReferredCommissionsColumn),
	)
}
func newReferralWithdrawalRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReferralWithdrawalRequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReferralWithdrawalRequestsTable, ReferralWithdrawalRequestsColumn),
	)
}
func newReferralWithdrawalAllocationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReferralWithdrawalAllocationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReferralWithdrawalAllocationsTable, ReferralWithdrawalAllocationsColumn),
	)
}
func newReviewedReferralWithdrawalsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReviewedReferralWithdrawalsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReviewedReferralWithdrawalsTable, ReviewedReferralWithdrawalsColumn),
	)
}
func newUserAllowedGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserAllowedGroupsInverseTable, UserAllowedGroupsColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, UserAllowedGroupsTable, UserAllowedGroupsColumn),
	)
}
