// Code generated by ent, DO NOT EDIT.

package referralwithdrawalallocation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldEQ(FieldUpdatedAt, v))
}

// PromoterUserID applies equality check predicate on the "promoter_user_id" field. It's identical to PromoterUserIDEQ.
func PromoterUserID(v int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldEQ(FieldPromoterUserID, v))
}

// WithdrawalRequestID applies equality check predicate on the "withdrawal_request_id" field. It's identical to WithdrawalRequestIDEQ.
func WithdrawalRequestID(v int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldEQ(FieldWithdrawalRequestID, v))
}

// CommissionID applies equality check predicate on the "commission_id" field. It's identical to CommissionIDEQ.
func CommissionID(v int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldEQ(FieldCommissionID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldEQ(FieldAmount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldLTE(FieldUpdatedAt, v))
}

// PromoterUserIDEQ applies the EQ predicate on the "promoter_user_id" field.
func PromoterUserIDEQ(v int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldEQ(FieldPromoterUserID, v))
}

// PromoterUserIDNEQ applies the NEQ predicate on the "promoter_user_id" field.
func PromoterUserIDNEQ(v int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldNEQ(FieldPromoterUserID, v))
}

// PromoterUserIDIn applies the In predicate on the "promoter_user_id" field.
func PromoterUserIDIn(vs ...int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldIn(FieldPromoterUserID, vs...))
}

// PromoterUserIDNotIn applies the NotIn predicate on the "promoter_user_id" field.
func PromoterUserIDNotIn(vs ...int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldNotIn(FieldPromoterUserID, vs...))
}

// WithdrawalRequestIDEQ applies the EQ predicate on the "withdrawal_request_id" field.
func WithdrawalRequestIDEQ(v int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldEQ(FieldWithdrawalRequestID, v))
}

// WithdrawalRequestIDNEQ applies the NEQ predicate on the "withdrawal_request_id" field.
func WithdrawalRequestIDNEQ(v int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldNEQ(FieldWithdrawalRequestID, v))
}

// WithdrawalRequestIDIn applies the In predicate on the "withdrawal_request_id" field.
func WithdrawalRequestIDIn(vs ...int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldIn(FieldWithdrawalRequestID, vs...))
}

// WithdrawalRequestIDNotIn applies the NotIn predicate on the "withdrawal_request_id" field.
func WithdrawalRequestIDNotIn(vs ...int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldNotIn(FieldWithdrawalRequestID, vs...))
}

// CommissionIDEQ applies the EQ predicate on the "commission_id" field.
func CommissionIDEQ(v int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldEQ(FieldCommissionID, v))
}

// CommissionIDNEQ applies the NEQ predicate on the "commission_id" field.
func CommissionIDNEQ(v int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldNEQ(FieldCommissionID, v))
}

// CommissionIDIn applies the In predicate on the "commission_id" field.
func CommissionIDIn(vs ...int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldIn(FieldCommissionID, vs...))
}

// CommissionIDNotIn applies the NotIn predicate on the "commission_id" field.
func CommissionIDNotIn(vs ...int64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldNotIn(FieldCommissionID, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.FieldLTE(FieldAmount, v))
}

// HasPromoter applies the HasEdge predicate on the "promoter" edge.
func HasPromoter() predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PromoterTable, PromoterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPromoterWith applies the HasEdge predicate on the "promoter" edge with a given conditions (other predicates).
func HasPromoterWith(preds ...predicate.User) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(func(s *sql.Selector) {
		step := newPromoterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWithdrawalRequest applies the HasEdge predicate on the "withdrawal_request" edge.
func HasWithdrawalRequest() predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WithdrawalRequestTable, WithdrawalRequestColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWithdrawalRequestWith applies the HasEdge predicate on the "withdrawal_request" edge with a given conditions (other predicates).
func HasWithdrawalRequestWith(preds ...predicate.ReferralWithdrawalRequest) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(func(s *sql.Selector) {
		step := newWithdrawalRequestStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCommission applies the HasEdge predicate on the "commission" edge.
func HasCommission() predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CommissionTable, CommissionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommissionWith applies the HasEdge predicate on the "commission" edge with a given conditions (other predicates).
func HasCommissionWith(preds ...predicate.ReferralCommission) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(func(s *sql.Selector) {
		step := newCommissionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReferralWithdrawalAllocation) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReferralWithdrawalAllocation) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReferralWithdrawalAllocation) predicate.ReferralWithdrawalAllocation {
	return predicate.ReferralWithdrawalAllocation(sql.NotPredicates(p))
}
