// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rechargeorder"
	"github.com/Wei-Shaw/sub2api/ent/referralcommission"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RechargeOrderUpdate is the builder for updating RechargeOrder entities.
type RechargeOrderUpdate struct {
	config
	hooks    []Hook
	mutation *RechargeOrderMutation
}

// Where appends a list predicates to the RechargeOrderUpdate builder.
func (_u *RechargeOrderUpdate) Where(ps ...predicate.RechargeOrder) *RechargeOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RechargeOrderUpdate) SetUpdatedAt(v time.Time) *RechargeOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RechargeOrderUpdate) SetUserID(v int64) *RechargeOrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableUserID(v *int64) *RechargeOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *RechargeOrderUpdate) SetOrderNo(v string) *RechargeOrderUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableOrderNo(v *string) *RechargeOrderUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetExternalOrderID sets the "external_order_id" field.
func (_u *RechargeOrderUpdate) SetExternalOrderID(v string) *RechargeOrderUpdate {
	_u.mutation.SetExternalOrderID(v)
	return _u
}

// SetNillableExternalOrderID sets the "external_order_id" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableExternalOrderID(v *string) *RechargeOrderUpdate {
	if v != nil {
		_u.SetExternalOrderID(*v)
	}
	return _u
}

// ClearExternalOrderID clears the value of the "external_order_id" field.
func (_u *RechargeOrderUpdate) ClearExternalOrderID() *RechargeOrderUpdate {
	_u.mutation.ClearExternalOrderID()
	return _u
}

// SetChannel sets the "channel" field.
func (_u *RechargeOrderUpdate) SetChannel(v string) *RechargeOrderUpdate {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableChannel(v *string) *RechargeOrderUpdate {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *RechargeOrderUpdate) SetSource(v string) *RechargeOrderUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableSource(v *string) *RechargeOrderUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *RechargeOrderUpdate) SetCurrency(v string) *RechargeOrderUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableCurrency(v *string) *RechargeOrderUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RechargeOrderUpdate) SetAmount(v float64) *RechargeOrderUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableAmount(v *float64) *RechargeOrderUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *RechargeOrderUpdate) AddAmount(v float64) *RechargeOrderUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCreditedAmount sets the "credited_amount" field.
func (_u *RechargeOrderUpdate) SetCreditedAmount(v float64) *RechargeOrderUpdate {
	_u.mutation.ResetCreditedAmount()
	_u.mutation.SetCreditedAmount(v)
	return _u
}

// SetNillableCreditedAmount sets the "credited_amount" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableCreditedAmount(v *float64) *RechargeOrderUpdate {
	if v != nil {
		_u.SetCreditedAmount(*v)
	}
	return _u
}

// AddCreditedAmount adds value to the "credited_amount" field.
func (_u *RechargeOrderUpdate) AddCreditedAmount(v float64) *RechargeOrderUpdate {
	_u.mutation.AddCreditedAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *RechargeOrderUpdate) SetStatus(v string) *RechargeOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableStatus(v *string) *RechargeOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *RechargeOrderUpdate) SetPaidAt(v time.Time) *RechargeOrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillablePaidAt(v *time.Time) *RechargeOrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *RechargeOrderUpdate) ClearPaidAt() *RechargeOrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetRefundedAt sets the "refunded_at" field.
func (_u *RechargeOrderUpdate) SetRefundedAt(v time.Time) *RechargeOrderUpdate {
	_u.mutation.SetRefundedAt(v)
	return _u
}

// SetNillableRefundedAt sets the "refunded_at" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableRefundedAt(v *time.Time) *RechargeOrderUpdate {
	if v != nil {
		_u.SetRefundedAt(*v)
	}
	return _u
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (_u *RechargeOrderUpdate) ClearRefundedAt() *RechargeOrderUpdate {
	_u.mutation.ClearRefundedAt()
	return _u
}

// SetCallbackIdempotencyKey sets the "callback_idempotency_key" field.
func (_u *RechargeOrderUpdate) SetCallbackIdempotencyKey(v string) *RechargeOrderUpdate {
	_u.mutation.SetCallbackIdempotencyKey(v)
	return _u
}

// SetNillableCallbackIdempotencyKey sets the "callback_idempotency_key" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableCallbackIdempotencyKey(v *string) *RechargeOrderUpdate {
	if v != nil {
		_u.SetCallbackIdempotencyKey(*v)
	}
	return _u
}

// SetCallbackRaw sets the "callback_raw" field.
func (_u *RechargeOrderUpdate) SetCallbackRaw(v string) *RechargeOrderUpdate {
	_u.mutation.SetCallbackRaw(v)
	return _u
}

// SetNillableCallbackRaw sets the "callback_raw" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableCallbackRaw(v *string) *RechargeOrderUpdate {
	if v != nil {
		_u.SetCallbackRaw(*v)
	}
	return _u
}

// ClearCallbackRaw clears the value of the "callback_raw" field.
func (_u *RechargeOrderUpdate) ClearCallbackRaw() *RechargeOrderUpdate {
	_u.mutation.ClearCallbackRaw()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *RechargeOrderUpdate) SetNotes(v string) *RechargeOrderUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableNotes(v *string) *RechargeOrderUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *RechargeOrderUpdate) ClearNotes() *RechargeOrderUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RechargeOrderUpdate) SetUser(v *User) *RechargeOrderUpdate {
	return _u.SetUserID(v.ID)
}

// AddReferralCommissionIDs adds the "referral_commissions" edge to the ReferralCommission entity by IDs.
func (_u *RechargeOrderUpdate) AddReferralCommissionIDs(ids ...int64) *RechargeOrderUpdate {
	_u.mutation.AddReferralCommissionIDs(ids...)
	return _u
}

// AddReferralCommissions adds the "referral_commissions" edges to the ReferralCommission entity.
func (_u *RechargeOrderUpdate) AddReferralCommissions(v ...*ReferralCommission) *RechargeOrderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReferralCommissionIDs(ids...)
}

// Mutation returns the RechargeOrderMutation object of the builder.
func (_u *RechargeOrderUpdate) Mutation() *RechargeOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RechargeOrderUpdate) ClearUser() *RechargeOrderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearReferralCommissions clears all "referral_commissions" edges to the ReferralCommission entity.
func (_u *RechargeOrderUpdate) ClearReferralCommissions() *RechargeOrderUpdate {
	_u.mutation.ClearReferralCommissions()
	return _u
}

// RemoveReferralCommissionIDs removes the "referral_commissions" edge to ReferralCommission entities by IDs.
func (_u *RechargeOrderUpdate) RemoveReferralCommissionIDs(ids ...int64) *RechargeOrderUpdate {
	_u.mutation.RemoveReferralCommissionIDs(ids...)
	return _u
}

// RemoveReferralCommissions removes "referral_commissions" edges to ReferralCommission entities.
func (_u *RechargeOrderUpdate) RemoveReferralCommissions(v ...*ReferralCommission) *RechargeOrderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReferralCommissionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RechargeOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RechargeOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RechargeOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RechargeOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RechargeOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rechargeorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RechargeOrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := rechargeorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalOrderID(); ok {
		if err := rechargeorder.ExternalOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "external_order_id", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.external_order_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Channel(); ok {
		if err := rechargeorder.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.channel": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := rechargeorder.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := rechargeorder.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rechargeorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CallbackIdempotencyKey(); ok {
		if err := rechargeorder.CallbackIdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "callback_idempotency_key", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.callback_idempotency_key": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RechargeOrder.user"`)
	}
	return nil
}

func (_u *RechargeOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rechargeorder.Table, rechargeorder.Columns, sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargeorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(rechargeorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalOrderID(); ok {
		_spec.SetField(rechargeorder.FieldExternalOrderID, field.TypeString, value)
	}
	if _u.mutation.ExternalOrderIDCleared() {
		_spec.ClearField(rechargeorder.FieldExternalOrderID, field.TypeString)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(rechargeorder.FieldChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(rechargeorder.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(rechargeorder.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(rechargeorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(rechargeorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreditedAmount(); ok {
		_spec.SetField(rechargeorder.FieldCreditedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditedAmount(); ok {
		_spec.AddField(rechargeorder.FieldCreditedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rechargeorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(rechargeorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(rechargeorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RefundedAt(); ok {
		_spec.SetField(rechargeorder.FieldRefundedAt, field.TypeTime, value)
	}
	if _u.mutation.RefundedAtCleared() {
		_spec.ClearField(rechargeorder.FieldRefundedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CallbackIdempotencyKey(); ok {
		_spec.SetField(rechargeorder.FieldCallbackIdempotencyKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.CallbackRaw(); ok {
		_spec.SetField(rechargeorder.FieldCallbackRaw, field.TypeString, value)
	}
	if _u.mutation.CallbackRawCleared() {
		_spec.ClearField(rechargeorder.FieldCallbackRaw, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(rechargeorder.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(rechargeorder.FieldNotes, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rechargeorder.UserTable,
			Columns: []string{rechargeorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rechargeorder.UserTable,
			Columns: []string{rechargeorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReferralCommissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeorder.ReferralCommissionsTable,
			Columns: []string{rechargeorder.ReferralCommissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReferralCommissionsIDs(); len(nodes) > 0 && !_u.mutation.ReferralCommissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeorder.ReferralCommissionsTable,
			Columns: []string{rechargeorder.ReferralCommissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferralCommissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeorder.ReferralCommissionsTable,
			Columns: []string{rechargeorder.ReferralCommissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rechargeorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RechargeOrderUpdateOne is the builder for updating a single RechargeOrder entity.
type RechargeOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RechargeOrderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RechargeOrderUpdateOne) SetUpdatedAt(v time.Time) *RechargeOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RechargeOrderUpdateOne) SetUserID(v int64) *RechargeOrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableUserID(v *int64) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *RechargeOrderUpdateOne) SetOrderNo(v string) *RechargeOrderUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableOrderNo(v *string) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetExternalOrderID sets the "external_order_id" field.
func (_u *RechargeOrderUpdateOne) SetExternalOrderID(v string) *RechargeOrderUpdateOne {
	_u.mutation.SetExternalOrderID(v)
	return _u
}

// SetNillableExternalOrderID sets the "external_order_id" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableExternalOrderID(v *string) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetExternalOrderID(*v)
	}
	return _u
}

// ClearExternalOrderID clears the value of the "external_order_id" field.
func (_u *RechargeOrderUpdateOne) ClearExternalOrderID() *RechargeOrderUpdateOne {
	_u.mutation.ClearExternalOrderID()
	return _u
}

// SetChannel sets the "channel" field.
func (_u *RechargeOrderUpdateOne) SetChannel(v string) *RechargeOrderUpdateOne {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableChannel(v *string) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *RechargeOrderUpdateOne) SetSource(v string) *RechargeOrderUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableSource(v *string) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *RechargeOrderUpdateOne) SetCurrency(v string) *RechargeOrderUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableCurrency(v *string) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RechargeOrderUpdateOne) SetAmount(v float64) *RechargeOrderUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableAmount(v *float64) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *RechargeOrderUpdateOne) AddAmount(v float64) *RechargeOrderUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCreditedAmount sets the "credited_amount" field.
func (_u *RechargeOrderUpdateOne) SetCreditedAmount(v float64) *RechargeOrderUpdateOne {
	_u.mutation.ResetCreditedAmount()
	_u.mutation.SetCreditedAmount(v)
	return _u
}

// SetNillableCreditedAmount sets the "credited_amount" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableCreditedAmount(v *float64) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetCreditedAmount(*v)
	}
	return _u
}

// AddCreditedAmount adds value to the "credited_amount" field.
func (_u *RechargeOrderUpdateOne) AddCreditedAmount(v float64) *RechargeOrderUpdateOne {
	_u.mutation.AddCreditedAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *RechargeOrderUpdateOne) SetStatus(v string) *RechargeOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableStatus(v *string) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *RechargeOrderUpdateOne) SetPaidAt(v time.Time) *RechargeOrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillablePaidAt(v *time.Time) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *RechargeOrderUpdateOne) ClearPaidAt() *RechargeOrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetRefundedAt sets the "refunded_at" field.
func (_u *RechargeOrderUpdateOne) SetRefundedAt(v time.Time) *RechargeOrderUpdateOne {
	_u.mutation.SetRefundedAt(v)
	return _u
}

// SetNillableRefundedAt sets the "refunded_at" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableRefundedAt(v *time.Time) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetRefundedAt(*v)
	}
	return _u
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (_u *RechargeOrderUpdateOne) ClearRefundedAt() *RechargeOrderUpdateOne {
	_u.mutation.ClearRefundedAt()
	return _u
}

// SetCallbackIdempotencyKey sets the "callback_idempotency_key" field.
func (_u *RechargeOrderUpdateOne) SetCallbackIdempotencyKey(v string) *RechargeOrderUpdateOne {
	_u.mutation.SetCallbackIdempotencyKey(v)
	return _u
}

// SetNillableCallbackIdempotencyKey sets the "callback_idempotency_key" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableCallbackIdempotencyKey(v *string) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetCallbackIdempotencyKey(*v)
	}
	return _u
}

// SetCallbackRaw sets the "callback_raw" field.
func (_u *RechargeOrderUpdateOne) SetCallbackRaw(v string) *RechargeOrderUpdateOne {
	_u.mutation.SetCallbackRaw(v)
	return _u
}

// SetNillableCallbackRaw sets the "callback_raw" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableCallbackRaw(v *string) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetCallbackRaw(*v)
	}
	return _u
}

// ClearCallbackRaw clears the value of the "callback_raw" field.
func (_u *RechargeOrderUpdateOne) ClearCallbackRaw() *RechargeOrderUpdateOne {
	_u.mutation.ClearCallbackRaw()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *RechargeOrderUpdateOne) SetNotes(v string) *RechargeOrderUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableNotes(v *string) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *RechargeOrderUpdateOne) ClearNotes() *RechargeOrderUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RechargeOrderUpdateOne) SetUser(v *User) *RechargeOrderUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddReferralCommissionIDs adds the "referral_commissions" edge to the ReferralCommission entity by IDs.
func (_u *RechargeOrderUpdateOne) AddReferralCommissionIDs(ids ...int64) *RechargeOrderUpdateOne {
	_u.mutation.AddReferralCommissionIDs(ids...)
	return _u
}

// AddReferralCommissions adds the "referral_commissions" edges to the ReferralCommission entity.
func (_u *RechargeOrderUpdateOne) AddReferralCommissions(v ...*ReferralCommission) *RechargeOrderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReferralCommissionIDs(ids...)
}

// Mutation returns the RechargeOrderMutation object of the builder.
func (_u *RechargeOrderUpdateOne) Mutation() *RechargeOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RechargeOrderUpdateOne) ClearUser() *RechargeOrderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearReferralCommissions clears all "referral_commissions" edges to the ReferralCommission entity.
func (_u *RechargeOrderUpdateOne) ClearReferralCommissions() *RechargeOrderUpdateOne {
	_u.mutation.ClearReferralCommissions()
	return _u
}

// RemoveReferralCommissionIDs removes the "referral_commissions" edge to ReferralCommission entities by IDs.
func (_u *RechargeOrderUpdateOne) RemoveReferralCommissionIDs(ids ...int64) *RechargeOrderUpdateOne {
	_u.mutation.RemoveReferralCommissionIDs(ids...)
	return _u
}

// RemoveReferralCommissions removes "referral_commissions" edges to ReferralCommission entities.
func (_u *RechargeOrderUpdateOne) RemoveReferralCommissions(v ...*ReferralCommission) *RechargeOrderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReferralCommissionIDs(ids...)
}

// Where appends a list predicates to the RechargeOrderUpdate builder.
func (_u *RechargeOrderUpdateOne) Where(ps ...predicate.RechargeOrder) *RechargeOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RechargeOrderUpdateOne) Select(field string, fields ...string) *RechargeOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RechargeOrder entity.
func (_u *RechargeOrderUpdateOne) Save(ctx context.Context) (*RechargeOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RechargeOrderUpdateOne) SaveX(ctx context.Context) *RechargeOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RechargeOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RechargeOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RechargeOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rechargeorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RechargeOrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := rechargeorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalOrderID(); ok {
		if err := rechargeorder.ExternalOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "external_order_id", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.external_order_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Channel(); ok {
		if err := rechargeorder.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.channel": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := rechargeorder.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := rechargeorder.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rechargeorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CallbackIdempotencyKey(); ok {
		if err := rechargeorder.CallbackIdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "callback_idempotency_key", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.callback_idempotency_key": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RechargeOrder.user"`)
	}
	return nil
}

func (_u *RechargeOrderUpdateOne) sqlSave(ctx context.Context) (_node *RechargeOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rechargeorder.Table, rechargeorder.Columns, sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RechargeOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rechargeorder.FieldID)
		for _, f := range fields {
			if !rechargeorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rechargeorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargeorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(rechargeorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalOrderID(); ok {
		_spec.SetField(rechargeorder.FieldExternalOrderID, field.TypeString, value)
	}
	if _u.mutation.ExternalOrderIDCleared() {
		_spec.ClearField(rechargeorder.FieldExternalOrderID, field.TypeString)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(rechargeorder.FieldChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(rechargeorder.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(rechargeorder.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(rechargeorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(rechargeorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreditedAmount(); ok {
		_spec.SetField(rechargeorder.FieldCreditedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditedAmount(); ok {
		_spec.AddField(rechargeorder.FieldCreditedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rechargeorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(rechargeorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(rechargeorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RefundedAt(); ok {
		_spec.SetField(rechargeorder.FieldRefundedAt, field.TypeTime, value)
	}
	if _u.mutation.RefundedAtCleared() {
		_spec.ClearField(rechargeorder.FieldRefundedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CallbackIdempotencyKey(); ok {
		_spec.SetField(rechargeorder.FieldCallbackIdempotencyKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.CallbackRaw(); ok {
		_spec.SetField(rechargeorder.FieldCallbackRaw, field.TypeString, value)
	}
	if _u.mutation.CallbackRawCleared() {
		_spec.ClearField(rechargeorder.FieldCallbackRaw, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(rechargeorder.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(rechargeorder.FieldNotes, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rechargeorder.UserTable,
			Columns: []string{rechargeorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rechargeorder.UserTable,
			Columns: []string{rechargeorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReferralCommissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeorder.ReferralCommissionsTable,
			Columns: []string{rechargeorder.ReferralCommissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReferralCommissionsIDs(); len(nodes) > 0 && !_u.mutation.ReferralCommissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeorder.ReferralCommissionsTable,
			Columns: []string{rechargeorder.ReferralCommissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferralCommissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeorder.ReferralCommissionsTable,
			Columns: []string{rechargeorder.ReferralCommissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RechargeOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rechargeorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
