// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/rechargeorder"
	"github.com/Wei-Shaw/sub2api/ent/referralcommission"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RechargeOrderCreate is the builder for creating a RechargeOrder entity.
type RechargeOrderCreate struct {
	config
	mutation *RechargeOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *RechargeOrderCreate) SetCreatedAt(v time.Time) *RechargeOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableCreatedAt(v *time.Time) *RechargeOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RechargeOrderCreate) SetUpdatedAt(v time.Time) *RechargeOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableUpdatedAt(v *time.Time) *RechargeOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RechargeOrderCreate) SetUserID(v int64) *RechargeOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetOrderNo sets the "order_no" field.
func (_c *RechargeOrderCreate) SetOrderNo(v string) *RechargeOrderCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetExternalOrderID sets the "external_order_id" field.
func (_c *RechargeOrderCreate) SetExternalOrderID(v string) *RechargeOrderCreate {
	_c.mutation.SetExternalOrderID(v)
	return _c
}

// SetNillableExternalOrderID sets the "external_order_id" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableExternalOrderID(v *string) *RechargeOrderCreate {
	if v != nil {
		_c.SetExternalOrderID(*v)
	}
	return _c
}

// SetChannel sets the "channel" field.
func (_c *RechargeOrderCreate) SetChannel(v string) *RechargeOrderCreate {
	_c.mutation.SetChannel(v)
	return _c
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableChannel(v *string) *RechargeOrderCreate {
	if v != nil {
		_c.SetChannel(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *RechargeOrderCreate) SetSource(v string) *RechargeOrderCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableSource(v *string) *RechargeOrderCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *RechargeOrderCreate) SetCurrency(v string) *RechargeOrderCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableCurrency(v *string) *RechargeOrderCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *RechargeOrderCreate) SetAmount(v float64) *RechargeOrderCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableAmount(v *float64) *RechargeOrderCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetCreditedAmount sets the "credited_amount" field.
func (_c *RechargeOrderCreate) SetCreditedAmount(v float64) *RechargeOrderCreate {
	_c.mutation.SetCreditedAmount(v)
	return _c
}

// SetNillableCreditedAmount sets the "credited_amount" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableCreditedAmount(v *float64) *RechargeOrderCreate {
	if v != nil {
		_c.SetCreditedAmount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RechargeOrderCreate) SetStatus(v string) *RechargeOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableStatus(v *string) *RechargeOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *RechargeOrderCreate) SetPaidAt(v time.Time) *RechargeOrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillablePaidAt(v *time.Time) *RechargeOrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetRefundedAt sets the "refunded_at" field.
func (_c *RechargeOrderCreate) SetRefundedAt(v time.Time) *RechargeOrderCreate {
	_c.mutation.SetRefundedAt(v)
	return _c
}

// SetNillableRefundedAt sets the "refunded_at" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableRefundedAt(v *time.Time) *RechargeOrderCreate {
	if v != nil {
		_c.SetRefundedAt(*v)
	}
	return _c
}

// SetCallbackIdempotencyKey sets the "callback_idempotency_key" field.
func (_c *RechargeOrderCreate) SetCallbackIdempotencyKey(v string) *RechargeOrderCreate {
	_c.mutation.SetCallbackIdempotencyKey(v)
	return _c
}

// SetNillableCallbackIdempotencyKey sets the "callback_idempotency_key" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableCallbackIdempotencyKey(v *string) *RechargeOrderCreate {
	if v != nil {
		_c.SetCallbackIdempotencyKey(*v)
	}
	return _c
}

// SetCallbackRaw sets the "callback_raw" field.
func (_c *RechargeOrderCreate) SetCallbackRaw(v string) *RechargeOrderCreate {
	_c.mutation.SetCallbackRaw(v)
	return _c
}

// SetNillableCallbackRaw sets the "callback_raw" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableCallbackRaw(v *string) *RechargeOrderCreate {
	if v != nil {
		_c.SetCallbackRaw(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *RechargeOrderCreate) SetNotes(v string) *RechargeOrderCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableNotes(v *string) *RechargeOrderCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *RechargeOrderCreate) SetUser(v *User) *RechargeOrderCreate {
	return _c.SetUserID(v.ID)
}

// AddReferralCommissionIDs adds the "referral_commissions" edge to the ReferralCommission entity by IDs.
func (_c *RechargeOrderCreate) AddReferralCommissionIDs(ids ...int64) *RechargeOrderCreate {
	_c.mutation.AddReferralCommissionIDs(ids...)
	return _c
}

// AddReferralCommissions adds the "referral_commissions" edges to the ReferralCommission entity.
func (_c *RechargeOrderCreate) AddReferralCommissions(v ...*ReferralCommission) *RechargeOrderCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReferralCommissionIDs(ids...)
}

// Mutation returns the RechargeOrderMutation object of the builder.
func (_c *RechargeOrderCreate) Mutation() *RechargeOrderMutation {
	return _c.mutation
}

// Save creates the RechargeOrder in the database.
func (_c *RechargeOrderCreate) Save(ctx context.Context) (*RechargeOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RechargeOrderCreate) SaveX(ctx context.Context) *RechargeOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RechargeOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RechargeOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RechargeOrderCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := rechargeorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := rechargeorder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Channel(); !ok {
		v := rechargeorder.DefaultChannel
		_c.mutation.SetChannel(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := rechargeorder.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := rechargeorder.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := rechargeorder.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.CreditedAmount(); !ok {
		v := rechargeorder.DefaultCreditedAmount
		_c.mutation.SetCreditedAmount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := rechargeorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CallbackIdempotencyKey(); !ok {
		v := rechargeorder.DefaultCallbackIdempotencyKey
		_c.mutation.SetCallbackIdempotencyKey(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RechargeOrderCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RechargeOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RechargeOrder.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RechargeOrder.user_id"`)}
	}
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "RechargeOrder.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := rechargeorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ExternalOrderID(); ok {
		if err := rechargeorder.ExternalOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "external_order_id", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.external_order_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Channel(); !ok {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required field "RechargeOrder.channel"`)}
	}
	if v, ok := _c.mutation.Channel(); ok {
		if err := rechargeorder.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.channel": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "RechargeOrder.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := rechargeorder.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "RechargeOrder.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := rechargeorder.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "RechargeOrder.amount"`)}
	}
	if _, ok := _c.mutation.CreditedAmount(); !ok {
		return &ValidationError{Name: "credited_amount", err: errors.New(`ent: missing required field "RechargeOrder.credited_amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RechargeOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := rechargeorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CallbackIdempotencyKey(); !ok {
		return &ValidationError{Name: "callback_idempotency_key", err: errors.New(`ent: missing required field "RechargeOrder.callback_idempotency_key"`)}
	}
	if v, ok := _c.mutation.CallbackIdempotencyKey(); ok {
		if err := rechargeorder.CallbackIdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "callback_idempotency_key", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.callback_idempotency_key": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "RechargeOrder.user"`)}
	}
	return nil
}

func (_c *RechargeOrderCreate) sqlSave(ctx context.Context) (*RechargeOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RechargeOrderCreate) createSpec() (*RechargeOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &RechargeOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rechargeorder.Table, sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rechargeorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargeorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(rechargeorder.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.ExternalOrderID(); ok {
		_spec.SetField(rechargeorder.FieldExternalOrderID, field.TypeString, value)
		_node.ExternalOrderID = &value
	}
	if value, ok := _c.mutation.Channel(); ok {
		_spec.SetField(rechargeorder.FieldChannel, field.TypeString, value)
		_node.Channel = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(rechargeorder.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(rechargeorder.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(rechargeorder.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.CreditedAmount(); ok {
		_spec.SetField(rechargeorder.FieldCreditedAmount, field.TypeFloat64, value)
		_node.CreditedAmount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(rechargeorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(rechargeorder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.RefundedAt(); ok {
		_spec.SetField(rechargeorder.FieldRefundedAt, field.TypeTime, value)
		_node.RefundedAt = &value
	}
	if value, ok := _c.mutation.CallbackIdempotencyKey(); ok {
		_spec.SetField(rechargeorder.FieldCallbackIdempotencyKey, field.TypeString, value)
		_node.CallbackIdempotencyKey = value
	}
	if value, ok := _c.mutation.CallbackRaw(); ok {
		_spec.SetField(rechargeorder.FieldCallbackRaw, field.TypeString, value)
		_node.CallbackRaw = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(rechargeorder.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rechargeorder.UserTable,
			Columns: []string{rechargeorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReferralCommissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeorder.ReferralCommissionsTable,
			Columns: []string{rechargeorder.ReferralCommissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RechargeOrder.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RechargeOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RechargeOrderCreate) OnConflict(opts ...sql.ConflictOption) *RechargeOrderUpsertOne {
	_c.conflict = opts
	return &RechargeOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RechargeOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RechargeOrderCreate) OnConflictColumns(columns ...string) *RechargeOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RechargeOrderUpsertOne{
		create: _c,
	}
}

type (
	// RechargeOrderUpsertOne is the builder for "upsert"-ing
	//  one RechargeOrder node.
	RechargeOrderUpsertOne struct {
		create *RechargeOrderCreate
	}

	// RechargeOrderUpsert is the "OnConflict" setter.
	RechargeOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargeOrderUpsert) SetUpdatedAt(v time.Time) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateUpdatedAt() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *RechargeOrderUpsert) SetUserID(v int64) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateUserID() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldUserID)
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *RechargeOrderUpsert) SetOrderNo(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldOrderNo, v)
	return u
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateOrderNo() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldOrderNo)
	return u
}

// SetExternalOrderID sets the "external_order_id" field.
func (u *RechargeOrderUpsert) SetExternalOrderID(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldExternalOrderID, v)
	return u
}

// UpdateExternalOrderID sets the "external_order_id" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateExternalOrderID() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldExternalOrderID)
	return u
}

// ClearExternalOrderID clears the value of the "external_order_id" field.
func (u *RechargeOrderUpsert) ClearExternalOrderID() *RechargeOrderUpsert {
	u.SetNull(rechargeorder.FieldExternalOrderID)
	return u
}

// SetChannel sets the "channel" field.
func (u *RechargeOrderUpsert) SetChannel(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldChannel, v)
	return u
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateChannel() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldChannel)
	return u
}

// SetSource sets the "source" field.
func (u *RechargeOrderUpsert) SetSource(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateSource() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldSource)
	return u
}

// SetCurrency sets the "currency" field.
func (u *RechargeOrderUpsert) SetCurrency(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateCurrency() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldCurrency)
	return u
}

// SetAmount sets the "amount" field.
func (u *RechargeOrderUpsert) SetAmount(v float64) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateAmount() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *RechargeOrderUpsert) AddAmount(v float64) *RechargeOrderUpsert {
	u.Add(rechargeorder.FieldAmount, v)
	return u
}

// SetCreditedAmount sets the "credited_amount" field.
func (u *RechargeOrderUpsert) SetCreditedAmount(v float64) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldCreditedAmount, v)
	return u
}

// UpdateCreditedAmount sets the "credited_amount" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateCreditedAmount() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldCreditedAmount)
	return u
}

// AddCreditedAmount adds v to the "credited_amount" field.
func (u *RechargeOrderUpsert) AddCreditedAmount(v float64) *RechargeOrderUpsert {
	u.Add(rechargeorder.FieldCreditedAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *RechargeOrderUpsert) SetStatus(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateStatus() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldStatus)
	return u
}

// SetPaidAt sets the "paid_at" field.
func (u *RechargeOrderUpsert) SetPaidAt(v time.Time) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldPaidAt, v)
	return u
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdatePaidAt() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldPaidAt)
	return u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *RechargeOrderUpsert) ClearPaidAt() *RechargeOrderUpsert {
	u.SetNull(rechargeorder.FieldPaidAt)
	return u
}

// SetRefundedAt sets the "refunded_at" field.
func (u *RechargeOrderUpsert) SetRefundedAt(v time.Time) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldRefundedAt, v)
	return u
}

// UpdateRefundedAt sets the "refunded_at" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateRefundedAt() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldRefundedAt)
	return u
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (u *RechargeOrderUpsert) ClearRefundedAt() *RechargeOrderUpsert {
	u.SetNull(rechargeorder.FieldRefundedAt)
	return u
}

// SetCallbackIdempotencyKey sets the "callback_idempotency_key" field.
func (u *RechargeOrderUpsert) SetCallbackIdempotencyKey(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldCallbackIdempotencyKey, v)
	return u
}

// UpdateCallbackIdempotencyKey sets the "callback_idempotency_key" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateCallbackIdempotencyKey() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldCallbackIdempotencyKey)
	return u
}

// SetCallbackRaw sets the "callback_raw" field.
func (u *RechargeOrderUpsert) SetCallbackRaw(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldCallbackRaw, v)
	return u
}

// UpdateCallbackRaw sets the "callback_raw" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateCallbackRaw() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldCallbackRaw)
	return u
}

// ClearCallbackRaw clears the value of the "callback_raw" field.
func (u *RechargeOrderUpsert) ClearCallbackRaw() *RechargeOrderUpsert {
	u.SetNull(rechargeorder.FieldCallbackRaw)
	return u
}

// SetNotes sets the "notes" field.
func (u *RechargeOrderUpsert) SetNotes(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateNotes() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *RechargeOrderUpsert) ClearNotes() *RechargeOrderUpsert {
	u.SetNull(rechargeorder.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RechargeOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RechargeOrderUpsertOne) UpdateNewValues() *RechargeOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(rechargeorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RechargeOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RechargeOrderUpsertOne) Ignore() *RechargeOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RechargeOrderUpsertOne) DoNothing() *RechargeOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RechargeOrderCreate.OnConflict
// documentation for more info.
func (u *RechargeOrderUpsertOne) Update(set func(*RechargeOrderUpsert)) *RechargeOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RechargeOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargeOrderUpsertOne) SetUpdatedAt(v time.Time) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateUpdatedAt() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *RechargeOrderUpsertOne) SetUserID(v int64) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateUserID() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *RechargeOrderUpsertOne) SetOrderNo(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateOrderNo() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetExternalOrderID sets the "external_order_id" field.
func (u *RechargeOrderUpsertOne) SetExternalOrderID(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetExternalOrderID(v)
	})
}

// UpdateExternalOrderID sets the "external_order_id" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateExternalOrderID() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateExternalOrderID()
	})
}

// ClearExternalOrderID clears the value of the "external_order_id" field.
func (u *RechargeOrderUpsertOne) ClearExternalOrderID() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearExternalOrderID()
	})
}

// SetChannel sets the "channel" field.
func (u *RechargeOrderUpsertOne) SetChannel(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetChannel(v)
	})
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateChannel() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateChannel()
	})
}

// SetSource sets the "source" field.
func (u *RechargeOrderUpsertOne) SetSource(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateSource() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateSource()
	})
}

// SetCurrency sets the "currency" field.
func (u *RechargeOrderUpsertOne) SetCurrency(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateCurrency() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateCurrency()
	})
}

// SetAmount sets the "amount" field.
func (u *RechargeOrderUpsertOne) SetAmount(v float64) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *RechargeOrderUpsertOne) AddAmount(v float64) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateAmount() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetCreditedAmount sets the "credited_amount" field.
func (u *RechargeOrderUpsertOne) SetCreditedAmount(v float64) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetCreditedAmount(v)
	})
}

// AddCreditedAmount adds v to the "credited_amount" field.
func (u *RechargeOrderUpsertOne) AddCreditedAmount(v float64) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.AddCreditedAmount(v)
	})
}

// UpdateCreditedAmount sets the "credited_amount" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateCreditedAmount() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateCreditedAmount()
	})
}

// SetStatus sets the "status" field.
func (u *RechargeOrderUpsertOne) SetStatus(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateStatus() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *RechargeOrderUpsertOne) SetPaidAt(v time.Time) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdatePaidAt() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *RechargeOrderUpsertOne) ClearPaidAt() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetRefundedAt sets the "refunded_at" field.
func (u *RechargeOrderUpsertOne) SetRefundedAt(v time.Time) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetRefundedAt(v)
	})
}

// UpdateRefundedAt sets the "refunded_at" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateRefundedAt() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateRefundedAt()
	})
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (u *RechargeOrderUpsertOne) ClearRefundedAt() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearRefundedAt()
	})
}

// SetCallbackIdempotencyKey sets the "callback_idempotency_key" field.
func (u *RechargeOrderUpsertOne) SetCallbackIdempotencyKey(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetCallbackIdempotencyKey(v)
	})
}

// UpdateCallbackIdempotencyKey sets the "callback_idempotency_key" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateCallbackIdempotencyKey() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateCallbackIdempotencyKey()
	})
}

// SetCallbackRaw sets the "callback_raw" field.
func (u *RechargeOrderUpsertOne) SetCallbackRaw(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetCallbackRaw(v)
	})
}

// UpdateCallbackRaw sets the "callback_raw" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateCallbackRaw() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateCallbackRaw()
	})
}

// ClearCallbackRaw clears the value of the "callback_raw" field.
func (u *RechargeOrderUpsertOne) ClearCallbackRaw() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearCallbackRaw()
	})
}

// SetNotes sets the "notes" field.
func (u *RechargeOrderUpsertOne) SetNotes(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateNotes() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *RechargeOrderUpsertOne) ClearNotes() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *RechargeOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RechargeOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RechargeOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RechargeOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RechargeOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RechargeOrderCreateBulk is the builder for creating many RechargeOrder entities in bulk.
type RechargeOrderCreateBulk struct {
	config
	err      error
	builders []*RechargeOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the RechargeOrder entities in the database.
func (_c *RechargeOrderCreateBulk) Save(ctx context.Context) ([]*RechargeOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RechargeOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RechargeOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RechargeOrderCreateBulk) SaveX(ctx context.Context) []*RechargeOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RechargeOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RechargeOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RechargeOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RechargeOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RechargeOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *RechargeOrderUpsertBulk {
	_c.conflict = opts
	return &RechargeOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RechargeOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RechargeOrderCreateBulk) OnConflictColumns(columns ...string) *RechargeOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RechargeOrderUpsertBulk{
		create: _c,
	}
}

// RechargeOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of RechargeOrder nodes.
type RechargeOrderUpsertBulk struct {
	create *RechargeOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RechargeOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RechargeOrderUpsertBulk) UpdateNewValues() *RechargeOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(rechargeorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RechargeOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RechargeOrderUpsertBulk) Ignore() *RechargeOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RechargeOrderUpsertBulk) DoNothing() *RechargeOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RechargeOrderCreateBulk.OnConflict
// documentation for more info.
func (u *RechargeOrderUpsertBulk) Update(set func(*RechargeOrderUpsert)) *RechargeOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RechargeOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargeOrderUpsertBulk) SetUpdatedAt(v time.Time) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateUpdatedAt() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *RechargeOrderUpsertBulk) SetUserID(v int64) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateUserID() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *RechargeOrderUpsertBulk) SetOrderNo(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateOrderNo() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetExternalOrderID sets the "external_order_id" field.
func (u *RechargeOrderUpsertBulk) SetExternalOrderID(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetExternalOrderID(v)
	})
}

// UpdateExternalOrderID sets the "external_order_id" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateExternalOrderID() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateExternalOrderID()
	})
}

// ClearExternalOrderID clears the value of the "external_order_id" field.
func (u *RechargeOrderUpsertBulk) ClearExternalOrderID() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearExternalOrderID()
	})
}

// SetChannel sets the "channel" field.
func (u *RechargeOrderUpsertBulk) SetChannel(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetChannel(v)
	})
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateChannel() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateChannel()
	})
}

// SetSource sets the "source" field.
func (u *RechargeOrderUpsertBulk) SetSource(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateSource() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateSource()
	})
}

// SetCurrency sets the "currency" field.
func (u *RechargeOrderUpsertBulk) SetCurrency(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateCurrency() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateCurrency()
	})
}

// SetAmount sets the "amount" field.
func (u *RechargeOrderUpsertBulk) SetAmount(v float64) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *RechargeOrderUpsertBulk) AddAmount(v float64) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateAmount() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetCreditedAmount sets the "credited_amount" field.
func (u *RechargeOrderUpsertBulk) SetCreditedAmount(v float64) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetCreditedAmount(v)
	})
}

// AddCreditedAmount adds v to the "credited_amount" field.
func (u *RechargeOrderUpsertBulk) AddCreditedAmount(v float64) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.AddCreditedAmount(v)
	})
}

// UpdateCreditedAmount sets the "credited_amount" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateCreditedAmount() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateCreditedAmount()
	})
}

// SetStatus sets the "status" field.
func (u *RechargeOrderUpsertBulk) SetStatus(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateStatus() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *RechargeOrderUpsertBulk) SetPaidAt(v time.Time) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdatePaidAt() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *RechargeOrderUpsertBulk) ClearPaidAt() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetRefundedAt sets the "refunded_at" field.
func (u *RechargeOrderUpsertBulk) SetRefundedAt(v time.Time) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetRefundedAt(v)
	})
}

// UpdateRefundedAt sets the "refunded_at" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateRefundedAt() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateRefundedAt()
	})
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (u *RechargeOrderUpsertBulk) ClearRefundedAt() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearRefundedAt()
	})
}

// SetCallbackIdempotencyKey sets the "callback_idempotency_key" field.
func (u *RechargeOrderUpsertBulk) SetCallbackIdempotencyKey(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetCallbackIdempotencyKey(v)
	})
}

// UpdateCallbackIdempotencyKey sets the "callback_idempotency_key" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateCallbackIdempotencyKey() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateCallbackIdempotencyKey()
	})
}

// SetCallbackRaw sets the "callback_raw" field.
func (u *RechargeOrderUpsertBulk) SetCallbackRaw(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetCallbackRaw(v)
	})
}

// UpdateCallbackRaw sets the "callback_raw" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateCallbackRaw() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateCallbackRaw()
	})
}

// ClearCallbackRaw clears the value of the "callback_raw" field.
func (u *RechargeOrderUpsertBulk) ClearCallbackRaw() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearCallbackRaw()
	})
}

// SetNotes sets the "notes" field.
func (u *RechargeOrderUpsertBulk) SetNotes(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateNotes() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *RechargeOrderUpsertBulk) ClearNotes() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *RechargeOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RechargeOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RechargeOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RechargeOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
