// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/rechargeorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RechargeOrder is the model entity for the RechargeOrder schema.
type RechargeOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// OrderNo holds the value of the "order_no" field.
	OrderNo string `json:"order_no,omitempty"`
	// ExternalOrderID holds the value of the "external_order_id" field.
	ExternalOrderID *string `json:"external_order_id,omitempty"`
	// Channel holds the value of the "channel" field.
	Channel string `json:"channel,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// CreditedAmount holds the value of the "credited_amount" field.
	CreditedAmount float64 `json:"credited_amount,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// RefundedAt holds the value of the "refunded_at" field.
	RefundedAt *time.Time `json:"refunded_at,omitempty"`
	// CallbackIdempotencyKey holds the value of the "callback_idempotency_key" field.
	CallbackIdempotencyKey string `json:"callback_idempotency_key,omitempty"`
	// CallbackRaw holds the value of the "callback_raw" field.
	CallbackRaw *string `json:"callback_raw,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RechargeOrderQuery when eager-loading is set.
	Edges        RechargeOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RechargeOrderEdges holds the relations/edges for other nodes in the graph.
type RechargeOrderEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// ReferralCommissions holds the value of the referral_commissions edge.
	ReferralCommissions []*ReferralCommission `json:"referral_commissions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RechargeOrderEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ReferralCommissionsOrErr returns the ReferralCommissions value or an error if the edge
// was not loaded in eager-loading.
func (e RechargeOrderEdges) ReferralCommissionsOrErr() ([]*ReferralCommission, error) {
	if e.loadedTypes[1] {
		return e.ReferralCommissions, nil
	}
	return nil, &NotLoadedError{edge: "referral_commissions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RechargeOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rechargeorder.FieldAmount, rechargeorder.FieldCreditedAmount:
			values[i] = new(sql.NullFloat64)
		case rechargeorder.FieldID, rechargeorder.FieldUserID:
			values[i] = new(sql.NullInt64)
		case rechargeorder.FieldOrderNo, rechargeorder.FieldExternalOrderID, rechargeorder.FieldChannel, rechargeorder.FieldSource, rechargeorder.FieldCurrency, rechargeorder.FieldStatus, rechargeorder.FieldCallbackIdempotencyKey, rechargeorder.FieldCallbackRaw, rechargeorder.FieldNotes:
			values[i] = new(sql.NullString)
		case rechargeorder.FieldCreatedAt, rechargeorder.FieldUpdatedAt, rechargeorder.FieldPaidAt, rechargeorder.FieldRefundedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RechargeOrder fields.
func (_m *RechargeOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rechargeorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case rechargeorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case rechargeorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case rechargeorder.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case rechargeorder.FieldOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_no", values[i])
			} else if value.Valid {
				_m.OrderNo = value.String
			}
		case rechargeorder.FieldExternalOrderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_order_id", values[i])
			} else if value.Valid {
				_m.ExternalOrderID = new(string)
				*_m.ExternalOrderID = value.String
			}
		case rechargeorder.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				_m.Channel = value.String
			}
		case rechargeorder.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case rechargeorder.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case rechargeorder.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case rechargeorder.FieldCreditedAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field credited_amount", values[i])
			} else if value.Valid {
				_m.CreditedAmount = value.Float64
			}
		case rechargeorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case rechargeorder.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		case rechargeorder.FieldRefundedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field refunded_at", values[i])
			} else if value.Valid {
				_m.RefundedAt = new(time.Time)
				*_m.RefundedAt = value.Time
			}
		case rechargeorder.FieldCallbackIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field callback_idempotency_key", values[i])
			} else if value.Valid {
				_m.CallbackIdempotencyKey = value.String
			}
		case rechargeorder.FieldCallbackRaw:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field callback_raw", values[i])
			} else if value.Valid {
				_m.CallbackRaw = new(string)
				*_m.CallbackRaw = value.String
			}
		case rechargeorder.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RechargeOrder.
// This includes values selected through modifiers, order, etc.
func (_m *RechargeOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the RechargeOrder entity.
func (_m *RechargeOrder) QueryUser() *UserQuery {
	return NewRechargeOrderClient(_m.config).QueryUser(_m)
}

// QueryReferralCommissions queries the "referral_commissions" edge of the RechargeOrder entity.
func (_m *RechargeOrder) QueryReferralCommissions() *ReferralCommissionQuery {
	return NewRechargeOrderClient(_m.config).QueryReferralCommissions(_m)
}

// Update returns a builder for updating this RechargeOrder.
// Note that you need to call RechargeOrder.Unwrap() before calling this method if this RechargeOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RechargeOrder) Update() *RechargeOrderUpdateOne {
	return NewRechargeOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RechargeOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RechargeOrder) Unwrap() *RechargeOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RechargeOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RechargeOrder) String() string {
	var builder strings.Builder
	builder.WriteString("RechargeOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("order_no=")
	builder.WriteString(_m.OrderNo)
	builder.WriteString(", ")
	if v := _m.ExternalOrderID; v != nil {
		builder.WriteString("external_order_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("channel=")
	builder.WriteString(_m.Channel)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("credited_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditedAmount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RefundedAt; v != nil {
		builder.WriteString("refunded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("callback_idempotency_key=")
	builder.WriteString(_m.CallbackIdempotencyKey)
	builder.WriteString(", ")
	if v := _m.CallbackRaw; v != nil {
		builder.WriteString("callback_raw=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// RechargeOrders is a parsable slice of RechargeOrder.
type RechargeOrders []*RechargeOrder
