// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/referralwithdrawalrequest"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ReferralWithdrawalRequest is the model entity for the ReferralWithdrawalRequest schema.
type ReferralWithdrawalRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PromoterUserID holds the value of the "promoter_user_id" field.
	PromoterUserID int64 `json:"promoter_user_id,omitempty"`
	// ReviewerUserID holds the value of the "reviewer_user_id" field.
	ReviewerUserID *int64 `json:"reviewer_user_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// PaymentMethod holds the value of the "payment_method" field.
	PaymentMethod string `json:"payment_method,omitempty"`
	// AccountName holds the value of the "account_name" field.
	AccountName *string `json:"account_name,omitempty"`
	// AccountIdentifier holds the value of the "account_identifier" field.
	AccountIdentifier *string `json:"account_identifier,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ReviewedAt holds the value of the "reviewed_at" field.
	ReviewedAt *time.Time `json:"reviewed_at,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// ReviewNotes holds the value of the "review_notes" field.
	ReviewNotes *string `json:"review_notes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReferralWithdrawalRequestQuery when eager-loading is set.
	Edges        ReferralWithdrawalRequestEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReferralWithdrawalRequestEdges holds the relations/edges for other nodes in the graph.
type ReferralWithdrawalRequestEdges struct {
	// Promoter holds the value of the promoter edge.
	Promoter *User `json:"promoter,omitempty"`
	// Reviewer holds the value of the reviewer edge.
	Reviewer *User `json:"reviewer,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PromoterOrErr returns the Promoter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReferralWithdrawalRequestEdges) PromoterOrErr() (*User, error) {
	if e.Promoter != nil {
		return e.Promoter, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "promoter"}
}

// ReviewerOrErr returns the Reviewer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReferralWithdrawalRequestEdges) ReviewerOrErr() (*User, error) {
	if e.Reviewer != nil {
		return e.Reviewer, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "reviewer"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReferralWithdrawalRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case referralwithdrawalrequest.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case referralwithdrawalrequest.FieldID, referralwithdrawalrequest.FieldPromoterUserID, referralwithdrawalrequest.FieldReviewerUserID:
			values[i] = new(sql.NullInt64)
		case referralwithdrawalrequest.FieldCurrency, referralwithdrawalrequest.FieldPaymentMethod, referralwithdrawalrequest.FieldAccountName, referralwithdrawalrequest.FieldAccountIdentifier, referralwithdrawalrequest.FieldStatus, referralwithdrawalrequest.FieldNotes, referralwithdrawalrequest.FieldReviewNotes:
			values[i] = new(sql.NullString)
		case referralwithdrawalrequest.FieldCreatedAt, referralwithdrawalrequest.FieldUpdatedAt, referralwithdrawalrequest.FieldReviewedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReferralWithdrawalRequest fields.
func (_m *ReferralWithdrawalRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case referralwithdrawalrequest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case referralwithdrawalrequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case referralwithdrawalrequest.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case referralwithdrawalrequest.FieldPromoterUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field promoter_user_id", values[i])
			} else if value.Valid {
				_m.PromoterUserID = value.Int64
			}
		case referralwithdrawalrequest.FieldReviewerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reviewer_user_id", values[i])
			} else if value.Valid {
				_m.ReviewerUserID = new(int64)
				*_m.ReviewerUserID = value.Int64
			}
		case referralwithdrawalrequest.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case referralwithdrawalrequest.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case referralwithdrawalrequest.FieldPaymentMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_method", values[i])
			} else if value.Valid {
				_m.PaymentMethod = value.String
			}
		case referralwithdrawalrequest.FieldAccountName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_name", values[i])
			} else if value.Valid {
				_m.AccountName = new(string)
				*_m.AccountName = value.String
			}
		case referralwithdrawalrequest.FieldAccountIdentifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_identifier", values[i])
			} else if value.Valid {
				_m.AccountIdentifier = new(string)
				*_m.AccountIdentifier = value.String
			}
		case referralwithdrawalrequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case referralwithdrawalrequest.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				_m.ReviewedAt = new(time.Time)
				*_m.ReviewedAt = value.Time
			}
		case referralwithdrawalrequest.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case referralwithdrawalrequest.FieldReviewNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_notes", values[i])
			} else if value.Valid {
				_m.ReviewNotes = new(string)
				*_m.ReviewNotes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReferralWithdrawalRequest.
// This includes values selected through modifiers, order, etc.
func (_m *ReferralWithdrawalRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPromoter queries the "promoter" edge of the ReferralWithdrawalRequest entity.
func (_m *ReferralWithdrawalRequest) QueryPromoter() *UserQuery {
	return NewReferralWithdrawalRequestClient(_m.config).QueryPromoter(_m)
}

// QueryReviewer queries the "reviewer" edge of the ReferralWithdrawalRequest entity.
func (_m *ReferralWithdrawalRequest) QueryReviewer() *UserQuery {
	return NewReferralWithdrawalRequestClient(_m.config).QueryReviewer(_m)
}

// Update returns a builder for updating this ReferralWithdrawalRequest.
// Note that you need to call ReferralWithdrawalRequest.Unwrap() before calling this method if this ReferralWithdrawalRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReferralWithdrawalRequest) Update() *ReferralWithdrawalRequestUpdateOne {
	return NewReferralWithdrawalRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReferralWithdrawalRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReferralWithdrawalRequest) Unwrap() *ReferralWithdrawalRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReferralWithdrawalRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReferralWithdrawalRequest) String() string {
	var builder strings.Builder
	builder.WriteString("ReferralWithdrawalRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("promoter_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PromoterUserID))
	builder.WriteString(", ")
	if v := _m.ReviewerUserID; v != nil {
		builder.WriteString("reviewer_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("payment_method=")
	builder.WriteString(_m.PaymentMethod)
	builder.WriteString(", ")
	if v := _m.AccountName; v != nil {
		builder.WriteString("account_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AccountIdentifier; v != nil {
		builder.WriteString("account_identifier=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.ReviewedAt; v != nil {
		builder.WriteString("reviewed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ReviewNotes; v != nil {
		builder.WriteString("review_notes=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// ReferralWithdrawalRequests is a parsable slice of ReferralWithdrawalRequest.
type ReferralWithdrawalRequests []*ReferralWithdrawalRequest
