// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rechargeorder"
	"github.com/Wei-Shaw/sub2api/ent/referralcommission"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ReferralCommissionUpdate is the builder for updating ReferralCommission entities.
type ReferralCommissionUpdate struct {
	config
	hooks    []Hook
	mutation *ReferralCommissionMutation
}

// Where appends a list predicates to the ReferralCommissionUpdate builder.
func (_u *ReferralCommissionUpdate) Where(ps ...predicate.ReferralCommission) *ReferralCommissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReferralCommissionUpdate) SetUpdatedAt(v time.Time) *ReferralCommissionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPromoterUserID sets the "promoter_user_id" field.
func (_u *ReferralCommissionUpdate) SetPromoterUserID(v int64) *ReferralCommissionUpdate {
	_u.mutation.SetPromoterUserID(v)
	return _u
}

// SetNillablePromoterUserID sets the "promoter_user_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillablePromoterUserID(v *int64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetPromoterUserID(*v)
	}
	return _u
}

// SetReferredUserID sets the "referred_user_id" field.
func (_u *ReferralCommissionUpdate) SetReferredUserID(v int64) *ReferralCommissionUpdate {
	_u.mutation.SetReferredUserID(v)
	return _u
}

// SetNillableReferredUserID sets the "referred_user_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableReferredUserID(v *int64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetReferredUserID(*v)
	}
	return _u
}

// SetRechargeOrderID sets the "recharge_order_id" field.
func (_u *ReferralCommissionUpdate) SetRechargeOrderID(v int64) *ReferralCommissionUpdate {
	_u.mutation.SetRechargeOrderID(v)
	return _u
}

// SetNillableRechargeOrderID sets the "recharge_order_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableRechargeOrderID(v *int64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetRechargeOrderID(*v)
	}
	return _u
}

// SetCommissionType sets the "commission_type" field.
func (_u *ReferralCommissionUpdate) SetCommissionType(v string) *ReferralCommissionUpdate {
	_u.mutation.SetCommissionType(v)
	return _u
}

// SetNillableCommissionType sets the "commission_type" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableCommissionType(v *string) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetCommissionType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReferralCommissionUpdate) SetStatus(v string) *ReferralCommissionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableStatus(v *string) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSourceAmount sets the "source_amount" field.
func (_u *ReferralCommissionUpdate) SetSourceAmount(v float64) *ReferralCommissionUpdate {
	_u.mutation.ResetSourceAmount()
	_u.mutation.SetSourceAmount(v)
	return _u
}

// SetNillableSourceAmount sets the "source_amount" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableSourceAmount(v *float64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetSourceAmount(*v)
	}
	return _u
}

// AddSourceAmount adds value to the "source_amount" field.
func (_u *ReferralCommissionUpdate) AddSourceAmount(v float64) *ReferralCommissionUpdate {
	_u.mutation.AddSourceAmount(v)
	return _u
}

// SetRateSnapshot sets the "rate_snapshot" field.
func (_u *ReferralCommissionUpdate) SetRateSnapshot(v float64) *ReferralCommissionUpdate {
	_u.mutation.ResetRateSnapshot()
	_u.mutation.SetRateSnapshot(v)
	return _u
}

// SetNillableRateSnapshot sets the "rate_snapshot" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableRateSnapshot(v *float64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetRateSnapshot(*v)
	}
	return _u
}

// AddRateSnapshot adds value to the "rate_snapshot" field.
func (_u *ReferralCommissionUpdate) AddRateSnapshot(v float64) *ReferralCommissionUpdate {
	_u.mutation.AddRateSnapshot(v)
	return _u
}

// SetCommissionAmount sets the "commission_amount" field.
func (_u *ReferralCommissionUpdate) SetCommissionAmount(v float64) *ReferralCommissionUpdate {
	_u.mutation.ResetCommissionAmount()
	_u.mutation.SetCommissionAmount(v)
	return _u
}

// SetNillableCommissionAmount sets the "commission_amount" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableCommissionAmount(v *float64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetCommissionAmount(*v)
	}
	return _u
}

// AddCommissionAmount adds value to the "commission_amount" field.
func (_u *ReferralCommissionUpdate) AddCommissionAmount(v float64) *ReferralCommissionUpdate {
	_u.mutation.AddCommissionAmount(v)
	return _u
}

// SetReversedAt sets the "reversed_at" field.
func (_u *ReferralCommissionUpdate) SetReversedAt(v time.Time) *ReferralCommissionUpdate {
	_u.mutation.SetReversedAt(v)
	return _u
}

// SetNillableReversedAt sets the "reversed_at" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableReversedAt(v *time.Time) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetReversedAt(*v)
	}
	return _u
}

// ClearReversedAt clears the value of the "reversed_at" field.
func (_u *ReferralCommissionUpdate) ClearReversedAt() *ReferralCommissionUpdate {
	_u.mutation.ClearReversedAt()
	return _u
}

// SetReversedReason sets the "reversed_reason" field.
func (_u *ReferralCommissionUpdate) SetReversedReason(v string) *ReferralCommissionUpdate {
	_u.mutation.SetReversedReason(v)
	return _u
}

// SetNillableReversedReason sets the "reversed_reason" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableReversedReason(v *string) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetReversedReason(*v)
	}
	return _u
}

// ClearReversedReason clears the value of the "reversed_reason" field.
func (_u *ReferralCommissionUpdate) ClearReversedReason() *ReferralCommissionUpdate {
	_u.mutation.ClearReversedReason()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ReferralCommissionUpdate) SetNotes(v string) *ReferralCommissionUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableNotes(v *string) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *ReferralCommissionUpdate) ClearNotes() *ReferralCommissionUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetPromoterID sets the "promoter" edge to the User entity by ID.
func (_u *ReferralCommissionUpdate) SetPromoterID(id int64) *ReferralCommissionUpdate {
	_u.mutation.SetPromoterID(id)
	return _u
}

// SetPromoter sets the "promoter" edge to the User entity.
func (_u *ReferralCommissionUpdate) SetPromoter(v *User) *ReferralCommissionUpdate {
	return _u.SetPromoterID(v.ID)
}

// SetReferredUser sets the "referred_user" edge to the User entity.
func (_u *ReferralCommissionUpdate) SetReferredUser(v *User) *ReferralCommissionUpdate {
	return _u.SetReferredUserID(v.ID)
}

// SetRechargeOrder sets the "recharge_order" edge to the RechargeOrder entity.
func (_u *ReferralCommissionUpdate) SetRechargeOrder(v *RechargeOrder) *ReferralCommissionUpdate {
	return _u.SetRechargeOrderID(v.ID)
}

// Mutation returns the ReferralCommissionMutation object of the builder.
func (_u *ReferralCommissionUpdate) Mutation() *ReferralCommissionMutation {
	return _u.mutation
}

// ClearPromoter clears the "promoter" edge to the User entity.
func (_u *ReferralCommissionUpdate) ClearPromoter() *ReferralCommissionUpdate {
	_u.mutation.ClearPromoter()
	return _u
}

// ClearReferredUser clears the "referred_user" edge to the User entity.
func (_u *ReferralCommissionUpdate) ClearReferredUser() *ReferralCommissionUpdate {
	_u.mutation.ClearReferredUser()
	return _u
}

// ClearRechargeOrder clears the "recharge_order" edge to the RechargeOrder entity.
func (_u *ReferralCommissionUpdate) ClearRechargeOrder() *ReferralCommissionUpdate {
	_u.mutation.ClearRechargeOrder()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReferralCommissionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralCommissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReferralCommissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralCommissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReferralCommissionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := referralcommission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReferralCommissionUpdate) check() error {
	if v, ok := _u.mutation.CommissionType(); ok {
		if err := referralcommission.CommissionTypeValidator(v); err != nil {
			return &ValidationError{Name: "commission_type", err: fmt.Errorf(`ent: validator failed for field "ReferralCommission.commission_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := referralcommission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReferralCommission.status": %w`, err)}
		}
	}
	if _u.mutation.PromoterCleared() && len(_u.mutation.PromoterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralCommission.promoter"`)
	}
	if _u.mutation.ReferredUserCleared() && len(_u.mutation.ReferredUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralCommission.referred_user"`)
	}
	if _u.mutation.RechargeOrderCleared() && len(_u.mutation.RechargeOrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralCommission.recharge_order"`)
	}
	return nil
}

func (_u *ReferralCommissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(referralcommission.Table, referralcommission.Columns, sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(referralcommission.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CommissionType(); ok {
		_spec.SetField(referralcommission.FieldCommissionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(referralcommission.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceAmount(); ok {
		_spec.SetField(referralcommission.FieldSourceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSourceAmount(); ok {
		_spec.AddField(referralcommission.FieldSourceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RateSnapshot(); ok {
		_spec.SetField(referralcommission.FieldRateSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateSnapshot(); ok {
		_spec.AddField(referralcommission.FieldRateSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CommissionAmount(); ok {
		_spec.SetField(referralcommission.FieldCommissionAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionAmount(); ok {
		_spec.AddField(referralcommission.FieldCommissionAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ReversedAt(); ok {
		_spec.SetField(referralcommission.FieldReversedAt, field.TypeTime, value)
	}
	if _u.mutation.ReversedAtCleared() {
		_spec.ClearField(referralcommission.FieldReversedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReversedReason(); ok {
		_spec.SetField(referralcommission.FieldReversedReason, field.TypeString, value)
	}
	if _u.mutation.ReversedReasonCleared() {
		_spec.ClearField(referralcommission.FieldReversedReason, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(referralcommission.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(referralcommission.FieldNotes, field.TypeString)
	}
	if _u.mutation.PromoterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.PromoterTable,
			Columns: []string{referralcommission.PromoterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PromoterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.PromoterTable,
			Columns: []string{referralcommission.PromoterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReferredUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.ReferredUserTable,
			Columns: []string{referralcommission.ReferredUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferredUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.ReferredUserTable,
			Columns: []string{referralcommission.ReferredUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RechargeOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.RechargeOrderTable,
			Columns: []string{referralcommission.RechargeOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RechargeOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.RechargeOrderTable,
			Columns: []string{referralcommission.RechargeOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralcommission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReferralCommissionUpdateOne is the builder for updating a single ReferralCommission entity.
type ReferralCommissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReferralCommissionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReferralCommissionUpdateOne) SetUpdatedAt(v time.Time) *ReferralCommissionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPromoterUserID sets the "promoter_user_id" field.
func (_u *ReferralCommissionUpdateOne) SetPromoterUserID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.SetPromoterUserID(v)
	return _u
}

// SetNillablePromoterUserID sets the "promoter_user_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillablePromoterUserID(v *int64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetPromoterUserID(*v)
	}
	return _u
}

// SetReferredUserID sets the "referred_user_id" field.
func (_u *ReferralCommissionUpdateOne) SetReferredUserID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.SetReferredUserID(v)
	return _u
}

// SetNillableReferredUserID sets the "referred_user_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableReferredUserID(v *int64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetReferredUserID(*v)
	}
	return _u
}

// SetRechargeOrderID sets the "recharge_order_id" field.
func (_u *ReferralCommissionUpdateOne) SetRechargeOrderID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.SetRechargeOrderID(v)
	return _u
}

// SetNillableRechargeOrderID sets the "recharge_order_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableRechargeOrderID(v *int64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetRechargeOrderID(*v)
	}
	return _u
}

// SetCommissionType sets the "commission_type" field.
func (_u *ReferralCommissionUpdateOne) SetCommissionType(v string) *ReferralCommissionUpdateOne {
	_u.mutation.SetCommissionType(v)
	return _u
}

// SetNillableCommissionType sets the "commission_type" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableCommissionType(v *string) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetCommissionType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReferralCommissionUpdateOne) SetStatus(v string) *ReferralCommissionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableStatus(v *string) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSourceAmount sets the "source_amount" field.
func (_u *ReferralCommissionUpdateOne) SetSourceAmount(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetSourceAmount()
	_u.mutation.SetSourceAmount(v)
	return _u
}

// SetNillableSourceAmount sets the "source_amount" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableSourceAmount(v *float64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetSourceAmount(*v)
	}
	return _u
}

// AddSourceAmount adds value to the "source_amount" field.
func (_u *ReferralCommissionUpdateOne) AddSourceAmount(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.AddSourceAmount(v)
	return _u
}

// SetRateSnapshot sets the "rate_snapshot" field.
func (_u *ReferralCommissionUpdateOne) SetRateSnapshot(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetRateSnapshot()
	_u.mutation.SetRateSnapshot(v)
	return _u
}

// SetNillableRateSnapshot sets the "rate_snapshot" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableRateSnapshot(v *float64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetRateSnapshot(*v)
	}
	return _u
}

// AddRateSnapshot adds value to the "rate_snapshot" field.
func (_u *ReferralCommissionUpdateOne) AddRateSnapshot(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.AddRateSnapshot(v)
	return _u
}

// SetCommissionAmount sets the "commission_amount" field.
func (_u *ReferralCommissionUpdateOne) SetCommissionAmount(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetCommissionAmount()
	_u.mutation.SetCommissionAmount(v)
	return _u
}

// SetNillableCommissionAmount sets the "commission_amount" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableCommissionAmount(v *float64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetCommissionAmount(*v)
	}
	return _u
}

// AddCommissionAmount adds value to the "commission_amount" field.
func (_u *ReferralCommissionUpdateOne) AddCommissionAmount(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.AddCommissionAmount(v)
	return _u
}

// SetReversedAt sets the "reversed_at" field.
func (_u *ReferralCommissionUpdateOne) SetReversedAt(v time.Time) *ReferralCommissionUpdateOne {
	_u.mutation.SetReversedAt(v)
	return _u
}

// SetNillableReversedAt sets the "reversed_at" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableReversedAt(v *time.Time) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetReversedAt(*v)
	}
	return _u
}

// ClearReversedAt clears the value of the "reversed_at" field.
func (_u *ReferralCommissionUpdateOne) ClearReversedAt() *ReferralCommissionUpdateOne {
	_u.mutation.ClearReversedAt()
	return _u
}

// SetReversedReason sets the "reversed_reason" field.
func (_u *ReferralCommissionUpdateOne) SetReversedReason(v string) *ReferralCommissionUpdateOne {
	_u.mutation.SetReversedReason(v)
	return _u
}

// SetNillableReversedReason sets the "reversed_reason" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableReversedReason(v *string) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetReversedReason(*v)
	}
	return _u
}

// ClearReversedReason clears the value of the "reversed_reason" field.
func (_u *ReferralCommissionUpdateOne) ClearReversedReason() *ReferralCommissionUpdateOne {
	_u.mutation.ClearReversedReason()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ReferralCommissionUpdateOne) SetNotes(v string) *ReferralCommissionUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableNotes(v *string) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *ReferralCommissionUpdateOne) ClearNotes() *ReferralCommissionUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetPromoterID sets the "promoter" edge to the User entity by ID.
func (_u *ReferralCommissionUpdateOne) SetPromoterID(id int64) *ReferralCommissionUpdateOne {
	_u.mutation.SetPromoterID(id)
	return _u
}

// SetPromoter sets the "promoter" edge to the User entity.
func (_u *ReferralCommissionUpdateOne) SetPromoter(v *User) *ReferralCommissionUpdateOne {
	return _u.SetPromoterID(v.ID)
}

// SetReferredUser sets the "referred_user" edge to the User entity.
func (_u *ReferralCommissionUpdateOne) SetReferredUser(v *User) *ReferralCommissionUpdateOne {
	return _u.SetReferredUserID(v.ID)
}

// SetRechargeOrder sets the "recharge_order" edge to the RechargeOrder entity.
func (_u *ReferralCommissionUpdateOne) SetRechargeOrder(v *RechargeOrder) *ReferralCommissionUpdateOne {
	return _u.SetRechargeOrderID(v.ID)
}

// Mutation returns the ReferralCommissionMutation object of the builder.
func (_u *ReferralCommissionUpdateOne) Mutation() *ReferralCommissionMutation {
	return _u.mutation
}

// ClearPromoter clears the "promoter" edge to the User entity.
func (_u *ReferralCommissionUpdateOne) ClearPromoter() *ReferralCommissionUpdateOne {
	_u.mutation.ClearPromoter()
	return _u
}

// ClearReferredUser clears the "referred_user" edge to the User entity.
func (_u *ReferralCommissionUpdateOne) ClearReferredUser() *ReferralCommissionUpdateOne {
	_u.mutation.ClearReferredUser()
	return _u
}

// ClearRechargeOrder clears the "recharge_order" edge to the RechargeOrder entity.
func (_u *ReferralCommissionUpdateOne) ClearRechargeOrder() *ReferralCommissionUpdateOne {
	_u.mutation.ClearRechargeOrder()
	return _u
}

// Where appends a list predicates to the ReferralCommissionUpdate builder.
func (_u *ReferralCommissionUpdateOne) Where(ps ...predicate.ReferralCommission) *ReferralCommissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReferralCommissionUpdateOne) Select(field string, fields ...string) *ReferralCommissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReferralCommission entity.
func (_u *ReferralCommissionUpdateOne) Save(ctx context.Context) (*ReferralCommission, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralCommissionUpdateOne) SaveX(ctx context.Context) *ReferralCommission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReferralCommissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralCommissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReferralCommissionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := referralcommission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReferralCommissionUpdateOne) check() error {
	if v, ok := _u.mutation.CommissionType(); ok {
		if err := referralcommission.CommissionTypeValidator(v); err != nil {
			return &ValidationError{Name: "commission_type", err: fmt.Errorf(`ent: validator failed for field "ReferralCommission.commission_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := referralcommission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReferralCommission.status": %w`, err)}
		}
	}
	if _u.mutation.PromoterCleared() && len(_u.mutation.PromoterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralCommission.promoter"`)
	}
	if _u.mutation.ReferredUserCleared() && len(_u.mutation.ReferredUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralCommission.referred_user"`)
	}
	if _u.mutation.RechargeOrderCleared() && len(_u.mutation.RechargeOrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralCommission.recharge_order"`)
	}
	return nil
}

func (_u *ReferralCommissionUpdateOne) sqlSave(ctx context.Context) (_node *ReferralCommission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(referralcommission.Table, referralcommission.Columns, sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReferralCommission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, referralcommission.FieldID)
		for _, f := range fields {
			if !referralcommission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != referralcommission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(referralcommission.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CommissionType(); ok {
		_spec.SetField(referralcommission.FieldCommissionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(referralcommission.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceAmount(); ok {
		_spec.SetField(referralcommission.FieldSourceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSourceAmount(); ok {
		_spec.AddField(referralcommission.FieldSourceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RateSnapshot(); ok {
		_spec.SetField(referralcommission.FieldRateSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateSnapshot(); ok {
		_spec.AddField(referralcommission.FieldRateSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CommissionAmount(); ok {
		_spec.SetField(referralcommission.FieldCommissionAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionAmount(); ok {
		_spec.AddField(referralcommission.FieldCommissionAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ReversedAt(); ok {
		_spec.SetField(referralcommission.FieldReversedAt, field.TypeTime, value)
	}
	if _u.mutation.ReversedAtCleared() {
		_spec.ClearField(referralcommission.FieldReversedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReversedReason(); ok {
		_spec.SetField(referralcommission.FieldReversedReason, field.TypeString, value)
	}
	if _u.mutation.ReversedReasonCleared() {
		_spec.ClearField(referralcommission.FieldReversedReason, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(referralcommission.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(referralcommission.FieldNotes, field.TypeString)
	}
	if _u.mutation.PromoterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.PromoterTable,
			Columns: []string{referralcommission.PromoterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PromoterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.PromoterTable,
			Columns: []string{referralcommission.PromoterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReferredUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.ReferredUserTable,
			Columns: []string{referralcommission.ReferredUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferredUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.ReferredUserTable,
			Columns: []string{referralcommission.ReferredUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RechargeOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.RechargeOrderTable,
			Columns: []string{referralcommission.RechargeOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RechargeOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.RechargeOrderTable,
			Columns: []string{referralcommission.RechargeOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ReferralCommission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralcommission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
