// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/referralcommission"
	"github.com/Wei-Shaw/sub2api/ent/referralwithdrawalallocation"
	"github.com/Wei-Shaw/sub2api/ent/referralwithdrawalrequest"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ReferralWithdrawalAllocation is the model entity for the ReferralWithdrawalAllocation schema.
type ReferralWithdrawalAllocation struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PromoterUserID holds the value of the "promoter_user_id" field.
	PromoterUserID int64 `json:"promoter_user_id,omitempty"`
	// WithdrawalRequestID holds the value of the "withdrawal_request_id" field.
	WithdrawalRequestID int64 `json:"withdrawal_request_id,omitempty"`
	// CommissionID holds the value of the "commission_id" field.
	CommissionID int64 `json:"commission_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReferralWithdrawalAllocationQuery when eager-loading is set.
	Edges        ReferralWithdrawalAllocationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReferralWithdrawalAllocationEdges holds the relations/edges for other nodes in the graph.
type ReferralWithdrawalAllocationEdges struct {
	// Promoter holds the value of the promoter edge.
	Promoter *User `json:"promoter,omitempty"`
	// WithdrawalRequest holds the value of the withdrawal_request edge.
	WithdrawalRequest *ReferralWithdrawalRequest `json:"withdrawal_request,omitempty"`
	// Commission holds the value of the commission edge.
	Commission *ReferralCommission `json:"commission,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// PromoterOrErr returns the Promoter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReferralWithdrawalAllocationEdges) PromoterOrErr() (*User, error) {
	if e.Promoter != nil {
		return e.Promoter, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "promoter"}
}

// WithdrawalRequestOrErr returns the WithdrawalRequest value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReferralWithdrawalAllocationEdges) WithdrawalRequestOrErr() (*ReferralWithdrawalRequest, error) {
	if e.WithdrawalRequest != nil {
		return e.WithdrawalRequest, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: referralwithdrawalrequest.Label}
	}
	return nil, &NotLoadedError{edge: "withdrawal_request"}
}

// CommissionOrErr returns the Commission value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReferralWithdrawalAllocationEdges) CommissionOrErr() (*ReferralCommission, error) {
	if e.Commission != nil {
		return e.Commission, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: referralcommission.Label}
	}
	return nil, &NotLoadedError{edge: "commission"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReferralWithdrawalAllocation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case referralwithdrawalallocation.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case referralwithdrawalallocation.FieldID, referralwithdrawalallocation.FieldPromoterUserID, referralwithdrawalallocation.FieldWithdrawalRequestID, referralwithdrawalallocation.FieldCommissionID:
			values[i] = new(sql.NullInt64)
		case referralwithdrawalallocation.FieldCreatedAt, referralwithdrawalallocation.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReferralWithdrawalAllocation fields.
func (_m *ReferralWithdrawalAllocation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case referralwithdrawalallocation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case referralwithdrawalallocation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case referralwithdrawalallocation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case referralwithdrawalallocation.FieldPromoterUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field promoter_user_id", values[i])
			} else if value.Valid {
				_m.PromoterUserID = value.Int64
			}
		case referralwithdrawalallocation.FieldWithdrawalRequestID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field withdrawal_request_id", values[i])
			} else if value.Valid {
				_m.WithdrawalRequestID = value.Int64
			}
		case referralwithdrawalallocation.FieldCommissionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field commission_id", values[i])
			} else if value.Valid {
				_m.CommissionID = value.Int64
			}
		case referralwithdrawalallocation.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReferralWithdrawalAllocation.
// This includes values selected through modifiers, order, etc.
func (_m *ReferralWithdrawalAllocation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPromoter queries the "promoter" edge of the ReferralWithdrawalAllocation entity.
func (_m *ReferralWithdrawalAllocation) QueryPromoter() *UserQuery {
	return NewReferralWithdrawalAllocationClient(_m.config).QueryPromoter(_m)
}

// QueryWithdrawalRequest queries the "withdrawal_request" edge of the ReferralWithdrawalAllocation entity.
func (_m *ReferralWithdrawalAllocation) QueryWithdrawalRequest() *ReferralWithdrawalRequestQuery {
	return NewReferralWithdrawalAllocationClient(_m.config).QueryWithdrawalRequest(_m)
}

// QueryCommission queries the "commission" edge of the ReferralWithdrawalAllocation entity.
func (_m *ReferralWithdrawalAllocation) QueryCommission() *ReferralCommissionQuery {
	return NewReferralWithdrawalAllocationClient(_m.config).QueryCommission(_m)
}

// Update returns a builder for updating this ReferralWithdrawalAllocation.
// Note that you need to call ReferralWithdrawalAllocation.Unwrap() before calling this method if this ReferralWithdrawalAllocation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReferralWithdrawalAllocation) Update() *ReferralWithdrawalAllocationUpdateOne {
	return NewReferralWithdrawalAllocationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReferralWithdrawalAllocation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReferralWithdrawalAllocation) Unwrap() *ReferralWithdrawalAllocation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReferralWithdrawalAllocation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReferralWithdrawalAllocation) String() string {
	var builder strings.Builder
	builder.WriteString("ReferralWithdrawalAllocation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("promoter_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PromoterUserID))
	builder.WriteString(", ")
	builder.WriteString("withdrawal_request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WithdrawalRequestID))
	builder.WriteString(", ")
	builder.WriteString("commission_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CommissionID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteByte(')')
	return builder.String()
}

// ReferralWithdrawalAllocations is a parsable slice of ReferralWithdrawalAllocation.
type ReferralWithdrawalAllocations []*ReferralWithdrawalAllocation
