// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/referralcommission"
	"github.com/Wei-Shaw/sub2api/ent/referralwithdrawalallocation"
	"github.com/Wei-Shaw/sub2api/ent/referralwithdrawalrequest"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ReferralWithdrawalAllocationCreate is the builder for creating a ReferralWithdrawalAllocation entity.
type ReferralWithdrawalAllocationCreate struct {
	config
	mutation *ReferralWithdrawalAllocationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReferralWithdrawalAllocationCreate) SetCreatedAt(v time.Time) *ReferralWithdrawalAllocationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReferralWithdrawalAllocationCreate) SetNillableCreatedAt(v *time.Time) *ReferralWithdrawalAllocationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ReferralWithdrawalAllocationCreate) SetUpdatedAt(v time.Time) *ReferralWithdrawalAllocationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ReferralWithdrawalAllocationCreate) SetNillableUpdatedAt(v *time.Time) *ReferralWithdrawalAllocationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPromoterUserID sets the "promoter_user_id" field.
func (_c *ReferralWithdrawalAllocationCreate) SetPromoterUserID(v int64) *ReferralWithdrawalAllocationCreate {
	_c.mutation.SetPromoterUserID(v)
	return _c
}

// SetWithdrawalRequestID sets the "withdrawal_request_id" field.
func (_c *ReferralWithdrawalAllocationCreate) SetWithdrawalRequestID(v int64) *ReferralWithdrawalAllocationCreate {
	_c.mutation.SetWithdrawalRequestID(v)
	return _c
}

// SetCommissionID sets the "commission_id" field.
func (_c *ReferralWithdrawalAllocationCreate) SetCommissionID(v int64) *ReferralWithdrawalAllocationCreate {
	_c.mutation.SetCommissionID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *ReferralWithdrawalAllocationCreate) SetAmount(v float64) *ReferralWithdrawalAllocationCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *ReferralWithdrawalAllocationCreate) SetNillableAmount(v *float64) *ReferralWithdrawalAllocationCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetPromoterID sets the "promoter" edge to the User entity by ID.
func (_c *ReferralWithdrawalAllocationCreate) SetPromoterID(id int64) *ReferralWithdrawalAllocationCreate {
	_c.mutation.SetPromoterID(id)
	return _c
}

// SetPromoter sets the "promoter" edge to the User entity.
func (_c *ReferralWithdrawalAllocationCreate) SetPromoter(v *User) *ReferralWithdrawalAllocationCreate {
	return _c.SetPromoterID(v.ID)
}

// SetWithdrawalRequest sets the "withdrawal_request" edge to the ReferralWithdrawalRequest entity.
func (_c *ReferralWithdrawalAllocationCreate) SetWithdrawalRequest(v *ReferralWithdrawalRequest) *ReferralWithdrawalAllocationCreate {
	return _c.SetWithdrawalRequestID(v.ID)
}

// SetCommission sets the "commission" edge to the ReferralCommission entity.
func (_c *ReferralWithdrawalAllocationCreate) SetCommission(v *ReferralCommission) *ReferralWithdrawalAllocationCreate {
	return _c.SetCommissionID(v.ID)
}

// Mutation returns the ReferralWithdrawalAllocationMutation object of the builder.
func (_c *ReferralWithdrawalAllocationCreate) Mutation() *ReferralWithdrawalAllocationMutation {
	return _c.mutation
}

// Save creates the ReferralWithdrawalAllocation in the database.
func (_c *ReferralWithdrawalAllocationCreate) Save(ctx context.Context) (*ReferralWithdrawalAllocation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReferralWithdrawalAllocationCreate) SaveX(ctx context.Context) *ReferralWithdrawalAllocation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralWithdrawalAllocationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralWithdrawalAllocationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReferralWithdrawalAllocationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := referralwithdrawalallocation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := referralwithdrawalallocation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := referralwithdrawalallocation.DefaultAmount
		_c.mutation.SetAmount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReferralWithdrawalAllocationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReferralWithdrawalAllocation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ReferralWithdrawalAllocation.updated_at"`)}
	}
	if _, ok := _c.mutation.PromoterUserID(); !ok {
		return &ValidationError{Name: "promoter_user_id", err: errors.New(`ent: missing required field "ReferralWithdrawalAllocation.promoter_user_id"`)}
	}
	if _, ok := _c.mutation.WithdrawalRequestID(); !ok {
		return &ValidationError{Name: "withdrawal_request_id", err: errors.New(`ent: missing required field "ReferralWithdrawalAllocation.withdrawal_request_id"`)}
	}
	if _, ok := _c.mutation.CommissionID(); !ok {
		return &ValidationError{Name: "commission_id", err: errors.New(`ent: missing required field "ReferralWithdrawalAllocation.commission_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "ReferralWithdrawalAllocation.amount"`)}
	}
	if len(_c.mutation.PromoterIDs()) == 0 {
		return &ValidationError{Name: "promoter", err: errors.New(`ent: missing required edge "ReferralWithdrawalAllocation.promoter"`)}
	}
	if len(_c.mutation.WithdrawalRequestIDs()) == 0 {
		return &ValidationError{Name: "withdrawal_request", err: errors.New(`ent: missing required edge "ReferralWithdrawalAllocation.withdrawal_request"`)}
	}
	if len(_c.mutation.CommissionIDs()) == 0 {
		return &ValidationError{Name: "commission", err: errors.New(`ent: missing required edge "ReferralWithdrawalAllocation.commission"`)}
	}
	return nil
}

func (_c *ReferralWithdrawalAllocationCreate) sqlSave(ctx context.Context) (*ReferralWithdrawalAllocation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReferralWithdrawalAllocationCreate) createSpec() (*ReferralWithdrawalAllocation, *sqlgraph.CreateSpec) {
	var (
		_node = &ReferralWithdrawalAllocation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(referralwithdrawalallocation.Table, sqlgraph.NewFieldSpec(referralwithdrawalallocation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(referralwithdrawalallocation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(referralwithdrawalallocation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(referralwithdrawalallocation.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if nodes := _c.mutation.PromoterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralwithdrawalallocation.PromoterTable,
			Columns: []string{referralwithdrawalallocation.PromoterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PromoterUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WithdrawalRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralwithdrawalallocation.WithdrawalRequestTable,
			Columns: []string{referralwithdrawalallocation.WithdrawalRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referralwithdrawalrequest.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WithdrawalRequestID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CommissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralwithdrawalallocation.CommissionTable,
			Columns: []string{referralwithdrawalallocation.CommissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CommissionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralWithdrawalAllocation.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralWithdrawalAllocationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralWithdrawalAllocationCreate) OnConflict(opts ...sql.ConflictOption) *ReferralWithdrawalAllocationUpsertOne {
	_c.conflict = opts
	return &ReferralWithdrawalAllocationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralWithdrawalAllocation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralWithdrawalAllocationCreate) OnConflictColumns(columns ...string) *ReferralWithdrawalAllocationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralWithdrawalAllocationUpsertOne{
		create: _c,
	}
}

type (
	// ReferralWithdrawalAllocationUpsertOne is the builder for "upsert"-ing
	//  one ReferralWithdrawalAllocation node.
	ReferralWithdrawalAllocationUpsertOne struct {
		create *ReferralWithdrawalAllocationCreate
	}

	// ReferralWithdrawalAllocationUpsert is the "OnConflict" setter.
	ReferralWithdrawalAllocationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ReferralWithdrawalAllocationUpsert) SetUpdatedAt(v time.Time) *ReferralWithdrawalAllocationUpsert {
	u.Set(referralwithdrawalallocation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReferralWithdrawalAllocationUpsert) UpdateUpdatedAt() *ReferralWithdrawalAllocationUpsert {
	u.SetExcluded(referralwithdrawalallocation.FieldUpdatedAt)
	return u
}

// SetPromoterUserID sets the "promoter_user_id" field.
func (u *ReferralWithdrawalAllocationUpsert) SetPromoterUserID(v int64) *ReferralWithdrawalAllocationUpsert {
	u.Set(referralwithdrawalallocation.FieldPromoterUserID, v)
	return u
}

// UpdatePromoterUserID sets the "promoter_user_id" field to the value that was provided on create.
func (u *ReferralWithdrawalAllocationUpsert) UpdatePromoterUserID() *ReferralWithdrawalAllocationUpsert {
	u.SetExcluded(referralwithdrawalallocation.FieldPromoterUserID)
	return u
}

// SetWithdrawalRequestID sets the "withdrawal_request_id" field.
func (u *ReferralWithdrawalAllocationUpsert) SetWithdrawalRequestID(v int64) *ReferralWithdrawalAllocationUpsert {
	u.Set(referralwithdrawalallocation.FieldWithdrawalRequestID, v)
	return u
}

// UpdateWithdrawalRequestID sets the "withdrawal_request_id" field to the value that was provided on create.
func (u *ReferralWithdrawalAllocationUpsert) UpdateWithdrawalRequestID() *ReferralWithdrawalAllocationUpsert {
	u.SetExcluded(referralwithdrawalallocation.FieldWithdrawalRequestID)
	return u
}

// SetCommissionID sets the "commission_id" field.
func (u *ReferralWithdrawalAllocationUpsert) SetCommissionID(v int64) *ReferralWithdrawalAllocationUpsert {
	u.Set(referralwithdrawalallocation.FieldCommissionID, v)
	return u
}

// UpdateCommissionID sets the "commission_id" field to the value that was provided on create.
func (u *ReferralWithdrawalAllocationUpsert) UpdateCommissionID() *ReferralWithdrawalAllocationUpsert {
	u.SetExcluded(referralwithdrawalallocation.FieldCommissionID)
	return u
}

// SetAmount sets the "amount" field.
func (u *ReferralWithdrawalAllocationUpsert) SetAmount(v float64) *ReferralWithdrawalAllocationUpsert {
	u.Set(referralwithdrawalallocation.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ReferralWithdrawalAllocationUpsert) UpdateAmount() *ReferralWithdrawalAllocationUpsert {
	u.SetExcluded(referralwithdrawalallocation.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *ReferralWithdrawalAllocationUpsert) AddAmount(v float64) *ReferralWithdrawalAllocationUpsert {
	u.Add(referralwithdrawalallocation.FieldAmount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ReferralWithdrawalAllocation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralWithdrawalAllocationUpsertOne) UpdateNewValues() *ReferralWithdrawalAllocationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(referralwithdrawalallocation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralWithdrawalAllocation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReferralWithdrawalAllocationUpsertOne) Ignore() *ReferralWithdrawalAllocationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralWithdrawalAllocationUpsertOne) DoNothing() *ReferralWithdrawalAllocationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralWithdrawalAllocationCreate.OnConflict
// documentation for more info.
func (u *ReferralWithdrawalAllocationUpsertOne) Update(set func(*ReferralWithdrawalAllocationUpsert)) *ReferralWithdrawalAllocationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralWithdrawalAllocationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReferralWithdrawalAllocationUpsertOne) SetUpdatedAt(v time.Time) *ReferralWithdrawalAllocationUpsertOne {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReferralWithdrawalAllocationUpsertOne) UpdateUpdatedAt() *ReferralWithdrawalAllocationUpsertOne {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPromoterUserID sets the "promoter_user_id" field.
func (u *ReferralWithdrawalAllocationUpsertOne) SetPromoterUserID(v int64) *ReferralWithdrawalAllocationUpsertOne {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.SetPromoterUserID(v)
	})
}

// UpdatePromoterUserID sets the "promoter_user_id" field to the value that was provided on create.
func (u *ReferralWithdrawalAllocationUpsertOne) UpdatePromoterUserID() *ReferralWithdrawalAllocationUpsertOne {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.UpdatePromoterUserID()
	})
}

// SetWithdrawalRequestID sets the "withdrawal_request_id" field.
func (u *ReferralWithdrawalAllocationUpsertOne) SetWithdrawalRequestID(v int64) *ReferralWithdrawalAllocationUpsertOne {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.SetWithdrawalRequestID(v)
	})
}

// UpdateWithdrawalRequestID sets the "withdrawal_request_id" field to the value that was provided on create.
func (u *ReferralWithdrawalAllocationUpsertOne) UpdateWithdrawalRequestID() *ReferralWithdrawalAllocationUpsertOne {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.UpdateWithdrawalRequestID()
	})
}

// SetCommissionID sets the "commission_id" field.
func (u *ReferralWithdrawalAllocationUpsertOne) SetCommissionID(v int64) *ReferralWithdrawalAllocationUpsertOne {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.SetCommissionID(v)
	})
}

// UpdateCommissionID sets the "commission_id" field to the value that was provided on create.
func (u *ReferralWithdrawalAllocationUpsertOne) UpdateCommissionID() *ReferralWithdrawalAllocationUpsertOne {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.UpdateCommissionID()
	})
}

// SetAmount sets the "amount" field.
func (u *ReferralWithdrawalAllocationUpsertOne) SetAmount(v float64) *ReferralWithdrawalAllocationUpsertOne {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ReferralWithdrawalAllocationUpsertOne) AddAmount(v float64) *ReferralWithdrawalAllocationUpsertOne {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ReferralWithdrawalAllocationUpsertOne) UpdateAmount() *ReferralWithdrawalAllocationUpsertOne {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.UpdateAmount()
	})
}

// Exec executes the query.
func (u *ReferralWithdrawalAllocationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralWithdrawalAllocationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralWithdrawalAllocationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReferralWithdrawalAllocationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReferralWithdrawalAllocationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReferralWithdrawalAllocationCreateBulk is the builder for creating many ReferralWithdrawalAllocation entities in bulk.
type ReferralWithdrawalAllocationCreateBulk struct {
	config
	err      error
	builders []*ReferralWithdrawalAllocationCreate
	conflict []sql.ConflictOption
}

// Save creates the ReferralWithdrawalAllocation entities in the database.
func (_c *ReferralWithdrawalAllocationCreateBulk) Save(ctx context.Context) ([]*ReferralWithdrawalAllocation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReferralWithdrawalAllocation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReferralWithdrawalAllocationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReferralWithdrawalAllocationCreateBulk) SaveX(ctx context.Context) []*ReferralWithdrawalAllocation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralWithdrawalAllocationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralWithdrawalAllocationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralWithdrawalAllocation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralWithdrawalAllocationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralWithdrawalAllocationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReferralWithdrawalAllocationUpsertBulk {
	_c.conflict = opts
	return &ReferralWithdrawalAllocationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralWithdrawalAllocation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralWithdrawalAllocationCreateBulk) OnConflictColumns(columns ...string) *ReferralWithdrawalAllocationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralWithdrawalAllocationUpsertBulk{
		create: _c,
	}
}

// ReferralWithdrawalAllocationUpsertBulk is the builder for "upsert"-ing
// a bulk of ReferralWithdrawalAllocation nodes.
type ReferralWithdrawalAllocationUpsertBulk struct {
	create *ReferralWithdrawalAllocationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ReferralWithdrawalAllocation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralWithdrawalAllocationUpsertBulk) UpdateNewValues() *ReferralWithdrawalAllocationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(referralwithdrawalallocation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralWithdrawalAllocation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReferralWithdrawalAllocationUpsertBulk) Ignore() *ReferralWithdrawalAllocationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralWithdrawalAllocationUpsertBulk) DoNothing() *ReferralWithdrawalAllocationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralWithdrawalAllocationCreateBulk.OnConflict
// documentation for more info.
func (u *ReferralWithdrawalAllocationUpsertBulk) Update(set func(*ReferralWithdrawalAllocationUpsert)) *ReferralWithdrawalAllocationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralWithdrawalAllocationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReferralWithdrawalAllocationUpsertBulk) SetUpdatedAt(v time.Time) *ReferralWithdrawalAllocationUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReferralWithdrawalAllocationUpsertBulk) UpdateUpdatedAt() *ReferralWithdrawalAllocationUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPromoterUserID sets the "promoter_user_id" field.
func (u *ReferralWithdrawalAllocationUpsertBulk) SetPromoterUserID(v int64) *ReferralWithdrawalAllocationUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.SetPromoterUserID(v)
	})
}

// UpdatePromoterUserID sets the "promoter_user_id" field to the value that was provided on create.
func (u *ReferralWithdrawalAllocationUpsertBulk) UpdatePromoterUserID() *ReferralWithdrawalAllocationUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.UpdatePromoterUserID()
	})
}

// SetWithdrawalRequestID sets the "withdrawal_request_id" field.
func (u *ReferralWithdrawalAllocationUpsertBulk) SetWithdrawalRequestID(v int64) *ReferralWithdrawalAllocationUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.SetWithdrawalRequestID(v)
	})
}

// UpdateWithdrawalRequestID sets the "withdrawal_request_id" field to the value that was provided on create.
func (u *ReferralWithdrawalAllocationUpsertBulk) UpdateWithdrawalRequestID() *ReferralWithdrawalAllocationUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.UpdateWithdrawalRequestID()
	})
}

// SetCommissionID sets the "commission_id" field.
func (u *ReferralWithdrawalAllocationUpsertBulk) SetCommissionID(v int64) *ReferralWithdrawalAllocationUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.SetCommissionID(v)
	})
}

// UpdateCommissionID sets the "commission_id" field to the value that was provided on create.
func (u *ReferralWithdrawalAllocationUpsertBulk) UpdateCommissionID() *ReferralWithdrawalAllocationUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.UpdateCommissionID()
	})
}

// SetAmount sets the "amount" field.
func (u *ReferralWithdrawalAllocationUpsertBulk) SetAmount(v float64) *ReferralWithdrawalAllocationUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ReferralWithdrawalAllocationUpsertBulk) AddAmount(v float64) *ReferralWithdrawalAllocationUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ReferralWithdrawalAllocationUpsertBulk) UpdateAmount() *ReferralWithdrawalAllocationUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalAllocationUpsert) {
		s.UpdateAmount()
	})
}

// Exec executes the query.
func (u *ReferralWithdrawalAllocationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReferralWithdrawalAllocationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralWithdrawalAllocationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralWithdrawalAllocationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
