// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/referralcommission"
	"github.com/Wei-Shaw/sub2api/ent/referralwithdrawalallocation"
	"github.com/Wei-Shaw/sub2api/ent/referralwithdrawalrequest"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ReferralWithdrawalAllocationUpdate is the builder for updating ReferralWithdrawalAllocation entities.
type ReferralWithdrawalAllocationUpdate struct {
	config
	hooks    []Hook
	mutation *ReferralWithdrawalAllocationMutation
}

// Where appends a list predicates to the ReferralWithdrawalAllocationUpdate builder.
func (_u *ReferralWithdrawalAllocationUpdate) Where(ps ...predicate.ReferralWithdrawalAllocation) *ReferralWithdrawalAllocationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReferralWithdrawalAllocationUpdate) SetUpdatedAt(v time.Time) *ReferralWithdrawalAllocationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPromoterUserID sets the "promoter_user_id" field.
func (_u *ReferralWithdrawalAllocationUpdate) SetPromoterUserID(v int64) *ReferralWithdrawalAllocationUpdate {
	_u.mutation.SetPromoterUserID(v)
	return _u
}

// SetNillablePromoterUserID sets the "promoter_user_id" field if the given value is not nil.
func (_u *ReferralWithdrawalAllocationUpdate) SetNillablePromoterUserID(v *int64) *ReferralWithdrawalAllocationUpdate {
	if v != nil {
		_u.SetPromoterUserID(*v)
	}
	return _u
}

// SetWithdrawalRequestID sets the "withdrawal_request_id" field.
func (_u *ReferralWithdrawalAllocationUpdate) SetWithdrawalRequestID(v int64) *ReferralWithdrawalAllocationUpdate {
	_u.mutation.SetWithdrawalRequestID(v)
	return _u
}

// SetNillableWithdrawalRequestID sets the "withdrawal_request_id" field if the given value is not nil.
func (_u *ReferralWithdrawalAllocationUpdate) SetNillableWithdrawalRequestID(v *int64) *ReferralWithdrawalAllocationUpdate {
	if v != nil {
		_u.SetWithdrawalRequestID(*v)
	}
	return _u
}

// SetCommissionID sets the "commission_id" field.
func (_u *ReferralWithdrawalAllocationUpdate) SetCommissionID(v int64) *ReferralWithdrawalAllocationUpdate {
	_u.mutation.SetCommissionID(v)
	return _u
}

// SetNillableCommissionID sets the "commission_id" field if the given value is not nil.
func (_u *ReferralWithdrawalAllocationUpdate) SetNillableCommissionID(v *int64) *ReferralWithdrawalAllocationUpdate {
	if v != nil {
		_u.SetCommissionID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ReferralWithdrawalAllocationUpdate) SetAmount(v float64) *ReferralWithdrawalAllocationUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ReferralWithdrawalAllocationUpdate) SetNillableAmount(v *float64) *ReferralWithdrawalAllocationUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ReferralWithdrawalAllocationUpdate) AddAmount(v float64) *ReferralWithdrawalAllocationUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetPromoterID sets the "promoter" edge to the User entity by ID.
func (_u *ReferralWithdrawalAllocationUpdate) SetPromoterID(id int64) *ReferralWithdrawalAllocationUpdate {
	_u.mutation.SetPromoterID(id)
	return _u
}

// SetPromoter sets the "promoter" edge to the User entity.
func (_u *ReferralWithdrawalAllocationUpdate) SetPromoter(v *User) *ReferralWithdrawalAllocationUpdate {
	return _u.SetPromoterID(v.ID)
}

// SetWithdrawalRequest sets the "withdrawal_request" edge to the ReferralWithdrawalRequest entity.
func (_u *ReferralWithdrawalAllocationUpdate) SetWithdrawalRequest(v *ReferralWithdrawalRequest) *ReferralWithdrawalAllocationUpdate {
	return _u.SetWithdrawalRequestID(v.ID)
}

// SetCommission sets the "commission" edge to the ReferralCommission entity.
func (_u *ReferralWithdrawalAllocationUpdate) SetCommission(v *ReferralCommission) *ReferralWithdrawalAllocationUpdate {
	return _u.SetCommissionID(v.ID)
}

// Mutation returns the ReferralWithdrawalAllocationMutation object of the builder.
func (_u *ReferralWithdrawalAllocationUpdate) Mutation() *ReferralWithdrawalAllocationMutation {
	return _u.mutation
}

// ClearPromoter clears the "promoter" edge to the User entity.
func (_u *ReferralWithdrawalAllocationUpdate) ClearPromoter() *ReferralWithdrawalAllocationUpdate {
	_u.mutation.ClearPromoter()
	return _u
}

// ClearWithdrawalRequest clears the "withdrawal_request" edge to the ReferralWithdrawalRequest entity.
func (_u *ReferralWithdrawalAllocationUpdate) ClearWithdrawalRequest() *ReferralWithdrawalAllocationUpdate {
	_u.mutation.ClearWithdrawalRequest()
	return _u
}

// ClearCommission clears the "commission" edge to the ReferralCommission entity.
func (_u *ReferralWithdrawalAllocationUpdate) ClearCommission() *ReferralWithdrawalAllocationUpdate {
	_u.mutation.ClearCommission()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReferralWithdrawalAllocationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralWithdrawalAllocationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReferralWithdrawalAllocationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralWithdrawalAllocationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReferralWithdrawalAllocationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := referralwithdrawalallocation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReferralWithdrawalAllocationUpdate) check() error {
	if _u.mutation.PromoterCleared() && len(_u.mutation.PromoterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralWithdrawalAllocation.promoter"`)
	}
	if _u.mutation.WithdrawalRequestCleared() && len(_u.mutation.WithdrawalRequestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralWithdrawalAllocation.withdrawal_request"`)
	}
	if _u.mutation.CommissionCleared() && len(_u.mutation.CommissionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralWithdrawalAllocation.commission"`)
	}
	return nil
}

func (_u *ReferralWithdrawalAllocationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(referralwithdrawalallocation.Table, referralwithdrawalallocation.Columns, sqlgraph.NewFieldSpec(referralwithdrawalallocation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(referralwithdrawalallocation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(referralwithdrawalallocation.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(referralwithdrawalallocation.FieldAmount, field.TypeFloat64, value)
	}
	if _u.mutation.PromoterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralwithdrawalallocation.PromoterTable,
			Columns: []string{referralwithdrawalallocation.PromoterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PromoterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralwithdrawalallocation.PromoterTable,
			Columns: []string{referralwithdrawalallocation.PromoterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WithdrawalRequestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralwithdrawalallocation.WithdrawalRequestTable,
			Columns: []string{referralwithdrawalallocation.WithdrawalRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referralwithdrawalrequest.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WithdrawalRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralwithdrawalallocation.WithdrawalRequestTable,
			Columns: []string{referralwithdrawalallocation.WithdrawalRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referralwithdrawalrequest.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralwithdrawalallocation.CommissionTable,
			Columns: []string{referralwithdrawalallocation.CommissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralwithdrawalallocation.CommissionTable,
			Columns: []string{referralwithdrawalallocation.CommissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralwithdrawalallocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReferralWithdrawalAllocationUpdateOne is the builder for updating a single ReferralWithdrawalAllocation entity.
type ReferralWithdrawalAllocationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReferralWithdrawalAllocationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReferralWithdrawalAllocationUpdateOne) SetUpdatedAt(v time.Time) *ReferralWithdrawalAllocationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPromoterUserID sets the "promoter_user_id" field.
func (_u *ReferralWithdrawalAllocationUpdateOne) SetPromoterUserID(v int64) *ReferralWithdrawalAllocationUpdateOne {
	_u.mutation.SetPromoterUserID(v)
	return _u
}

// SetNillablePromoterUserID sets the "promoter_user_id" field if the given value is not nil.
func (_u *ReferralWithdrawalAllocationUpdateOne) SetNillablePromoterUserID(v *int64) *ReferralWithdrawalAllocationUpdateOne {
	if v != nil {
		_u.SetPromoterUserID(*v)
	}
	return _u
}

// SetWithdrawalRequestID sets the "withdrawal_request_id" field.
func (_u *ReferralWithdrawalAllocationUpdateOne) SetWithdrawalRequestID(v int64) *ReferralWithdrawalAllocationUpdateOne {
	_u.mutation.SetWithdrawalRequestID(v)
	return _u
}

// SetNillableWithdrawalRequestID sets the "withdrawal_request_id" field if the given value is not nil.
func (_u *ReferralWithdrawalAllocationUpdateOne) SetNillableWithdrawalRequestID(v *int64) *ReferralWithdrawalAllocationUpdateOne {
	if v != nil {
		_u.SetWithdrawalRequestID(*v)
	}
	return _u
}

// SetCommissionID sets the "commission_id" field.
func (_u *ReferralWithdrawalAllocationUpdateOne) SetCommissionID(v int64) *ReferralWithdrawalAllocationUpdateOne {
	_u.mutation.SetCommissionID(v)
	return _u
}

// SetNillableCommissionID sets the "commission_id" field if the given value is not nil.
func (_u *ReferralWithdrawalAllocationUpdateOne) SetNillableCommissionID(v *int64) *ReferralWithdrawalAllocationUpdateOne {
	if v != nil {
		_u.SetCommissionID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ReferralWithdrawalAllocationUpdateOne) SetAmount(v float64) *ReferralWithdrawalAllocationUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ReferralWithdrawalAllocationUpdateOne) SetNillableAmount(v *float64) *ReferralWithdrawalAllocationUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ReferralWithdrawalAllocationUpdateOne) AddAmount(v float64) *ReferralWithdrawalAllocationUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetPromoterID sets the "promoter" edge to the User entity by ID.
func (_u *ReferralWithdrawalAllocationUpdateOne) SetPromoterID(id int64) *ReferralWithdrawalAllocationUpdateOne {
	_u.mutation.SetPromoterID(id)
	return _u
}

// SetPromoter sets the "promoter" edge to the User entity.
func (_u *ReferralWithdrawalAllocationUpdateOne) SetPromoter(v *User) *ReferralWithdrawalAllocationUpdateOne {
	return _u.SetPromoterID(v.ID)
}

// SetWithdrawalRequest sets the "withdrawal_request" edge to the ReferralWithdrawalRequest entity.
func (_u *ReferralWithdrawalAllocationUpdateOne) SetWithdrawalRequest(v *ReferralWithdrawalRequest) *ReferralWithdrawalAllocationUpdateOne {
	return _u.SetWithdrawalRequestID(v.ID)
}

// SetCommission sets the "commission" edge to the ReferralCommission entity.
func (_u *ReferralWithdrawalAllocationUpdateOne) SetCommission(v *ReferralCommission) *ReferralWithdrawalAllocationUpdateOne {
	return _u.SetCommissionID(v.ID)
}

// Mutation returns the ReferralWithdrawalAllocationMutation object of the builder.
func (_u *ReferralWithdrawalAllocationUpdateOne) Mutation() *ReferralWithdrawalAllocationMutation {
	return _u.mutation
}

// ClearPromoter clears the "promoter" edge to the User entity.
func (_u *ReferralWithdrawalAllocationUpdateOne) ClearPromoter() *ReferralWithdrawalAllocationUpdateOne {
	_u.mutation.ClearPromoter()
	return _u
}

// ClearWithdrawalRequest clears the "withdrawal_request" edge to the ReferralWithdrawalRequest entity.
func (_u *ReferralWithdrawalAllocationUpdateOne) ClearWithdrawalRequest() *ReferralWithdrawalAllocationUpdateOne {
	_u.mutation.ClearWithdrawalRequest()
	return _u
}

// ClearCommission clears the "commission" edge to the ReferralCommission entity.
func (_u *ReferralWithdrawalAllocationUpdateOne) ClearCommission() *ReferralWithdrawalAllocationUpdateOne {
	_u.mutation.ClearCommission()
	return _u
}

// Where appends a list predicates to the ReferralWithdrawalAllocationUpdate builder.
func (_u *ReferralWithdrawalAllocationUpdateOne) Where(ps ...predicate.ReferralWithdrawalAllocation) *ReferralWithdrawalAllocationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReferralWithdrawalAllocationUpdateOne) Select(field string, fields ...string) *ReferralWithdrawalAllocationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReferralWithdrawalAllocation entity.
func (_u *ReferralWithdrawalAllocationUpdateOne) Save(ctx context.Context) (*ReferralWithdrawalAllocation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralWithdrawalAllocationUpdateOne) SaveX(ctx context.Context) *ReferralWithdrawalAllocation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReferralWithdrawalAllocationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralWithdrawalAllocationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReferralWithdrawalAllocationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := referralwithdrawalallocation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReferralWithdrawalAllocationUpdateOne) check() error {
	if _u.mutation.PromoterCleared() && len(_u.mutation.PromoterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralWithdrawalAllocation.promoter"`)
	}
	if _u.mutation.WithdrawalRequestCleared() && len(_u.mutation.WithdrawalRequestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralWithdrawalAllocation.withdrawal_request"`)
	}
	if _u.mutation.CommissionCleared() && len(_u.mutation.CommissionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralWithdrawalAllocation.commission"`)
	}
	return nil
}

func (_u *ReferralWithdrawalAllocationUpdateOne) sqlSave(ctx context.Context) (_node *ReferralWithdrawalAllocation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(referralwithdrawalallocation.Table, referralwithdrawalallocation.Columns, sqlgraph.NewFieldSpec(referralwithdrawalallocation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReferralWithdrawalAllocation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, referralwithdrawalallocation.FieldID)
		for _, f := range fields {
			if !referralwithdrawalallocation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != referralwithdrawalallocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(referralwithdrawalallocation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(referralwithdrawalallocation.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(referralwithdrawalallocation.FieldAmount, field.TypeFloat64, value)
	}
	if _u.mutation.PromoterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralwithdrawalallocation.PromoterTable,
			Columns: []string{referralwithdrawalallocation.PromoterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PromoterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralwithdrawalallocation.PromoterTable,
			Columns: []string{referralwithdrawalallocation.PromoterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WithdrawalRequestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralwithdrawalallocation.WithdrawalRequestTable,
			Columns: []string{referralwithdrawalallocation.WithdrawalRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referralwithdrawalrequest.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WithdrawalRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralwithdrawalallocation.WithdrawalRequestTable,
			Columns: []string{referralwithdrawalallocation.WithdrawalRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referralwithdrawalrequest.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralwithdrawalallocation.CommissionTable,
			Columns: []string{referralwithdrawalallocation.CommissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralwithdrawalallocation.CommissionTable,
			Columns: []string{referralwithdrawalallocation.CommissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ReferralWithdrawalAllocation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralwithdrawalallocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
