// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/rechargeorder"
	"github.com/Wei-Shaw/sub2api/ent/referralcommission"
	"github.com/Wei-Shaw/sub2api/ent/referralwithdrawalallocation"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ReferralCommissionCreate is the builder for creating a ReferralCommission entity.
type ReferralCommissionCreate struct {
	config
	mutation *ReferralCommissionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReferralCommissionCreate) SetCreatedAt(v time.Time) *ReferralCommissionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReferralCommissionCreate) SetNillableCreatedAt(v *time.Time) *ReferralCommissionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ReferralCommissionCreate) SetUpdatedAt(v time.Time) *ReferralCommissionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ReferralCommissionCreate) SetNillableUpdatedAt(v *time.Time) *ReferralCommissionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPromoterUserID sets the "promoter_user_id" field.
func (_c *ReferralCommissionCreate) SetPromoterUserID(v int64) *ReferralCommissionCreate {
	_c.mutation.SetPromoterUserID(v)
	return _c
}

// SetReferredUserID sets the "referred_user_id" field.
func (_c *ReferralCommissionCreate) SetReferredUserID(v int64) *ReferralCommissionCreate {
	_c.mutation.SetReferredUserID(v)
	return _c
}

// SetRechargeOrderID sets the "recharge_order_id" field.
func (_c *ReferralCommissionCreate) SetRechargeOrderID(v int64) *ReferralCommissionCreate {
	_c.mutation.SetRechargeOrderID(v)
	return _c
}

// SetCommissionType sets the "commission_type" field.
func (_c *ReferralCommissionCreate) SetCommissionType(v string) *ReferralCommissionCreate {
	_c.mutation.SetCommissionType(v)
	return _c
}

// SetNillableCommissionType sets the "commission_type" field if the given value is not nil.
func (_c *ReferralCommissionCreate) SetNillableCommissionType(v *string) *ReferralCommissionCreate {
	if v != nil {
		_c.SetCommissionType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ReferralCommissionCreate) SetStatus(v string) *ReferralCommissionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ReferralCommissionCreate) SetNillableStatus(v *string) *ReferralCommissionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSourceAmount sets the "source_amount" field.
func (_c *ReferralCommissionCreate) SetSourceAmount(v float64) *ReferralCommissionCreate {
	_c.mutation.SetSourceAmount(v)
	return _c
}

// SetNillableSourceAmount sets the "source_amount" field if the given value is not nil.
func (_c *ReferralCommissionCreate) SetNillableSourceAmount(v *float64) *ReferralCommissionCreate {
	if v != nil {
		_c.SetSourceAmount(*v)
	}
	return _c
}

// SetRateSnapshot sets the "rate_snapshot" field.
func (_c *ReferralCommissionCreate) SetRateSnapshot(v float64) *ReferralCommissionCreate {
	_c.mutation.SetRateSnapshot(v)
	return _c
}

// SetNillableRateSnapshot sets the "rate_snapshot" field if the given value is not nil.
func (_c *ReferralCommissionCreate) SetNillableRateSnapshot(v *float64) *ReferralCommissionCreate {
	if v != nil {
		_c.SetRateSnapshot(*v)
	}
	return _c
}

// SetCommissionAmount sets the "commission_amount" field.
func (_c *ReferralCommissionCreate) SetCommissionAmount(v float64) *ReferralCommissionCreate {
	_c.mutation.SetCommissionAmount(v)
	return _c
}

// SetNillableCommissionAmount sets the "commission_amount" field if the given value is not nil.
func (_c *ReferralCommissionCreate) SetNillableCommissionAmount(v *float64) *ReferralCommissionCreate {
	if v != nil {
		_c.SetCommissionAmount(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *ReferralCommissionCreate) SetCurrency(v string) *ReferralCommissionCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *ReferralCommissionCreate) SetNillableCurrency(v *string) *ReferralCommissionCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetReversedAt sets the "reversed_at" field.
func (_c *ReferralCommissionCreate) SetReversedAt(v time.Time) *ReferralCommissionCreate {
	_c.mutation.SetReversedAt(v)
	return _c
}

// SetNillableReversedAt sets the "reversed_at" field if the given value is not nil.
func (_c *ReferralCommissionCreate) SetNillableReversedAt(v *time.Time) *ReferralCommissionCreate {
	if v != nil {
		_c.SetReversedAt(*v)
	}
	return _c
}

// SetReversedReason sets the "reversed_reason" field.
func (_c *ReferralCommissionCreate) SetReversedReason(v string) *ReferralCommissionCreate {
	_c.mutation.SetReversedReason(v)
	return _c
}

// SetNillableReversedReason sets the "reversed_reason" field if the given value is not nil.
func (_c *ReferralCommissionCreate) SetNillableReversedReason(v *string) *ReferralCommissionCreate {
	if v != nil {
		_c.SetReversedReason(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *ReferralCommissionCreate) SetNotes(v string) *ReferralCommissionCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *ReferralCommissionCreate) SetNillableNotes(v *string) *ReferralCommissionCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetPromoterID sets the "promoter" edge to the User entity by ID.
func (_c *ReferralCommissionCreate) SetPromoterID(id int64) *ReferralCommissionCreate {
	_c.mutation.SetPromoterID(id)
	return _c
}

// SetPromoter sets the "promoter" edge to the User entity.
func (_c *ReferralCommissionCreate) SetPromoter(v *User) *ReferralCommissionCreate {
	return _c.SetPromoterID(v.ID)
}

// SetReferredUser sets the "referred_user" edge to the User entity.
func (_c *ReferralCommissionCreate) SetReferredUser(v *User) *ReferralCommissionCreate {
	return _c.SetReferredUserID(v.ID)
}

// SetRechargeOrder sets the "recharge_order" edge to the RechargeOrder entity.
func (_c *ReferralCommissionCreate) SetRechargeOrder(v *RechargeOrder) *ReferralCommissionCreate {
	return _c.SetRechargeOrderID(v.ID)
}

// AddWithdrawalAllocationIDs adds the "withdrawal_allocations" edge to the ReferralWithdrawalAllocation entity by IDs.
func (_c *ReferralCommissionCreate) AddWithdrawalAllocationIDs(ids ...int64) *ReferralCommissionCreate {
	_c.mutation.AddWithdrawalAllocationIDs(ids...)
	return _c
}

// AddWithdrawalAllocations adds the "withdrawal_allocations" edges to the ReferralWithdrawalAllocation entity.
func (_c *ReferralCommissionCreate) AddWithdrawalAllocations(v ...*ReferralWithdrawalAllocation) *ReferralCommissionCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddWithdrawalAllocationIDs(ids...)
}

// Mutation returns the ReferralCommissionMutation object of the builder.
func (_c *ReferralCommissionCreate) Mutation() *ReferralCommissionMutation {
	return _c.mutation
}

// Save creates the ReferralCommission in the database.
func (_c *ReferralCommissionCreate) Save(ctx context.Context) (*ReferralCommission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReferralCommissionCreate) SaveX(ctx context.Context) *ReferralCommission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralCommissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralCommissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReferralCommissionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := referralcommission.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := referralcommission.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CommissionType(); !ok {
		v := referralcommission.DefaultCommissionType
		_c.mutation.SetCommissionType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := referralcommission.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SourceAmount(); !ok {
		v := referralcommission.DefaultSourceAmount
		_c.mutation.SetSourceAmount(v)
	}
	if _, ok := _c.mutation.RateSnapshot(); !ok {
		v := referralcommission.DefaultRateSnapshot
		_c.mutation.SetRateSnapshot(v)
	}
	if _, ok := _c.mutation.CommissionAmount(); !ok {
		v := referralcommission.DefaultCommissionAmount
		_c.mutation.SetCommissionAmount(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := referralcommission.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReferralCommissionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReferralCommission.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ReferralCommission.updated_at"`)}
	}
	if _, ok := _c.mutation.PromoterUserID(); !ok {
		return &ValidationError{Name: "promoter_user_id", err: errors.New(`ent: missing required field "ReferralCommission.promoter_user_id"`)}
	}
	if _, ok := _c.mutation.ReferredUserID(); !ok {
		return &ValidationError{Name: "referred_user_id", err: errors.New(`ent: missing required field "ReferralCommission.referred_user_id"`)}
	}
	if _, ok := _c.mutation.RechargeOrderID(); !ok {
		return &ValidationError{Name: "recharge_order_id", err: errors.New(`ent: missing required field "ReferralCommission.recharge_order_id"`)}
	}
	if _, ok := _c.mutation.CommissionType(); !ok {
		return &ValidationError{Name: "commission_type", err: errors.New(`ent: missing required field "ReferralCommission.commission_type"`)}
	}
	if v, ok := _c.mutation.CommissionType(); ok {
		if err := referralcommission.CommissionTypeValidator(v); err != nil {
			return &ValidationError{Name: "commission_type", err: fmt.Errorf(`ent: validator failed for field "ReferralCommission.commission_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ReferralCommission.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := referralcommission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReferralCommission.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceAmount(); !ok {
		return &ValidationError{Name: "source_amount", err: errors.New(`ent: missing required field "ReferralCommission.source_amount"`)}
	}
	if _, ok := _c.mutation.RateSnapshot(); !ok {
		return &ValidationError{Name: "rate_snapshot", err: errors.New(`ent: missing required field "ReferralCommission.rate_snapshot"`)}
	}
	if _, ok := _c.mutation.CommissionAmount(); !ok {
		return &ValidationError{Name: "commission_amount", err: errors.New(`ent: missing required field "ReferralCommission.commission_amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "ReferralCommission.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := referralcommission.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "ReferralCommission.currency": %w`, err)}
		}
	}
	if len(_c.mutation.PromoterIDs()) == 0 {
		return &ValidationError{Name: "promoter", err: errors.New(`ent: missing required edge "ReferralCommission.promoter"`)}
	}
	if len(_c.mutation.ReferredUserIDs()) == 0 {
		return &ValidationError{Name: "referred_user", err: errors.New(`ent: missing required edge "ReferralCommission.referred_user"`)}
	}
	if len(_c.mutation.RechargeOrderIDs()) == 0 {
		return &ValidationError{Name: "recharge_order", err: errors.New(`ent: missing required edge "ReferralCommission.recharge_order"`)}
	}
	return nil
}

func (_c *ReferralCommissionCreate) sqlSave(ctx context.Context) (*ReferralCommission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReferralCommissionCreate) createSpec() (*ReferralCommission, *sqlgraph.CreateSpec) {
	var (
		_node = &ReferralCommission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(referralcommission.Table, sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(referralcommission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(referralcommission.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CommissionType(); ok {
		_spec.SetField(referralcommission.FieldCommissionType, field.TypeString, value)
		_node.CommissionType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(referralcommission.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SourceAmount(); ok {
		_spec.SetField(referralcommission.FieldSourceAmount, field.TypeFloat64, value)
		_node.SourceAmount = value
	}
	if value, ok := _c.mutation.RateSnapshot(); ok {
		_spec.SetField(referralcommission.FieldRateSnapshot, field.TypeFloat64, value)
		_node.RateSnapshot = value
	}
	if value, ok := _c.mutation.CommissionAmount(); ok {
		_spec.SetField(referralcommission.FieldCommissionAmount, field.TypeFloat64, value)
		_node.CommissionAmount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(referralcommission.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.ReversedAt(); ok {
		_spec.SetField(referralcommission.FieldReversedAt, field.TypeTime, value)
		_node.ReversedAt = &value
	}
	if value, ok := _c.mutation.ReversedReason(); ok {
		_spec.SetField(referralcommission.FieldReversedReason, field.TypeString, value)
		_node.ReversedReason = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(referralcommission.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if nodes := _c.mutation.PromoterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.PromoterTable,
			Columns: []string{referralcommission.PromoterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PromoterUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReferredUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.ReferredUserTable,
			Columns: []string{referralcommission.ReferredUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReferredUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RechargeOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.RechargeOrderTable,
			Columns: []string{referralcommission.RechargeOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RechargeOrderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WithdrawalAllocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   referralcommission.WithdrawalAllocationsTable,
			Columns: []string{referralcommission.WithdrawalAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(referralwithdrawalallocation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralCommission.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralCommissionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralCommissionCreate) OnConflict(opts ...sql.ConflictOption) *ReferralCommissionUpsertOne {
	_c.conflict = opts
	return &ReferralCommissionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralCommission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralCommissionCreate) OnConflictColumns(columns ...string) *ReferralCommissionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralCommissionUpsertOne{
		create: _c,
	}
}

type (
	// ReferralCommissionUpsertOne is the builder for "upsert"-ing
	//  one ReferralCommission node.
	ReferralCommissionUpsertOne struct {
		create *ReferralCommissionCreate
	}

	// ReferralCommissionUpsert is the "OnConflict" setter.
	ReferralCommissionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ReferralCommissionUpsert) SetUpdatedAt(v time.Time) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateUpdatedAt() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldUpdatedAt)
	return u
}

// SetPromoterUserID sets the "promoter_user_id" field.
func (u *ReferralCommissionUpsert) SetPromoterUserID(v int64) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldPromoterUserID, v)
	return u
}

// UpdatePromoterUserID sets the "promoter_user_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdatePromoterUserID() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldPromoterUserID)
	return u
}

// SetReferredUserID sets the "referred_user_id" field.
func (u *ReferralCommissionUpsert) SetReferredUserID(v int64) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldReferredUserID, v)
	return u
}

// UpdateReferredUserID sets the "referred_user_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateReferredUserID() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldReferredUserID)
	return u
}

// SetRechargeOrderID sets the "recharge_order_id" field.
func (u *ReferralCommissionUpsert) SetRechargeOrderID(v int64) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldRechargeOrderID, v)
	return u
}

// UpdateRechargeOrderID sets the "recharge_order_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateRechargeOrderID() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldRechargeOrderID)
	return u
}

// SetCommissionType sets the "commission_type" field.
func (u *ReferralCommissionUpsert) SetCommissionType(v string) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldCommissionType, v)
	return u
}

// UpdateCommissionType sets the "commission_type" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateCommissionType() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldCommissionType)
	return u
}

// SetStatus sets the "status" field.
func (u *ReferralCommissionUpsert) SetStatus(v string) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateStatus() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldStatus)
	return u
}

// SetSourceAmount sets the "source_amount" field.
func (u *ReferralCommissionUpsert) SetSourceAmount(v float64) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldSourceAmount, v)
	return u
}

// UpdateSourceAmount sets the "source_amount" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateSourceAmount() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldSourceAmount)
	return u
}

// AddSourceAmount adds v to the "source_amount" field.
func (u *ReferralCommissionUpsert) AddSourceAmount(v float64) *ReferralCommissionUpsert {
	u.Add(referralcommission.FieldSourceAmount, v)
	return u
}

// SetRateSnapshot sets the "rate_snapshot" field.
func (u *ReferralCommissionUpsert) SetRateSnapshot(v float64) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldRateSnapshot, v)
	return u
}

// UpdateRateSnapshot sets the "rate_snapshot" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateRateSnapshot() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldRateSnapshot)
	return u
}

// AddRateSnapshot adds v to the "rate_snapshot" field.
func (u *ReferralCommissionUpsert) AddRateSnapshot(v float64) *ReferralCommissionUpsert {
	u.Add(referralcommission.FieldRateSnapshot, v)
	return u
}

// SetCommissionAmount sets the "commission_amount" field.
func (u *ReferralCommissionUpsert) SetCommissionAmount(v float64) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldCommissionAmount, v)
	return u
}

// UpdateCommissionAmount sets the "commission_amount" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateCommissionAmount() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldCommissionAmount)
	return u
}

// AddCommissionAmount adds v to the "commission_amount" field.
func (u *ReferralCommissionUpsert) AddCommissionAmount(v float64) *ReferralCommissionUpsert {
	u.Add(referralcommission.FieldCommissionAmount, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *ReferralCommissionUpsert) SetCurrency(v string) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateCurrency() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldCurrency)
	return u
}

// SetReversedAt sets the "reversed_at" field.
func (u *ReferralCommissionUpsert) SetReversedAt(v time.Time) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldReversedAt, v)
	return u
}

// UpdateReversedAt sets the "reversed_at" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateReversedAt() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldReversedAt)
	return u
}

// ClearReversedAt clears the value of the "reversed_at" field.
func (u *ReferralCommissionUpsert) ClearReversedAt() *ReferralCommissionUpsert {
	u.SetNull(referralcommission.FieldReversedAt)
	return u
}

// SetReversedReason sets the "reversed_reason" field.
func (u *ReferralCommissionUpsert) SetReversedReason(v string) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldReversedReason, v)
	return u
}

// UpdateReversedReason sets the "reversed_reason" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateReversedReason() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldReversedReason)
	return u
}

// ClearReversedReason clears the value of the "reversed_reason" field.
func (u *ReferralCommissionUpsert) ClearReversedReason() *ReferralCommissionUpsert {
	u.SetNull(referralcommission.FieldReversedReason)
	return u
}

// SetNotes sets the "notes" field.
func (u *ReferralCommissionUpsert) SetNotes(v string) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateNotes() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *ReferralCommissionUpsert) ClearNotes() *ReferralCommissionUpsert {
	u.SetNull(referralcommission.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ReferralCommission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralCommissionUpsertOne) UpdateNewValues() *ReferralCommissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(referralcommission.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralCommission.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReferralCommissionUpsertOne) Ignore() *ReferralCommissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralCommissionUpsertOne) DoNothing() *ReferralCommissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralCommissionCreate.OnConflict
// documentation for more info.
func (u *ReferralCommissionUpsertOne) Update(set func(*ReferralCommissionUpsert)) *ReferralCommissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralCommissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReferralCommissionUpsertOne) SetUpdatedAt(v time.Time) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateUpdatedAt() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPromoterUserID sets the "promoter_user_id" field.
func (u *ReferralCommissionUpsertOne) SetPromoterUserID(v int64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetPromoterUserID(v)
	})
}

// UpdatePromoterUserID sets the "promoter_user_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdatePromoterUserID() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdatePromoterUserID()
	})
}

// SetReferredUserID sets the "referred_user_id" field.
func (u *ReferralCommissionUpsertOne) SetReferredUserID(v int64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetReferredUserID(v)
	})
}

// UpdateReferredUserID sets the "referred_user_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateReferredUserID() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateReferredUserID()
	})
}

// SetRechargeOrderID sets the "recharge_order_id" field.
func (u *ReferralCommissionUpsertOne) SetRechargeOrderID(v int64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetRechargeOrderID(v)
	})
}

// UpdateRechargeOrderID sets the "recharge_order_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateRechargeOrderID() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateRechargeOrderID()
	})
}

// SetCommissionType sets the "commission_type" field.
func (u *ReferralCommissionUpsertOne) SetCommissionType(v string) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetCommissionType(v)
	})
}

// UpdateCommissionType sets the "commission_type" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateCommissionType() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateCommissionType()
	})
}

// SetStatus sets the "status" field.
func (u *ReferralCommissionUpsertOne) SetStatus(v string) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateStatus() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateStatus()
	})
}

// SetSourceAmount sets the "source_amount" field.
func (u *ReferralCommissionUpsertOne) SetSourceAmount(v float64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetSourceAmount(v)
	})
}

// AddSourceAmount adds v to the "source_amount" field.
func (u *ReferralCommissionUpsertOne) AddSourceAmount(v float64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddSourceAmount(v)
	})
}

// UpdateSourceAmount sets the "source_amount" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateSourceAmount() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateSourceAmount()
	})
}

// SetRateSnapshot sets the "rate_snapshot" field.
func (u *ReferralCommissionUpsertOne) SetRateSnapshot(v float64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetRateSnapshot(v)
	})
}

// AddRateSnapshot adds v to the "rate_snapshot" field.
func (u *ReferralCommissionUpsertOne) AddRateSnapshot(v float64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddRateSnapshot(v)
	})
}

// UpdateRateSnapshot sets the "rate_snapshot" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateRateSnapshot() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateRateSnapshot()
	})
}

// SetCommissionAmount sets the "commission_amount" field.
func (u *ReferralCommissionUpsertOne) SetCommissionAmount(v float64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetCommissionAmount(v)
	})
}

// AddCommissionAmount adds v to the "commission_amount" field.
func (u *ReferralCommissionUpsertOne) AddCommissionAmount(v float64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddCommissionAmount(v)
	})
}

// UpdateCommissionAmount sets the "commission_amount" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateCommissionAmount() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateCommissionAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *ReferralCommissionUpsertOne) SetCurrency(v string) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateCurrency() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateCurrency()
	})
}

// SetReversedAt sets the "reversed_at" field.
func (u *ReferralCommissionUpsertOne) SetReversedAt(v time.Time) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetReversedAt(v)
	})
}

// UpdateReversedAt sets the "reversed_at" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateReversedAt() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateReversedAt()
	})
}

// ClearReversedAt clears the value of the "reversed_at" field.
func (u *ReferralCommissionUpsertOne) ClearReversedAt() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.ClearReversedAt()
	})
}

// SetReversedReason sets the "reversed_reason" field.
func (u *ReferralCommissionUpsertOne) SetReversedReason(v string) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetReversedReason(v)
	})
}

// UpdateReversedReason sets the "reversed_reason" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateReversedReason() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateReversedReason()
	})
}

// ClearReversedReason clears the value of the "reversed_reason" field.
func (u *ReferralCommissionUpsertOne) ClearReversedReason() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.ClearReversedReason()
	})
}

// SetNotes sets the "notes" field.
func (u *ReferralCommissionUpsertOne) SetNotes(v string) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateNotes() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *ReferralCommissionUpsertOne) ClearNotes() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *ReferralCommissionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralCommissionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralCommissionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReferralCommissionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReferralCommissionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReferralCommissionCreateBulk is the builder for creating many ReferralCommission entities in bulk.
type ReferralCommissionCreateBulk struct {
	config
	err      error
	builders []*ReferralCommissionCreate
	conflict []sql.ConflictOption
}

// Save creates the ReferralCommission entities in the database.
func (_c *ReferralCommissionCreateBulk) Save(ctx context.Context) ([]*ReferralCommission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReferralCommission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReferralCommissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReferralCommissionCreateBulk) SaveX(ctx context.Context) []*ReferralCommission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralCommissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralCommissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralCommission.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralCommissionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralCommissionCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReferralCommissionUpsertBulk {
	_c.conflict = opts
	return &ReferralCommissionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralCommission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralCommissionCreateBulk) OnConflictColumns(columns ...string) *ReferralCommissionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralCommissionUpsertBulk{
		create: _c,
	}
}

// ReferralCommissionUpsertBulk is the builder for "upsert"-ing
// a bulk of ReferralCommission nodes.
type ReferralCommissionUpsertBulk struct {
	create *ReferralCommissionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ReferralCommission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralCommissionUpsertBulk) UpdateNewValues() *ReferralCommissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(referralcommission.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralCommission.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReferralCommissionUpsertBulk) Ignore() *ReferralCommissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralCommissionUpsertBulk) DoNothing() *ReferralCommissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralCommissionCreateBulk.OnConflict
// documentation for more info.
func (u *ReferralCommissionUpsertBulk) Update(set func(*ReferralCommissionUpsert)) *ReferralCommissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralCommissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReferralCommissionUpsertBulk) SetUpdatedAt(v time.Time) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateUpdatedAt() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPromoterUserID sets the "promoter_user_id" field.
func (u *ReferralCommissionUpsertBulk) SetPromoterUserID(v int64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetPromoterUserID(v)
	})
}

// UpdatePromoterUserID sets the "promoter_user_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdatePromoterUserID() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdatePromoterUserID()
	})
}

// SetReferredUserID sets the "referred_user_id" field.
func (u *ReferralCommissionUpsertBulk) SetReferredUserID(v int64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetReferredUserID(v)
	})
}

// UpdateReferredUserID sets the "referred_user_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateReferredUserID() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateReferredUserID()
	})
}

// SetRechargeOrderID sets the "recharge_order_id" field.
func (u *ReferralCommissionUpsertBulk) SetRechargeOrderID(v int64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetRechargeOrderID(v)
	})
}

// UpdateRechargeOrderID sets the "recharge_order_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateRechargeOrderID() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateRechargeOrderID()
	})
}

// SetCommissionType sets the "commission_type" field.
func (u *ReferralCommissionUpsertBulk) SetCommissionType(v string) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetCommissionType(v)
	})
}

// UpdateCommissionType sets the "commission_type" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateCommissionType() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateCommissionType()
	})
}

// SetStatus sets the "status" field.
func (u *ReferralCommissionUpsertBulk) SetStatus(v string) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateStatus() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateStatus()
	})
}

// SetSourceAmount sets the "source_amount" field.
func (u *ReferralCommissionUpsertBulk) SetSourceAmount(v float64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetSourceAmount(v)
	})
}

// AddSourceAmount adds v to the "source_amount" field.
func (u *ReferralCommissionUpsertBulk) AddSourceAmount(v float64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddSourceAmount(v)
	})
}

// UpdateSourceAmount sets the "source_amount" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateSourceAmount() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateSourceAmount()
	})
}

// SetRateSnapshot sets the "rate_snapshot" field.
func (u *ReferralCommissionUpsertBulk) SetRateSnapshot(v float64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetRateSnapshot(v)
	})
}

// AddRateSnapshot adds v to the "rate_snapshot" field.
func (u *ReferralCommissionUpsertBulk) AddRateSnapshot(v float64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddRateSnapshot(v)
	})
}

// UpdateRateSnapshot sets the "rate_snapshot" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateRateSnapshot() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateRateSnapshot()
	})
}

// SetCommissionAmount sets the "commission_amount" field.
func (u *ReferralCommissionUpsertBulk) SetCommissionAmount(v float64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetCommissionAmount(v)
	})
}

// AddCommissionAmount adds v to the "commission_amount" field.
func (u *ReferralCommissionUpsertBulk) AddCommissionAmount(v float64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddCommissionAmount(v)
	})
}

// UpdateCommissionAmount sets the "commission_amount" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateCommissionAmount() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateCommissionAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *ReferralCommissionUpsertBulk) SetCurrency(v string) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateCurrency() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateCurrency()
	})
}

// SetReversedAt sets the "reversed_at" field.
func (u *ReferralCommissionUpsertBulk) SetReversedAt(v time.Time) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetReversedAt(v)
	})
}

// UpdateReversedAt sets the "reversed_at" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateReversedAt() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateReversedAt()
	})
}

// ClearReversedAt clears the value of the "reversed_at" field.
func (u *ReferralCommissionUpsertBulk) ClearReversedAt() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.ClearReversedAt()
	})
}

// SetReversedReason sets the "reversed_reason" field.
func (u *ReferralCommissionUpsertBulk) SetReversedReason(v string) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetReversedReason(v)
	})
}

// UpdateReversedReason sets the "reversed_reason" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateReversedReason() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateReversedReason()
	})
}

// ClearReversedReason clears the value of the "reversed_reason" field.
func (u *ReferralCommissionUpsertBulk) ClearReversedReason() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.ClearReversedReason()
	})
}

// SetNotes sets the "notes" field.
func (u *ReferralCommissionUpsertBulk) SetNotes(v string) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateNotes() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *ReferralCommissionUpsertBulk) ClearNotes() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *ReferralCommissionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReferralCommissionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralCommissionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralCommissionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
