// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rechargeorder"
	"github.com/Wei-Shaw/sub2api/ent/referralcommission"
	"github.com/Wei-Shaw/sub2api/ent/referralwithdrawalallocation"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ReferralCommissionQuery is the builder for querying ReferralCommission entities.
type ReferralCommissionQuery struct {
	config
	ctx                       *QueryContext
	order                     []referralcommission.OrderOption
	inters                    []Interceptor
	predicates                []predicate.ReferralCommission
	withPromoter              *UserQuery
	withReferredUser          *UserQuery
	withRechargeOrder         *RechargeOrderQuery
	withWithdrawalAllocations *ReferralWithdrawalAllocationQuery
	modifiers                 []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReferralCommissionQuery builder.
func (_q *ReferralCommissionQuery) Where(ps ...predicate.ReferralCommission) *ReferralCommissionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ReferralCommissionQuery) Limit(limit int) *ReferralCommissionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ReferralCommissionQuery) Offset(offset int) *ReferralCommissionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ReferralCommissionQuery) Unique(unique bool) *ReferralCommissionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ReferralCommissionQuery) Order(o ...referralcommission.OrderOption) *ReferralCommissionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPromoter chains the current query on the "promoter" edge.
func (_q *ReferralCommissionQuery) QueryPromoter() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(referralcommission.Table, referralcommission.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, referralcommission.PromoterTable, referralcommission.PromoterColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReferredUser chains the current query on the "referred_user" edge.
func (_q *ReferralCommissionQuery) QueryReferredUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(referralcommission.Table, referralcommission.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, referralcommission.ReferredUserTable, referralcommission.ReferredUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRechargeOrder chains the current query on the "recharge_order" edge.
func (_q *ReferralCommissionQuery) QueryRechargeOrder() *RechargeOrderQuery {
	query := (&RechargeOrderClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(referralcommission.Table, referralcommission.FieldID, selector),
			sqlgraph.To(rechargeorder.Table, rechargeorder.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, referralcommission.RechargeOrderTable, referralcommission.RechargeOrderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWithdrawalAllocations chains the current query on the "withdrawal_allocations" edge.
func (_q *ReferralCommissionQuery) QueryWithdrawalAllocations() *ReferralWithdrawalAllocationQuery {
	query := (&ReferralWithdrawalAllocationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(referralcommission.Table, referralcommission.FieldID, selector),
			sqlgraph.To(referralwithdrawalallocation.Table, referralwithdrawalallocation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, referralcommission.WithdrawalAllocationsTable, referralcommission.WithdrawalAllocationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ReferralCommission entity from the query.
// Returns a *NotFoundError when no ReferralCommission was found.
func (_q *ReferralCommissionQuery) First(ctx context.Context) (*ReferralCommission, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{referralcommission.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ReferralCommissionQuery) FirstX(ctx context.Context) *ReferralCommission {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ReferralCommission ID from the query.
// Returns a *NotFoundError when no ReferralCommission ID was found.
func (_q *ReferralCommissionQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{referralcommission.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ReferralCommissionQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ReferralCommission entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ReferralCommission entity is found.
// Returns a *NotFoundError when no ReferralCommission entities are found.
func (_q *ReferralCommissionQuery) Only(ctx context.Context) (*ReferralCommission, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{referralcommission.Label}
	default:
		return nil, &NotSingularError{referralcommission.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ReferralCommissionQuery) OnlyX(ctx context.Context) *ReferralCommission {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ReferralCommission ID in the query.
// Returns a *NotSingularError when more than one ReferralCommission ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ReferralCommissionQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{referralcommission.Label}
	default:
		err = &NotSingularError{referralcommission.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ReferralCommissionQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ReferralCommissions.
func (_q *ReferralCommissionQuery) All(ctx context.Context) ([]*ReferralCommission, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ReferralCommission, *ReferralCommissionQuery]()
	return withInterceptors[[]*ReferralCommission](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ReferralCommissionQuery) AllX(ctx context.Context) []*ReferralCommission {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ReferralCommission IDs.
func (_q *ReferralCommissionQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(referralcommission.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ReferralCommissionQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ReferralCommissionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ReferralCommissionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ReferralCommissionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ReferralCommissionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ReferralCommissionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReferralCommissionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ReferralCommissionQuery) Clone() *ReferralCommissionQuery {
	if _q == nil {
		return nil
	}
	return &ReferralCommissionQuery{
		config:                    _q.config,
		ctx:                       _q.ctx.Clone(),
		order:                     append([]referralcommission.OrderOption{}, _q.order...),
		inters:                    append([]Interceptor{}, _q.inters...),
		predicates:                append([]predicate.ReferralCommission{}, _q.predicates...),
		withPromoter:              _q.withPromoter.Clone(),
		withReferredUser:          _q.withReferredUser.Clone(),
		withRechargeOrder:         _q.withRechargeOrder.Clone(),
		withWithdrawalAllocations: _q.withWithdrawalAllocations.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPromoter tells the query-builder to eager-load the nodes that are connected to
// the "promoter" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ReferralCommissionQuery) WithPromoter(opts ...func(*UserQuery)) *ReferralCommissionQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPromoter = query
	return _q
}

// WithReferredUser tells the query-builder to eager-load the nodes that are connected to
// the "referred_user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ReferralCommissionQuery) WithReferredUser(opts ...func(*UserQuery)) *ReferralCommissionQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withReferredUser = query
	return _q
}

// WithRechargeOrder tells the query-builder to eager-load the nodes that are connected to
// the "recharge_order" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ReferralCommissionQuery) WithRechargeOrder(opts ...func(*RechargeOrderQuery)) *ReferralCommissionQuery {
	query := (&RechargeOrderClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRechargeOrder = query
	return _q
}

// WithWithdrawalAllocations tells the query-builder to eager-load the nodes that are connected to
// the "withdrawal_allocations" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ReferralCommissionQuery) WithWithdrawalAllocations(opts ...func(*ReferralWithdrawalAllocationQuery)) *ReferralCommissionQuery {
	query := (&ReferralWithdrawalAllocationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWithdrawalAllocations = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ReferralCommission.Query().
//		GroupBy(referralcommission.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ReferralCommissionQuery) GroupBy(field string, fields ...string) *ReferralCommissionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ReferralCommissionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = referralcommission.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ReferralCommission.Query().
//		Select(referralcommission.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *ReferralCommissionQuery) Select(fields ...string) *ReferralCommissionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ReferralCommissionSelect{ReferralCommissionQuery: _q}
	sbuild.label = referralcommission.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ReferralCommissionSelect configured with the given aggregations.
func (_q *ReferralCommissionQuery) Aggregate(fns ...AggregateFunc) *ReferralCommissionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ReferralCommissionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !referralcommission.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ReferralCommissionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ReferralCommission, error) {
	var (
		nodes       = []*ReferralCommission{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withPromoter != nil,
			_q.withReferredUser != nil,
			_q.withRechargeOrder != nil,
			_q.withWithdrawalAllocations != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ReferralCommission).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ReferralCommission{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPromoter; query != nil {
		if err := _q.loadPromoter(ctx, query, nodes, nil,
			func(n *ReferralCommission, e *User) { n.Edges.Promoter = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withReferredUser; query != nil {
		if err := _q.loadReferredUser(ctx, query, nodes, nil,
			func(n *ReferralCommission, e *User) { n.Edges.ReferredUser = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRechargeOrder; query != nil {
		if err := _q.loadRechargeOrder(ctx, query, nodes, nil,
			func(n *ReferralCommission, e *RechargeOrder) { n.Edges.RechargeOrder = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withWithdrawalAllocations; query != nil {
		if err := _q.loadWithdrawalAllocations(ctx, query, nodes,
			func(n *ReferralCommission) { n.Edges.WithdrawalAllocations = []*ReferralWithdrawalAllocation{} },
			func(n *ReferralCommission, e *ReferralWithdrawalAllocation) {
				n.Edges.WithdrawalAllocations = append(n.Edges.WithdrawalAllocations, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ReferralCommissionQuery) loadPromoter(ctx context.Context, query *UserQuery, nodes []*ReferralCommission, init func(*ReferralCommission), assign func(*ReferralCommission, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ReferralCommission)
	for i := range nodes {
		fk := nodes[i].PromoterUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "promoter_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ReferralCommissionQuery) loadReferredUser(ctx context.Context, query *UserQuery, nodes []*ReferralCommission, init func(*ReferralCommission), assign func(*ReferralCommission, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ReferralCommission)
	for i := range nodes {
		fk := nodes[i].ReferredUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "referred_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ReferralCommissionQuery) loadRechargeOrder(ctx context.Context, query *RechargeOrderQuery, nodes []*ReferralCommission, init func(*ReferralCommission), assign func(*ReferralCommission, *RechargeOrder)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ReferralCommission)
	for i := range nodes {
		fk := nodes[i].RechargeOrderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(rechargeorder.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "recharge_order_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ReferralCommissionQuery) loadWithdrawalAllocations(ctx context.Context, query *ReferralWithdrawalAllocationQuery, nodes []*ReferralCommission, init func(*ReferralCommission), assign func(*ReferralCommission, *ReferralWithdrawalAllocation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*ReferralCommission)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(referralwithdrawalallocation.FieldCommissionID)
	}
	query.Where(predicate.ReferralWithdrawalAllocation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(referralcommission.WithdrawalAllocationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CommissionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "commission_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ReferralCommissionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ReferralCommissionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(referralcommission.Table, referralcommission.Columns, sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, referralcommission.FieldID)
		for i := range fields {
			if fields[i] != referralcommission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withPromoter != nil {
			_spec.Node.AddColumnOnce(referralcommission.FieldPromoterUserID)
		}
		if _q.withReferredUser != nil {
			_spec.Node.AddColumnOnce(referralcommission.FieldReferredUserID)
		}
		if _q.withRechargeOrder != nil {
			_spec.Node.AddColumnOnce(referralcommission.FieldRechargeOrderID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ReferralCommissionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(referralcommission.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = referralcommission.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *ReferralCommissionQuery) ForUpdate(opts ...sql.LockOption) *ReferralCommissionQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *ReferralCommissionQuery) ForShare(opts ...sql.LockOption) *ReferralCommissionQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// ReferralCommissionGroupBy is the group-by builder for ReferralCommission entities.
type ReferralCommissionGroupBy struct {
	selector
	build *ReferralCommissionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ReferralCommissionGroupBy) Aggregate(fns ...AggregateFunc) *ReferralCommissionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ReferralCommissionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReferralCommissionQuery, *ReferralCommissionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ReferralCommissionGroupBy) sqlScan(ctx context.Context, root *ReferralCommissionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ReferralCommissionSelect is the builder for selecting fields of ReferralCommission entities.
type ReferralCommissionSelect struct {
	*ReferralCommissionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ReferralCommissionSelect) Aggregate(fns ...AggregateFunc) *ReferralCommissionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ReferralCommissionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReferralCommissionQuery, *ReferralCommissionSelect](ctx, _s.ReferralCommissionQuery, _s, _s.inters, v)
}

func (_s *ReferralCommissionSelect) sqlScan(ctx context.Context, root *ReferralCommissionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
