// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/referralcommission"
	"github.com/Wei-Shaw/sub2api/ent/referralwithdrawalallocation"
	"github.com/Wei-Shaw/sub2api/ent/referralwithdrawalrequest"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ReferralWithdrawalAllocationQuery is the builder for querying ReferralWithdrawalAllocation entities.
type ReferralWithdrawalAllocationQuery struct {
	config
	ctx                   *QueryContext
	order                 []referralwithdrawalallocation.OrderOption
	inters                []Interceptor
	predicates            []predicate.ReferralWithdrawalAllocation
	withPromoter          *UserQuery
	withWithdrawalRequest *ReferralWithdrawalRequestQuery
	withCommission        *ReferralCommissionQuery
	modifiers             []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReferralWithdrawalAllocationQuery builder.
func (_q *ReferralWithdrawalAllocationQuery) Where(ps ...predicate.ReferralWithdrawalAllocation) *ReferralWithdrawalAllocationQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ReferralWithdrawalAllocationQuery) Limit(limit int) *ReferralWithdrawalAllocationQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ReferralWithdrawalAllocationQuery) Offset(offset int) *ReferralWithdrawalAllocationQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ReferralWithdrawalAllocationQuery) Unique(unique bool) *ReferralWithdrawalAllocationQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ReferralWithdrawalAllocationQuery) Order(o ...referralwithdrawalallocation.OrderOption) *ReferralWithdrawalAllocationQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPromoter chains the current query on the "promoter" edge.
func (_q *ReferralWithdrawalAllocationQuery) QueryPromoter() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(referralwithdrawalallocation.Table, referralwithdrawalallocation.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, referralwithdrawalallocation.PromoterTable, referralwithdrawalallocation.PromoterColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWithdrawalRequest chains the current query on the "withdrawal_request" edge.
func (_q *ReferralWithdrawalAllocationQuery) QueryWithdrawalRequest() *ReferralWithdrawalRequestQuery {
	query := (&ReferralWithdrawalRequestClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(referralwithdrawalallocation.Table, referralwithdrawalallocation.FieldID, selector),
			sqlgraph.To(referralwithdrawalrequest.Table, referralwithdrawalrequest.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, referralwithdrawalallocation.WithdrawalRequestTable, referralwithdrawalallocation.WithdrawalRequestColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCommission chains the current query on the "commission" edge.
func (_q *ReferralWithdrawalAllocationQuery) QueryCommission() *ReferralCommissionQuery {
	query := (&ReferralCommissionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(referralwithdrawalallocation.Table, referralwithdrawalallocation.FieldID, selector),
			sqlgraph.To(referralcommission.Table, referralcommission.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, referralwithdrawalallocation.CommissionTable, referralwithdrawalallocation.CommissionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ReferralWithdrawalAllocation entity from the query.
// Returns a *NotFoundError when no ReferralWithdrawalAllocation was found.
func (_q *ReferralWithdrawalAllocationQuery) First(ctx context.Context) (*ReferralWithdrawalAllocation, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{referralwithdrawalallocation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ReferralWithdrawalAllocationQuery) FirstX(ctx context.Context) *ReferralWithdrawalAllocation {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ReferralWithdrawalAllocation ID from the query.
// Returns a *NotFoundError when no ReferralWithdrawalAllocation ID was found.
func (_q *ReferralWithdrawalAllocationQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{referralwithdrawalallocation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ReferralWithdrawalAllocationQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ReferralWithdrawalAllocation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ReferralWithdrawalAllocation entity is found.
// Returns a *NotFoundError when no ReferralWithdrawalAllocation entities are found.
func (_q *ReferralWithdrawalAllocationQuery) Only(ctx context.Context) (*ReferralWithdrawalAllocation, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{referralwithdrawalallocation.Label}
	default:
		return nil, &NotSingularError{referralwithdrawalallocation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ReferralWithdrawalAllocationQuery) OnlyX(ctx context.Context) *ReferralWithdrawalAllocation {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ReferralWithdrawalAllocation ID in the query.
// Returns a *NotSingularError when more than one ReferralWithdrawalAllocation ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ReferralWithdrawalAllocationQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{referralwithdrawalallocation.Label}
	default:
		err = &NotSingularError{referralwithdrawalallocation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ReferralWithdrawalAllocationQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ReferralWithdrawalAllocations.
func (_q *ReferralWithdrawalAllocationQuery) All(ctx context.Context) ([]*ReferralWithdrawalAllocation, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ReferralWithdrawalAllocation, *ReferralWithdrawalAllocationQuery]()
	return withInterceptors[[]*ReferralWithdrawalAllocation](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ReferralWithdrawalAllocationQuery) AllX(ctx context.Context) []*ReferralWithdrawalAllocation {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ReferralWithdrawalAllocation IDs.
func (_q *ReferralWithdrawalAllocationQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(referralwithdrawalallocation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ReferralWithdrawalAllocationQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ReferralWithdrawalAllocationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ReferralWithdrawalAllocationQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ReferralWithdrawalAllocationQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ReferralWithdrawalAllocationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ReferralWithdrawalAllocationQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReferralWithdrawalAllocationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ReferralWithdrawalAllocationQuery) Clone() *ReferralWithdrawalAllocationQuery {
	if _q == nil {
		return nil
	}
	return &ReferralWithdrawalAllocationQuery{
		config:                _q.config,
		ctx:                   _q.ctx.Clone(),
		order:                 append([]referralwithdrawalallocation.OrderOption{}, _q.order...),
		inters:                append([]Interceptor{}, _q.inters...),
		predicates:            append([]predicate.ReferralWithdrawalAllocation{}, _q.predicates...),
		withPromoter:          _q.withPromoter.Clone(),
		withWithdrawalRequest: _q.withWithdrawalRequest.Clone(),
		withCommission:        _q.withCommission.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPromoter tells the query-builder to eager-load the nodes that are connected to
// the "promoter" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ReferralWithdrawalAllocationQuery) WithPromoter(opts ...func(*UserQuery)) *ReferralWithdrawalAllocationQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPromoter = query
	return _q
}

// WithWithdrawalRequest tells the query-builder to eager-load the nodes that are connected to
// the "withdrawal_request" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ReferralWithdrawalAllocationQuery) WithWithdrawalRequest(opts ...func(*ReferralWithdrawalRequestQuery)) *ReferralWithdrawalAllocationQuery {
	query := (&ReferralWithdrawalRequestClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWithdrawalRequest = query
	return _q
}

// WithCommission tells the query-builder to eager-load the nodes that are connected to
// the "commission" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ReferralWithdrawalAllocationQuery) WithCommission(opts ...func(*ReferralCommissionQuery)) *ReferralWithdrawalAllocationQuery {
	query := (&ReferralCommissionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCommission = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ReferralWithdrawalAllocation.Query().
//		GroupBy(referralwithdrawalallocation.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ReferralWithdrawalAllocationQuery) GroupBy(field string, fields ...string) *ReferralWithdrawalAllocationGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ReferralWithdrawalAllocationGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = referralwithdrawalallocation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ReferralWithdrawalAllocation.Query().
//		Select(referralwithdrawalallocation.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *ReferralWithdrawalAllocationQuery) Select(fields ...string) *ReferralWithdrawalAllocationSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ReferralWithdrawalAllocationSelect{ReferralWithdrawalAllocationQuery: _q}
	sbuild.label = referralwithdrawalallocation.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ReferralWithdrawalAllocationSelect configured with the given aggregations.
func (_q *ReferralWithdrawalAllocationQuery) Aggregate(fns ...AggregateFunc) *ReferralWithdrawalAllocationSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ReferralWithdrawalAllocationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !referralwithdrawalallocation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ReferralWithdrawalAllocationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ReferralWithdrawalAllocation, error) {
	var (
		nodes       = []*ReferralWithdrawalAllocation{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withPromoter != nil,
			_q.withWithdrawalRequest != nil,
			_q.withCommission != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ReferralWithdrawalAllocation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ReferralWithdrawalAllocation{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPromoter; query != nil {
		if err := _q.loadPromoter(ctx, query, nodes, nil,
			func(n *ReferralWithdrawalAllocation, e *User) { n.Edges.Promoter = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withWithdrawalRequest; query != nil {
		if err := _q.loadWithdrawalRequest(ctx, query, nodes, nil,
			func(n *ReferralWithdrawalAllocation, e *ReferralWithdrawalRequest) { n.Edges.WithdrawalRequest = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCommission; query != nil {
		if err := _q.loadCommission(ctx, query, nodes, nil,
			func(n *ReferralWithdrawalAllocation, e *ReferralCommission) { n.Edges.Commission = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ReferralWithdrawalAllocationQuery) loadPromoter(ctx context.Context, query *UserQuery, nodes []*ReferralWithdrawalAllocation, init func(*ReferralWithdrawalAllocation), assign func(*ReferralWithdrawalAllocation, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ReferralWithdrawalAllocation)
	for i := range nodes {
		fk := nodes[i].PromoterUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "promoter_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ReferralWithdrawalAllocationQuery) loadWithdrawalRequest(ctx context.Context, query *ReferralWithdrawalRequestQuery, nodes []*ReferralWithdrawalAllocation, init func(*ReferralWithdrawalAllocation), assign func(*ReferralWithdrawalAllocation, *ReferralWithdrawalRequest)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ReferralWithdrawalAllocation)
	for i := range nodes {
		fk := nodes[i].WithdrawalRequestID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(referralwithdrawalrequest.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "withdrawal_request_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ReferralWithdrawalAllocationQuery) loadCommission(ctx context.Context, query *ReferralCommissionQuery, nodes []*ReferralWithdrawalAllocation, init func(*ReferralWithdrawalAllocation), assign func(*ReferralWithdrawalAllocation, *ReferralCommission)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ReferralWithdrawalAllocation)
	for i := range nodes {
		fk := nodes[i].CommissionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(referralcommission.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "commission_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ReferralWithdrawalAllocationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ReferralWithdrawalAllocationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(referralwithdrawalallocation.Table, referralwithdrawalallocation.Columns, sqlgraph.NewFieldSpec(referralwithdrawalallocation.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, referralwithdrawalallocation.FieldID)
		for i := range fields {
			if fields[i] != referralwithdrawalallocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withPromoter != nil {
			_spec.Node.AddColumnOnce(referralwithdrawalallocation.FieldPromoterUserID)
		}
		if _q.withWithdrawalRequest != nil {
			_spec.Node.AddColumnOnce(referralwithdrawalallocation.FieldWithdrawalRequestID)
		}
		if _q.withCommission != nil {
			_spec.Node.AddColumnOnce(referralwithdrawalallocation.FieldCommissionID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ReferralWithdrawalAllocationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(referralwithdrawalallocation.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = referralwithdrawalallocation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *ReferralWithdrawalAllocationQuery) ForUpdate(opts ...sql.LockOption) *ReferralWithdrawalAllocationQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *ReferralWithdrawalAllocationQuery) ForShare(opts ...sql.LockOption) *ReferralWithdrawalAllocationQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// ReferralWithdrawalAllocationGroupBy is the group-by builder for ReferralWithdrawalAllocation entities.
type ReferralWithdrawalAllocationGroupBy struct {
	selector
	build *ReferralWithdrawalAllocationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ReferralWithdrawalAllocationGroupBy) Aggregate(fns ...AggregateFunc) *ReferralWithdrawalAllocationGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ReferralWithdrawalAllocationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReferralWithdrawalAllocationQuery, *ReferralWithdrawalAllocationGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ReferralWithdrawalAllocationGroupBy) sqlScan(ctx context.Context, root *ReferralWithdrawalAllocationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ReferralWithdrawalAllocationSelect is the builder for selecting fields of ReferralWithdrawalAllocation entities.
type ReferralWithdrawalAllocationSelect struct {
	*ReferralWithdrawalAllocationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ReferralWithdrawalAllocationSelect) Aggregate(fns ...AggregateFunc) *ReferralWithdrawalAllocationSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ReferralWithdrawalAllocationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReferralWithdrawalAllocationQuery, *ReferralWithdrawalAllocationSelect](ctx, _s.ReferralWithdrawalAllocationQuery, _s, _s.inters, v)
}

func (_s *ReferralWithdrawalAllocationSelect) sqlScan(ctx context.Context, root *ReferralWithdrawalAllocationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
