// Code generated by ent, DO NOT EDIT.

package referralwithdrawalrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// PromoterUserID applies equality check predicate on the "promoter_user_id" field. It's identical to PromoterUserIDEQ.
func PromoterUserID(v int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldPromoterUserID, v))
}

// ReviewerUserID applies equality check predicate on the "reviewer_user_id" field. It's identical to ReviewerUserIDEQ.
func ReviewerUserID(v int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldReviewerUserID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldCurrency, v))
}

// PaymentMethod applies equality check predicate on the "payment_method" field. It's identical to PaymentMethodEQ.
func PaymentMethod(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldPaymentMethod, v))
}

// AccountName applies equality check predicate on the "account_name" field. It's identical to AccountNameEQ.
func AccountName(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldAccountName, v))
}

// AccountIdentifier applies equality check predicate on the "account_identifier" field. It's identical to AccountIdentifierEQ.
func AccountIdentifier(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldAccountIdentifier, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldStatus, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldReviewedAt, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldNotes, v))
}

// ReviewNotes applies equality check predicate on the "review_notes" field. It's identical to ReviewNotesEQ.
func ReviewNotes(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldReviewNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLTE(FieldUpdatedAt, v))
}

// PromoterUserIDEQ applies the EQ predicate on the "promoter_user_id" field.
func PromoterUserIDEQ(v int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldPromoterUserID, v))
}

// PromoterUserIDNEQ applies the NEQ predicate on the "promoter_user_id" field.
func PromoterUserIDNEQ(v int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNEQ(FieldPromoterUserID, v))
}

// PromoterUserIDIn applies the In predicate on the "promoter_user_id" field.
func PromoterUserIDIn(vs ...int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIn(FieldPromoterUserID, vs...))
}

// PromoterUserIDNotIn applies the NotIn predicate on the "promoter_user_id" field.
func PromoterUserIDNotIn(vs ...int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotIn(FieldPromoterUserID, vs...))
}

// ReviewerUserIDEQ applies the EQ predicate on the "reviewer_user_id" field.
func ReviewerUserIDEQ(v int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldReviewerUserID, v))
}

// ReviewerUserIDNEQ applies the NEQ predicate on the "reviewer_user_id" field.
func ReviewerUserIDNEQ(v int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNEQ(FieldReviewerUserID, v))
}

// ReviewerUserIDIn applies the In predicate on the "reviewer_user_id" field.
func ReviewerUserIDIn(vs ...int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIn(FieldReviewerUserID, vs...))
}

// ReviewerUserIDNotIn applies the NotIn predicate on the "reviewer_user_id" field.
func ReviewerUserIDNotIn(vs ...int64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotIn(FieldReviewerUserID, vs...))
}

// ReviewerUserIDIsNil applies the IsNil predicate on the "reviewer_user_id" field.
func ReviewerUserIDIsNil() predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIsNull(FieldReviewerUserID))
}

// ReviewerUserIDNotNil applies the NotNil predicate on the "reviewer_user_id" field.
func ReviewerUserIDNotNil() predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotNull(FieldReviewerUserID))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLTE(FieldAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldContainsFold(FieldCurrency, v))
}

// PaymentMethodEQ applies the EQ predicate on the "payment_method" field.
func PaymentMethodEQ(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldPaymentMethod, v))
}

// PaymentMethodNEQ applies the NEQ predicate on the "payment_method" field.
func PaymentMethodNEQ(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNEQ(FieldPaymentMethod, v))
}

// PaymentMethodIn applies the In predicate on the "payment_method" field.
func PaymentMethodIn(vs ...string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIn(FieldPaymentMethod, vs...))
}

// PaymentMethodNotIn applies the NotIn predicate on the "payment_method" field.
func PaymentMethodNotIn(vs ...string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotIn(FieldPaymentMethod, vs...))
}

// PaymentMethodGT applies the GT predicate on the "payment_method" field.
func PaymentMethodGT(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGT(FieldPaymentMethod, v))
}

// PaymentMethodGTE applies the GTE predicate on the "payment_method" field.
func PaymentMethodGTE(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGTE(FieldPaymentMethod, v))
}

// PaymentMethodLT applies the LT predicate on the "payment_method" field.
func PaymentMethodLT(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLT(FieldPaymentMethod, v))
}

// PaymentMethodLTE applies the LTE predicate on the "payment_method" field.
func PaymentMethodLTE(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLTE(FieldPaymentMethod, v))
}

// PaymentMethodContains applies the Contains predicate on the "payment_method" field.
func PaymentMethodContains(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldContains(FieldPaymentMethod, v))
}

// PaymentMethodHasPrefix applies the HasPrefix predicate on the "payment_method" field.
func PaymentMethodHasPrefix(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldHasPrefix(FieldPaymentMethod, v))
}

// PaymentMethodHasSuffix applies the HasSuffix predicate on the "payment_method" field.
func PaymentMethodHasSuffix(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldHasSuffix(FieldPaymentMethod, v))
}

// PaymentMethodEqualFold applies the EqualFold predicate on the "payment_method" field.
func PaymentMethodEqualFold(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEqualFold(FieldPaymentMethod, v))
}

// PaymentMethodContainsFold applies the ContainsFold predicate on the "payment_method" field.
func PaymentMethodContainsFold(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldContainsFold(FieldPaymentMethod, v))
}

// AccountNameEQ applies the EQ predicate on the "account_name" field.
func AccountNameEQ(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldAccountName, v))
}

// AccountNameNEQ applies the NEQ predicate on the "account_name" field.
func AccountNameNEQ(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNEQ(FieldAccountName, v))
}

// AccountNameIn applies the In predicate on the "account_name" field.
func AccountNameIn(vs ...string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIn(FieldAccountName, vs...))
}

// AccountNameNotIn applies the NotIn predicate on the "account_name" field.
func AccountNameNotIn(vs ...string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotIn(FieldAccountName, vs...))
}

// AccountNameGT applies the GT predicate on the "account_name" field.
func AccountNameGT(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGT(FieldAccountName, v))
}

// AccountNameGTE applies the GTE predicate on the "account_name" field.
func AccountNameGTE(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGTE(FieldAccountName, v))
}

// AccountNameLT applies the LT predicate on the "account_name" field.
func AccountNameLT(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLT(FieldAccountName, v))
}

// AccountNameLTE applies the LTE predicate on the "account_name" field.
func AccountNameLTE(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLTE(FieldAccountName, v))
}

// AccountNameContains applies the Contains predicate on the "account_name" field.
func AccountNameContains(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldContains(FieldAccountName, v))
}

// AccountNameHasPrefix applies the HasPrefix predicate on the "account_name" field.
func AccountNameHasPrefix(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldHasPrefix(FieldAccountName, v))
}

// AccountNameHasSuffix applies the HasSuffix predicate on the "account_name" field.
func AccountNameHasSuffix(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldHasSuffix(FieldAccountName, v))
}

// AccountNameIsNil applies the IsNil predicate on the "account_name" field.
func AccountNameIsNil() predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIsNull(FieldAccountName))
}

// AccountNameNotNil applies the NotNil predicate on the "account_name" field.
func AccountNameNotNil() predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotNull(FieldAccountName))
}

// AccountNameEqualFold applies the EqualFold predicate on the "account_name" field.
func AccountNameEqualFold(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEqualFold(FieldAccountName, v))
}

// AccountNameContainsFold applies the ContainsFold predicate on the "account_name" field.
func AccountNameContainsFold(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldContainsFold(FieldAccountName, v))
}

// AccountIdentifierEQ applies the EQ predicate on the "account_identifier" field.
func AccountIdentifierEQ(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldAccountIdentifier, v))
}

// AccountIdentifierNEQ applies the NEQ predicate on the "account_identifier" field.
func AccountIdentifierNEQ(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNEQ(FieldAccountIdentifier, v))
}

// AccountIdentifierIn applies the In predicate on the "account_identifier" field.
func AccountIdentifierIn(vs ...string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIn(FieldAccountIdentifier, vs...))
}

// AccountIdentifierNotIn applies the NotIn predicate on the "account_identifier" field.
func AccountIdentifierNotIn(vs ...string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotIn(FieldAccountIdentifier, vs...))
}

// AccountIdentifierGT applies the GT predicate on the "account_identifier" field.
func AccountIdentifierGT(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGT(FieldAccountIdentifier, v))
}

// AccountIdentifierGTE applies the GTE predicate on the "account_identifier" field.
func AccountIdentifierGTE(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGTE(FieldAccountIdentifier, v))
}

// AccountIdentifierLT applies the LT predicate on the "account_identifier" field.
func AccountIdentifierLT(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLT(FieldAccountIdentifier, v))
}

// AccountIdentifierLTE applies the LTE predicate on the "account_identifier" field.
func AccountIdentifierLTE(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLTE(FieldAccountIdentifier, v))
}

// AccountIdentifierContains applies the Contains predicate on the "account_identifier" field.
func AccountIdentifierContains(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldContains(FieldAccountIdentifier, v))
}

// AccountIdentifierHasPrefix applies the HasPrefix predicate on the "account_identifier" field.
func AccountIdentifierHasPrefix(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldHasPrefix(FieldAccountIdentifier, v))
}

// AccountIdentifierHasSuffix applies the HasSuffix predicate on the "account_identifier" field.
func AccountIdentifierHasSuffix(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldHasSuffix(FieldAccountIdentifier, v))
}

// AccountIdentifierIsNil applies the IsNil predicate on the "account_identifier" field.
func AccountIdentifierIsNil() predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIsNull(FieldAccountIdentifier))
}

// AccountIdentifierNotNil applies the NotNil predicate on the "account_identifier" field.
func AccountIdentifierNotNil() predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotNull(FieldAccountIdentifier))
}

// AccountIdentifierEqualFold applies the EqualFold predicate on the "account_identifier" field.
func AccountIdentifierEqualFold(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEqualFold(FieldAccountIdentifier, v))
}

// AccountIdentifierContainsFold applies the ContainsFold predicate on the "account_identifier" field.
func AccountIdentifierContainsFold(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldContainsFold(FieldAccountIdentifier, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldContainsFold(FieldStatus, v))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLTE(FieldReviewedAt, v))
}

// ReviewedAtIsNil applies the IsNil predicate on the "reviewed_at" field.
func ReviewedAtIsNil() predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIsNull(FieldReviewedAt))
}

// ReviewedAtNotNil applies the NotNil predicate on the "reviewed_at" field.
func ReviewedAtNotNil() predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotNull(FieldReviewedAt))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldContainsFold(FieldNotes, v))
}

// ReviewNotesEQ applies the EQ predicate on the "review_notes" field.
func ReviewNotesEQ(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEQ(FieldReviewNotes, v))
}

// ReviewNotesNEQ applies the NEQ predicate on the "review_notes" field.
func ReviewNotesNEQ(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNEQ(FieldReviewNotes, v))
}

// ReviewNotesIn applies the In predicate on the "review_notes" field.
func ReviewNotesIn(vs ...string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIn(FieldReviewNotes, vs...))
}

// ReviewNotesNotIn applies the NotIn predicate on the "review_notes" field.
func ReviewNotesNotIn(vs ...string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotIn(FieldReviewNotes, vs...))
}

// ReviewNotesGT applies the GT predicate on the "review_notes" field.
func ReviewNotesGT(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGT(FieldReviewNotes, v))
}

// ReviewNotesGTE applies the GTE predicate on the "review_notes" field.
func ReviewNotesGTE(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldGTE(FieldReviewNotes, v))
}

// ReviewNotesLT applies the LT predicate on the "review_notes" field.
func ReviewNotesLT(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLT(FieldReviewNotes, v))
}

// ReviewNotesLTE applies the LTE predicate on the "review_notes" field.
func ReviewNotesLTE(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldLTE(FieldReviewNotes, v))
}

// ReviewNotesContains applies the Contains predicate on the "review_notes" field.
func ReviewNotesContains(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldContains(FieldReviewNotes, v))
}

// ReviewNotesHasPrefix applies the HasPrefix predicate on the "review_notes" field.
func ReviewNotesHasPrefix(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldHasPrefix(FieldReviewNotes, v))
}

// ReviewNotesHasSuffix applies the HasSuffix predicate on the "review_notes" field.
func ReviewNotesHasSuffix(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldHasSuffix(FieldReviewNotes, v))
}

// ReviewNotesIsNil applies the IsNil predicate on the "review_notes" field.
func ReviewNotesIsNil() predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldIsNull(FieldReviewNotes))
}

// ReviewNotesNotNil applies the NotNil predicate on the "review_notes" field.
func ReviewNotesNotNil() predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldNotNull(FieldReviewNotes))
}

// ReviewNotesEqualFold applies the EqualFold predicate on the "review_notes" field.
func ReviewNotesEqualFold(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldEqualFold(FieldReviewNotes, v))
}

// ReviewNotesContainsFold applies the ContainsFold predicate on the "review_notes" field.
func ReviewNotesContainsFold(v string) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.FieldContainsFold(FieldReviewNotes, v))
}

// HasPromoter applies the HasEdge predicate on the "promoter" edge.
func HasPromoter() predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PromoterTable, PromoterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPromoterWith applies the HasEdge predicate on the "promoter" edge with a given conditions (other predicates).
func HasPromoterWith(preds ...predicate.User) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(func(s *sql.Selector) {
		step := newPromoterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReviewer applies the HasEdge predicate on the "reviewer" edge.
func HasReviewer() predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReviewerTable, ReviewerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReviewerWith applies the HasEdge predicate on the "reviewer" edge with a given conditions (other predicates).
func HasReviewerWith(preds ...predicate.User) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(func(s *sql.Selector) {
		step := newReviewerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReferralWithdrawalRequest) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReferralWithdrawalRequest) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReferralWithdrawalRequest) predicate.ReferralWithdrawalRequest {
	return predicate.ReferralWithdrawalRequest(sql.NotPredicates(p))
}
