// Code generated by ent, DO NOT EDIT.

package referralcommission

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the referralcommission type in the database.
	Label = "referral_commission"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPromoterUserID holds the string denoting the promoter_user_id field in the database.
	FieldPromoterUserID = "promoter_user_id"
	// FieldReferredUserID holds the string denoting the referred_user_id field in the database.
	FieldReferredUserID = "referred_user_id"
	// FieldRechargeOrderID holds the string denoting the recharge_order_id field in the database.
	FieldRechargeOrderID = "recharge_order_id"
	// FieldCommissionType holds the string denoting the commission_type field in the database.
	FieldCommissionType = "commission_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSourceAmount holds the string denoting the source_amount field in the database.
	FieldSourceAmount = "source_amount"
	// FieldRateSnapshot holds the string denoting the rate_snapshot field in the database.
	FieldRateSnapshot = "rate_snapshot"
	// FieldCommissionAmount holds the string denoting the commission_amount field in the database.
	FieldCommissionAmount = "commission_amount"
	// FieldReversedAt holds the string denoting the reversed_at field in the database.
	FieldReversedAt = "reversed_at"
	// FieldReversedReason holds the string denoting the reversed_reason field in the database.
	FieldReversedReason = "reversed_reason"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// EdgePromoter holds the string denoting the promoter edge name in mutations.
	EdgePromoter = "promoter"
	// EdgeReferredUser holds the string denoting the referred_user edge name in mutations.
	EdgeReferredUser = "referred_user"
	// EdgeRechargeOrder holds the string denoting the recharge_order edge name in mutations.
	EdgeRechargeOrder = "recharge_order"
	// Table holds the table name of the referralcommission in the database.
	Table = "referral_commissions"
	// PromoterTable is the table that holds the promoter relation/edge.
	PromoterTable = "referral_commissions"
	// PromoterInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	PromoterInverseTable = "users"
	// PromoterColumn is the table column denoting the promoter relation/edge.
	PromoterColumn = "promoter_user_id"
	// ReferredUserTable is the table that holds the referred_user relation/edge.
	ReferredUserTable = "referral_commissions"
	// ReferredUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ReferredUserInverseTable = "users"
	// ReferredUserColumn is the table column denoting the referred_user relation/edge.
	ReferredUserColumn = "referred_user_id"
	// RechargeOrderTable is the table that holds the recharge_order relation/edge.
	RechargeOrderTable = "referral_commissions"
	// RechargeOrderInverseTable is the table name for the RechargeOrder entity.
	// It exists in this package in order to avoid circular dependency with the "rechargeorder" package.
	RechargeOrderInverseTable = "recharge_orders"
	// RechargeOrderColumn is the table column denoting the recharge_order relation/edge.
	RechargeOrderColumn = "recharge_order_id"
)

// Columns holds all SQL columns for referralcommission fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPromoterUserID,
	FieldReferredUserID,
	FieldRechargeOrderID,
	FieldCommissionType,
	FieldStatus,
	FieldSourceAmount,
	FieldRateSnapshot,
	FieldCommissionAmount,
	FieldReversedAt,
	FieldReversedReason,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultCommissionType holds the default value on creation for the "commission_type" field.
	DefaultCommissionType string
	// CommissionTypeValidator is a validator for the "commission_type" field. It is called by the builders before save.
	CommissionTypeValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultSourceAmount holds the default value on creation for the "source_amount" field.
	DefaultSourceAmount float64
	// DefaultRateSnapshot holds the default value on creation for the "rate_snapshot" field.
	DefaultRateSnapshot float64
	// DefaultCommissionAmount holds the default value on creation for the "commission_amount" field.
	DefaultCommissionAmount float64
)

// OrderOption defines the ordering options for the ReferralCommission queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPromoterUserID orders the results by the promoter_user_id field.
func ByPromoterUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromoterUserID, opts...).ToFunc()
}

// ByReferredUserID orders the results by the referred_user_id field.
func ByReferredUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferredUserID, opts...).ToFunc()
}

// ByRechargeOrderID orders the results by the recharge_order_id field.
func ByRechargeOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRechargeOrderID, opts...).ToFunc()
}

// ByCommissionType orders the results by the commission_type field.
func ByCommissionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommissionType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySourceAmount orders the results by the source_amount field.
func BySourceAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceAmount, opts...).ToFunc()
}

// ByRateSnapshot orders the results by the rate_snapshot field.
func ByRateSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateSnapshot, opts...).ToFunc()
}

// ByCommissionAmount orders the results by the commission_amount field.
func ByCommissionAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommissionAmount, opts...).ToFunc()
}

// ByReversedAt orders the results by the reversed_at field.
func ByReversedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReversedAt, opts...).ToFunc()
}

// ByReversedReason orders the results by the reversed_reason field.
func ByReversedReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReversedReason, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByPromoterField orders the results by promoter field.
func ByPromoterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPromoterStep(), sql.OrderByField(field, opts...))
	}
}

// ByReferredUserField orders the results by referred_user field.
func ByReferredUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReferredUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByRechargeOrderField orders the results by recharge_order field.
func ByRechargeOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRechargeOrderStep(), sql.OrderByField(field, opts...))
	}
}
func newPromoterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PromoterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PromoterTable, PromoterColumn),
	)
}
func newReferredUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReferredUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReferredUserTable, ReferredUserColumn),
	)
}
func newRechargeOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RechargeOrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RechargeOrderTable, RechargeOrderColumn),
	)
}
